### ISSUE TITLE
ch-image push: fails for Quay.io

### ISSUE THREAD

**Issue by reidpr** [hpc/charliecloud#1002]
Pushing an image to Quay.io causes HTTP 500 while uploading manifest:

```
$ ch-image push 00_tiny quay.io/charliecloud/test:latest
pushing image:   00_tiny
destination:     quay.io/charliecloud/test:latest
layer 1/1: gathering
layer 1/1: preparing
preparing metadata
starting upload
layer 1/1: 0f73d3d: checking if already in repository
layer 1/1: 0f73d3d: already present
config: 0db8e4b: checking if already in repository
config: 0db8e4b: not present, uploading

Username: reidpr
Password:
manifest: uploading
error: PUT failed; expected status {201, 401} but got 500: Internal Server Error
```

**Comment by heasterday** [comment]
This issue looks similar to the previously reported issue where a Quay instance would 500 after a manifest list was pushed to the instance: https://issues.redhat.com/browse/PROJQUAY-944

**Comment by heasterday** [comment]
To resolve this issue we need to provide contents to `config["history"]` for our pushed images. Quay has a check where it counts the number of layers and compares to the number of entries with content in the `history` and treats the manifest as being malformed if they differ.

OCI image spec for reference: https://github.com/opencontainers/image-spec/blob/main/schema/config-schema.json#L122
