### ISSUE TITLE
ch-image: progress meters for upload/download

### ISSUE THREAD

**Issue by reidpr** [hpc/charliecloud#1003]
Currently, upload and download does not provide any progress indication at all, which is pretty user-unfriendly for anything of non-trivial size. We need something.

Should only be displayed if running interactively on a terminal.

@j-ogas found a nice library for this, though that would add a dependency. I wonder if we could put in something simple written ourselves.

**Comment by reidpr** [comment]
Looks like this needs to be handled differently for uploads and downloads, possibly a wrapped file object and streaming request, respectively.

Also: We currently load the entire response into memory before saving it to a file. That seems bad.

**Comment by rstyd** [comment]
I used a technique like this for a project several years ago. We could write something up natively without too much code. https://stackoverflow.com/a/27871113
