### ISSUE TITLE
ch-run: deal with existing mount points that are symlinks correctly

### ISSUE THREAD

**Issue by loveshack** [hpc/charliecloud#1015]
I tried to run an image built from a linuxcontainers.org rootfs, where /etc/resolv.conf is a link to /run/systemd/resolve/resolv.conf, and the host system doesn't have that link. The touch in ch-tar2dir gives a (non-fatal) error and, more to the point, DNS doesn't work inside the container.  (This looks rather familiar from long ago, maybe not with Charliecloud.)

Shouldn't /etc/resolv.conf be deleted in the image and replaced with an empty file on which to bind mount?  If I modify the script to do that, all is well. That should perhaps be done for other mount points which are always used.

**Comment by loveshack** [comment]
Apologies. I corrected where the touch gets done in the original version of that.

**Comment by reidpr** [comment]
Thanks for the bug report! We'll fix it.

**Comment by loveshack** [comment]
Sorry, I missed the request somehow.  I was actually using a tar image from under https://uk.images.linuxcontainers.org/images/fedora/33/ppc64el/default/ (which will vary with time) and using tar2dir.  I think that was before I found how to do ppc64le docker-ism. It would be the same with the x86_64 version. I was going to provide the patch I've been using in a bit.
