### ISSUE TITLE
ch-image build --force: support UBI8

### ISSUE THREAD

**Issue by qwofford** [hpc/charliecloud#1030]
A package requires the `--force` option. The package is in epel.

When I attempt to install the package without `--force`, I can install epel but I can't install the package.

When I attempt to `--force` the package installation, I can no longer install epel.

Dockerfile reproducer:
```
FROM qwofford/nvidia-cuda-devel:summit_2020-11-25
RUN dnf install -y  https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
RUN dnf update -y
```

**Comment by reidpr** [comment]
The problem is that `ch-image` tries to use the `rhel8` config but the UBI8 image doesn't have a `epel-release` package:

```
+ dnf install -y epel-release
[...]
Error: Unable to find a match: epel-release
```

I note that the Dockefile above installs EPEL with an RPM, not a package name. This is the [recommendation from Fedora](https://fedoraproject.org/wiki/EPEL).

**Comment by reidpr** [comment]
I think the thing to do here is:

1. Change the configs so we install EPEL via RPM. (Possible gotcha: What happens if the Dockerfile *also* installs it via RPM?)
2. Add a UBI8 test for `--force`.
