### ISSUE TITLE
`ch-run`: run images by name

### ISSUE THREAD

**Issue by nspark** [hpc/charliecloud#1058]
When working with `ch-image` to pull, build, and list images, it seems a bit odd that to run the images with `ch-run`, one needs the full path to the image folder. This isn't simply `$CH_IMAGE_STORAGE/$IMAGE:$TAG` but `$CH_IMAGE_STORAGE/img/$IMAGE:$TAG`, which requires a bit of awareness of the structure of `ch-image`'s storage.

Here are two suggestions:

- Provide a `path` subcommand to `ch-image` that takes the image name (as in `list`) and provides the fully-qualified path to the image for use with `ch-run`; e.g.,

      ch-run $(ch-image path foo:1.2.3) bash

- Provide a `run` subcommand to `ch-image` that delegates to `ch-run`; e.g,

      ch-image [image_args...] run [run_args...] foo:1.2.3 bash`.

**Comment by reidpr** [comment]
I agree it's awkward currently.

The reasoning on the current state is: while it's true that currently `ch-image` holds a complete, unpacked copy of every image it handles, this is currently an implementation detail. The structure of the storage directory is undocumented and we plan to keep it that way so we can be flexible moving forward.

The current documented way to run is `ch-builder2tar` followed by `ch-tar2dir`. This does currently have drawbacks: (a) often-needless copy and (b) needlessly complex UI. We do hope to fix at least the latter soon.

That said, if keeping the unpacked images does seem like it will be permanent, a zero-copy way to run directly from builder storage seems good, modulo pitfalls like `ch-run -w` causing inconsistent state.
