### ISSUE TITLE
ch-build: --force causes failures when target Dockerfile also installs EPEL

### ISSUE THREAD

**Issue by heasterday** [hpc/charliecloud#1067]
Currently the `--force` flag for ch-build installs EPEL, installs fakeroot, then disabled EPEL. This leaves the EPEL repo installed but disabled. The side effect of this is that if the Dockerfile also tries to install EPEL, while that operation won't fail, it won't result in EPEL being enabled, leading to the build failing later when trying to install packages from EPEL.

**Comment by heasterday** [comment]
This failure can be reproduced using this example Dockerfile:
```dockerfile
FROM centos:8
RUN dnf install -y epel-release && dnf install -y acme-tiny
```

**Comment by reidpr** [comment]
Some background that we discussed offline but would be good to include here:

* The reason for installing EPEL disabled is that leaving it enabled causes a different but related problem: EPEL has packages with the same name as the main repo but different versions, so EPEL unexpectedly enabled can cause the wrong versions of things to be installed later in the Dockerfile.
* We are investigating a replacement workflow: install EPEL, install fakeroot, uninstall EPEL.
