### ISSUE TITLE
ch-image: push: pigz --no-name adds timestamp to gzip header in older versions

### ISSUE THREAD

**Issue by j-ogas** [hpc/charliecloud#1080]
`pigz` versions older than `2.4` store timestamp metadata in the gzip header when using `--no-name`. This causes `ch-image` to produce different layer hashes for the same image in storage.

notes:
1. if both `pigz` and `gzip` are on the system, `ch-image` will use `pigz`.
2. the pigz version available on centos 7 is `2.3.4`

**Comment by reidpr** [comment]
For background, we do this b/c `pigz` can compress in parallel. If that's not enough of a win, we should just use Python's `gzip` module.
