### ISSUE TITLE
Test for compiling charliecloud as root

### ISSUE THREAD

**Issue by j-ogas** [hpc/charliecloud#11]
Bug source:      /charliecloud/Makefile
Edit: *Added markup syntax, reproduction steps, and expected/observed behavior, and cause*

## Reproduction
After cloning the charliecloud repo, as root in _/charliecloud_, run the following:

1. `$ make` or `make install PREFIX=/local/usr`

## Expected Behavior
Building as root is unsupported; the make should fail.  

## Observed Behavior
Charliecloud compiles successfully
** **
## Cause
The _Makefile_ is missing a test to determine if the user is root.

**Comment by reidpr** [comment]
Let's leave it open until the fix lands on master.

**Comment by j-ogas** [comment]
Update: 

The main Makefile's use of `.PHONY all`makes the prevention of compiling charliecloud as root a little more difficult than expected. 

An option discussed was to include adding the root test in bin/Makefile. The `.PHONY all` line in the bin/Makefile would need to be removed.

**Comment by reidpr** [comment]
Per comments in PR #85, this breaks common use cases, so we won't do it.
