### ISSUE TITLE
`ch-run-oci` hardwired for Buildah

### ISSUE THREAD

**Issue by naterini** [hpc/charliecloud#1109]
Looks like anyone attempting to use ch-run-oci will fail unless they are using it with buildah:

From the source:
>  m = re.search(r"^buildah-buildah(.+)$", cid)

Is it possible to make it generic and more closely follow the OCI runtime spec?
> https://github.com/opencontainers/runtime-spec/blob/1c3f411f041711bbeecf35ff7e93461ea6789220/runtime.md#create

**Comment by reidpr** [comment]
> Is it possible to make it generic and more closely follow the OCI runtime spec?

No, because OCI only provides the bundle path on `create`. Charliecloud does not maintain any state so we don't have anywhere to store the bundle patch.

The kludge could be extended to guess other bundle paths, but that doesn't fix the underlying problem.

Here's a proposal to extend OCI to support this use case: https://supercontainers.github.io/containers-wg/ideas/runtime-stateless_C2
Long list of my gripes with OCI: https://supercontainers.github.io/containers-wg/docs/hpc-projects/charliecloud/
The `ch-run-oci` man page may also be helpful: https://hpc.github.io/charliecloud/command-usage.html#ch-run-oci

**Comment by reidpr** [comment]
To be clear I don't like that it's that way either.

**Comment by naterini** [comment]
> > Is it possible to make it generic and more closely follow the OCI runtime spec?
> 
> No, because OCI only provides the bundle path on `create`. Charliecloud does not maintain any state so we don't have anywhere to store the bundle path.

Looks like crun/runc both will actually start a process that waits for contact from start command for it to actually execute argv. While not pretty, I don't see why it couldn't work for charlie cloud either as the stdio is also done via the create command process. There will likely be need for a '--root' option too that will hold a named socket for the go signal to be reliable. In this case, once the create process dies (and unlinks the socket), all the state should be lost maintaining the statelessness of charliecloud.

**Comment by reidpr** [comment]
> While not pretty

Indeed. Yes, we could do that; however, I'm skeptical of further kludges to work around problems in the standard. Hence why we are participating in the working group to fix the standard.

Do you have a specific use case here? What is the problem you are trying to solve? I'm sure we can help.

**Comment by naterini** [comment]
> > While not pretty
> 
> Indeed. Yes, we could do that; however, I'm skeptical of further kludges to work around problems in the standard. Hence why we are participating in the working group to fix the standard.

I understand not wanting to work around the standard but this adding some annoying limitations to using charlie-cloud OCI support outside of calls from buildah. Being required to specify bundles in /tmp makes using shared filesystems considerably more difficult.

> Do you have a specific use case here? What is the problem you are trying to solve? I'm sure we can help.
I would like to use charliecloud instead of runc/crun for an application (that is not buildah) via OCI runtime complaint calls.

I'll close this issue since I can workaround the workaround for the workaround but I would hope in the future the workarounds will not be required.
