### ISSUE TITLE
`configure`: nVidia check uses wrong `.so`

### ISSUE THREAD

**Issue by hpcpony** [hpc/charliecloud#1123]
This is something that caused me a bit of trouble until I debugged it. Someone can decide if it should be addressed:

The configure script tests for the presence of NVIDIA libraries with:

```
if test -n "$NVIDIA_CLI"; then :
  if nvidia-container-cli list | grep -Fq libnvidia-glcore.so; then :
  have_nvidia_libs=yes
else
  have_nvidia_libs=no
fi
else
  have_nvidia_libs=no
fi
```

libnvidia-glcore seems to be an OpenGL/GLX library which is missing from my system (setup for GPU compute).  I hacked the test to find a file that nvidia-container-cli finds on my system and was then able to get the build to proceed with NVIDIA.

Might it be better to pick a file other than libnvidia-glcore that is more commonly found across graphics _and_ compute GPU systems?  (Sorry but I'm not sure what the best file would be.)

For completeness, here's what ```nvidia-container-cli list``` finds on my machines:

[hpcpony@ugpu1 lib]$ nvidia-container-cli list
/dev/nvidiactl
/dev/nvidia-uvm
/dev/nvidia-uvm-tools
/dev/nvidia-modeset
/dev/nvidia0
/dev/nvidia1
/dev/nvidia2
/dev/nvidia3
/usr/bin/nvidia-smi
/usr/bin/nvidia-debugdump
/usr/bin/nvidia-persistenced
/usr/bin/nvidia-cuda-mps-control
/usr/bin/nvidia-cuda-mps-server
/usr/lib64/libnvidia-ml.so.450.80.02
/usr/lib64/libnvidia-cfg.so.450.80.02
/usr/lib64/libcuda.so.450.80.02
/usr/lib64/libnvidia-opencl.so.450.80.02
/usr/lib64/libnvidia-ptxjitcompiler.so.450.80.02
/usr/lib64/libnvidia-allocator.so.450.80.02
/usr/lib64/libnvidia-compiler.so.450.80.02
/usr/lib64/vdpau/libvdpau_nvidia.so.450.80.02
/usr/lib64/libnvidia-encode.so.450.80.02
/usr/lib64/libnvidia-opticalflow.so.450.80.02
/usr/lib64/libnvcuvid.so.450.80.02
/usr/lib64/libnvidia-fbc.so.450.80.02
/usr/lib64/libnvidia-ifr.so.450.80.02
/usr/lib/libnvidia-ml.so.450.80.02
/usr/lib/libcuda.so.450.80.02
/usr/lib/libnvidia-opencl.so.450.80.02
/usr/lib/libnvidia-ptxjitcompiler.so.450.80.02
/usr/lib/libnvidia-allocator.so.450.80.02
/usr/lib/libnvidia-compiler.so.450.80.02
/usr/lib/vdpau/libvdpau_nvidia.so.450.80.02
/usr/lib/libnvidia-encode.so.450.80.02
/usr/lib/libnvidia-opticalflow.so.450.80.02
/usr/lib/libnvcuvid.so.450.80.02
/usr/lib/libnvidia-fbc.so.450.80.02
/usr/lib/libnvidia-ifr.so.450.80.02

**Comment by reidpr** [comment]
I agree. I was the one who picked that library but I don't know much about GPGPU either. 😂

For what it's worth, `configure` doesn't make any decisions based on that test IIRC. It just goes in the report.

@samuelkgutierrez?

**Comment by samuelkgutierrez** [comment]
I'm not familiar with the configure script, but searching for something like `libcuda.so` is probably a safer bet. That said, I'm no expert.

**Comment by hpcpony** [comment]
I changed it to libcuda.so, but maybe just testing that nvidia-container-cli exists (if that's the real requirement) or that it produces a reasonable (i.e. non empty) output would be sufficient.  But...  If the test really doesn't matter I'd suggest some sort of message like "not found: ok  (nvidia-container-cli must be available at runtime)" (or something similar).  As it is, one (or at least me) thinks you have to build on a host with the NVIDIA stuff installed, and that the configure can find it, and that what gets built is (probably) different than the non-NVIDIA build.  Knowing that what I'd already built for my non-NVIDIA install of charliecloud would have worked would certainly have simplified my life. ;^)

**Comment by reidpr** [comment]
Good point. There's a section called "Caveat" at the beginning on the `configure` report to that effect, but I'm sure it could be improved.

Most of the items reported would need a caveat similar to what you suggested, so I'm a bit skeptical of putting them individually. But you have a legitimate concern.

Looking over the report as a whole, what clarity suggestions do you have? (Or am I misinterpreting that you think the report is what needs to be changed?)

**Comment by hpcpony** [comment]
Not sure I have a perfect solution but at a minimum maybe just add a "(ok, deferred to runtime)" message if the tests fail. Maybe a simple page in the documentation about "working with NVIDIA" to address some of the quirks would help as well.
