### ISSUE TITLE
build failure when -j 2 or larger is used

### ISSUE THREAD

**Issue by olifre** [hpc/charliecloud#115]
I just stumbled across the following while building:
```
make -j9 -l8 -C doc-src                                                                   
make: Entering directory '/var/tmp/portage/sys-cluster/charliecloud-9999/work/charliecloud-9999/doc-src'                     
sphinx-build -W -b html -D release="$(cat ../VERSION)" -D version="$(git rev-parse --short HEAD)" -d _build/doctrees   . _build/html                           
sphinx-build -b man -D release="$(cat ../VERSION)" -D version="$(git rev-parse --short HEAD)" -d _build/doctrees   . _build/man
Running Sphinx v1.6.3                                                                                                               
Running Sphinx v1.6.3                                                                                          
making output directory...                                                                    
making output directory...

Exception occurred:
loading pickled environment... not yet created
  File "/usr/lib64/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 17] File exists: '/var/tmp/portage/sys-cluster/charliecloud-9999/work/charliecloud-9999/doc-src/_build/doctrees'
The full traceback has been saved in /var/tmp/portage/sys-cluster/charliecloud-9999/temp/sphinx-err-M0Wd6R.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 25 source files that are out of date
make: *** [Makefile:144: man] Error 1
make: *** Waiting for unfinished jobs....
```
In a subsequent build, I could not reproduce, but got the following, and things went fine:
```
make -j9 -l8 -C doc-src                  
make: Entering directory '/var/tmp/portage/sys-cluster/charliecloud-9999/work/charliecloud-9999/doc-src'
sphinx-build -W -b html -D release="$(cat ../VERSION)" -D version="$(git rev-parse --short HEAD)" -d _build/doctrees   . _build/html
sphinx-build -b man -D release="$(cat ../VERSION)" -D version="$(git rev-parse --short HEAD)" -d _build/doctrees   . _build/man
Running Sphinx v1.6.3                                                           
making output directory...                                                       
Running Sphinx v1.6.3                                                                   
making output directory...                                                                                                                                     
loading pickled environment... not yet created                                                                              
loading pickled environment... not yet created                                                                                      
building [mo]: targets for 0 po files that are out of date                                
building [man]: all manpages
updating environment: 25 added, 0 changed, 0 removed
building [mo]: targets for 0 po files that are out of date
```
So it seems that `sphinx-build` may end up very unhappy if it is invoked twice at the very same moment in time with the same `doctrees` directory (at least if it does not exist yet). 

Probably not so easy to reproduce, I just hit it by chance... 

Also pinging @wiene since this has shown up after addition of the man page target.

**Comment by wiene** [comment]
@olifre, do you have any idea how probable the above error is? I just ran

`for i in {1..50}; do make clean && make -j8; sleep 2; done`

in the doc-src directory and I did not see this error a single time. Either my approach to reproduce the problem is flawed or this error happens quite rarely.

**Comment by olifre** [comment]
@wiene I can reproduce it with almost 100 % probability using the following incantation:
```
sudo sh -c 'echo 3 > /proc/sys/vm/drop_caches' && rm -rf doc-src/_build && make -j9  -C doc-src
```
This involves two magic tricks:
1. When the file caches are flushed, the almost, but not fully simultaneous startups of the `sphinx-build` processes are more likely to fully synchronize (even SSDs are "slow") so the race condition is triggered. 
2. `make clean` is insufficient, it will not remove `doc-src/_build`. 

Both these conditions are not unlikely on an actual freshly booted host. In my case, I used a freshly booted machine on which `sphinx-build` was not yet invoked before, and used a fresh git checkout (by building in portage's sandbox, Gentoo's package build system). 

So I think a fresh boot and usage of a fresh git checkout should also yield a high reproduction probability, but is certainly more cumbersome. 
It may also be related to available IO performance of course. 


I can not reproduce anymore after changing the incantation to:
```
sudo sh -c 'echo 3 > /proc/sys/vm/drop_caches' && rm -rf doc-src/_build && mkdir -p doc-src/_build/doctrees && make -j9  -C doc-src
```
Of course, race conditions may still happen inside the `doctrees` directory, I am unsure how exactly `sphinx-build` uses it. 
The underlying reason for the fault is likely something like this happening:
1. First instance of `sphinx-build` checks whether `_build/doctrees` exists, it does not. 
2. Second instance of `sphinx-build` checks whether `_build/doctrees` exists, it does not. 
3. First instance of`sphinx-build` decides the folder needs to be created. 
4. Second instance of`sphinx-build` decides the folder needs to be created. 
5. First instance of `sphinx-build` creates the folder. 
6. Second instance of `sphinx-build` fails to create the folder, since it already exists => fatal error. 

So the actual ugliness happens in `sphinx-build`, it seems they fall into a race condition such as the one discussed at:
https://stackoverflow.com/questions/21517227/how-to-avoid-a-race-condition-with-makedirs

I digged a bit deeper into the sources of `sphinx-build` and found that their current master branch uses a syntax which is _not_ subject to this flaw! 
Checking the history, it seems it was fixed here:
https://github.com/sphinx-doc/sphinx/pull/4282
a few months ago (by a long-term Gentoo developer), see also https://github.com/sphinx-doc/sphinx/issues/4281 . 

Funnily enough, this was only in December 2017, so no distro (including Gentoo) has the fix as of yet. 

So I would propose the following:
1. Use the `mkdir -p _build/doctrees` hack before invoking the `sphinx-build` processes. 
2. Add a comment that this is a temporary workaround for an issue fixed in newer Sphinx releases (>= 1.6.6). 
3. Drop this workaround again when newer sphinx-releases are widely adopted. 

Other suggestions?

**Comment by reidpr** [comment]
Folks: Can someone who can reproduce it easily please test PR #116?

As for `make clean`: if invoked within `doc-src`, it does remove `_build/*`. However at the top level, it indeed does not descend into `doc-src`. I could be easily convinced this behavior is erroneous. If you agree, please file a new issue or PR.

**Comment by olifre** [comment]
@reidpr : PR #116 reliably fixes the issue for me, without that I could reproduce with almost 100 % using the `drop_caches` technique.
