### ISSUE TITLE
examples/obspy: image comparison fails during testing

### ISSUE THREAD

**Issue by heasterday** [hpc/charliecloud#1171]
On my test machine (Ubuntu 20.04), the obspy tests are filing with the following:
```
   /home/heasterday/charliecloud/examples/obspy/obspy.png /tmp/ch-test.tmp.heasterday/bats.tmp/obspy.png differ: char 71, line 3
```

**Comment by reidpr** [comment]
We'll just drop the PNG compare for now. Long-term, perhaps we want a more sophisticated image comparison; that's issue #1172.
