### ISSUE TITLE
debian link can cause conflicts with debian directory used by packaging tools

### ISSUE THREAD

**Issue by wiene** [hpc/charliecloud#118]
Since commit 18c2dda Charliecloud contains a link `debian` pointing to `packaging/debian`. This link creates a conflict with the `debian` directory of the [official Debian packaging repository for Charliecloud](https://salsa.debian.org/hpc-team/charliecloud). I suppose @olifre's idea to put the packaging files in a separate directory was to avoid conflicts like this. Otherwise he would have faced similar problems with his [openSUSE build service builds](https://build.opensuse.org/project/show/home:ubn:charliecloud), I guess.

Therefore my suggestion would be to remove this link if there is no particular reason to keep it.

**Comment by olifre** [comment]
> I suppose @olifre's idea to put the packaging files in a separate directory was to avoid conflicts like this. Otherwise he would have faced similar problems with his openSUSE build service builds, I guess.

Exactly, this was the initial reason. There appear to be all kinds of different techniques:
- https://github.com/ceph/ceph uses `debian`
- https://github.com/htcondor/htcondor hides it in `build/packaging`

I guess the best would be to go what's easiest for Debian packaging.

**Comment by reidpr** [comment]
I put it there; I'm sorry for the hassle.

The reasoning was to give a one-liner that builds a `.deb` from the upstream source code. For example, see lines 33–39 of `test/travis.sh`, which in turn invokes `packaging/debian/travis.sh`. With the symlink there, you can just `debuild`.

This is only one of the failures to follow best practices in the Debian packaging. I'd love to get it in better shape. Would it work to put the official Debian packaging in `packaging/debian` and leave the link in place?

As for an immediate fix to this bug, I can remove the link from the repository and create/remove it in `packaging/debian/travis.sh`. Is there a better approach we should do now?

**Comment by wiene** [comment]
I found a way to tell `gbp` to ignore the debian link. This fixes the problem for the official Debian packaging repository but I suppose that the current structure still requires using patched tarballs to get successful builds on the Open Build Service (which might be a tool to address #100)

**Comment by reidpr** [comment]
OK.

What's the appropriate thing for me to do now to address this bug?

**Comment by wiene** [comment]
All deb packaging tools which I know (like `git-buildpackage` and the Open Build Service) keep the upstream source and - at some point - add a `debian` directory to the root of the upstream directory structure before starting the actual package build process. If the upstream source already contains a `debian` directory/file/link, you get a conflict during the merge of the upstream source and the `debian` directory.

One can pass filter rules to `git-buildpackage` to avoid this clash. Unfortunately whatever rule I tried, it always removes both the `debian` link and the `packaging/debian` directory when importing the latest Charliecloud release. Even if this does not cause a technical problem for the build process, this is not what I want the tool to do (maybe because I was not smart enough to use the tool correctly).

For the Open Build Service, the only workaround I know is a manual removal of the debian link from the Charliecloud tarball and use modified "upstream" sources.

So this is not a problem of Charliecloud itself but it only shows up in the interplay between Charliecloud and packaging tools. As such it is a matter of taste whether one adjusts Charliecloud accordingly or not.

If you do not mind changing Charliecloud, one option I could think of is: Remove the `debian` link in the Charliecloud root directory and instead add a `deb` target to the `Makefile` which is not built by default. This target creates the link on demand and builds the deb package. This way one probably keeps the comfort which one has now without interfering with the workflow of packaging tools.
