### ISSUE TITLE
document docutils version dependency

### ISSUE THREAD

**Issue by vsoch** [hpc/charliecloud#119]
Hey charlies! This is likely a trivial thing, but I'm going through the install instructions (very detailed, awesome!) and I am hitting a warning (that gets --> error) about building the docs:

```
make
mkdir -p _build/doctrees
sphinx-build -W -b html -D release="$(cat ../VERSION)" -D version="$(git rev-parse --short HEAD)" -d _build/doctrees   . _build/html
Running Sphinx v1.4.6
making output directory...
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 25 source files that are out of date
updating environment: 25 added, 0 changed, 0 removed
reading sources... [100%] virtualbox                                                                                         

Warning, treated as error:
/home/vanessa/Packages/charliecloud/doc-src/install.rst:136: ERROR: Error in "list-table" directive:
invalid option value: (option: "widths"; value: 'auto')
invalid literal for int() with base 10: 'auto'.

.. list-table::
   :widths: auto

   * - Distribution versions
     - proposed for *Buster* and *Stretch backports*
   * - Maintainers
     - Lucas Nussbaum (:code:`lucas@debian.org`)
       and Peter Wienemann (:code:`wienemann@physik.uni-bonn.de`)
   * - Bug reports to
     - Charliecloud's GitHub issue tracker
   * - Packaging source code
     - in Charliecloud: :code:`packaging/debian`

Makefile:56: recipe for target 'html' failed
make: *** [html] Error 1
```
I tried this with a fresh clone (with `--recursive`) and after a make clean. I first saw it running the larger set of test suite and then decided to try make on just the docs folder. Is there a particular version of sphinx (or another dependency) that I should be using? 

Perhaps if this is an issue that gets in the way of having a seamless "getting started" the test for building the docs could be removed from the larger test suite? That way, the user learning it (this guy! errr gal!) doesn't get stuck on start.

**Comment by vsoch** [comment]
And maybe we could export these environment variables as defaults, or provide a file so the user doens't need to copy paste manually?

```
$ export CH_TEST_TARDIR=/var/tmp/tarballs
$ export CH_TEST_IMGDIR=/var/tmp/images
$ export CH_TEST_PERMDIRS='/var/tmp /tmp'
```

**Comment by reidpr** [comment]
It looks like the `widths` option came about in docutils version 0.13.1, released in December 2016. ([changelog](http://docutils.sourceforge.net/HISTORY.txt)).

docutils comes about because it's depended on by Sphinx.

I believe the fix is to document our docutils dependency, either with or without a patch to make older versions work.

I'm willing to do the former myself, but I'd need a PR for the latter.

**Comment by reidpr** [comment]
As for the environment variables, those are host specific so I don't think it'd be appropriate to provide defaults. I'm open to argument, but please open a new issue in that case.

**Comment by vsoch** [comment]
I think just the documentation of the versions would be sufficient, at least in my case I would have installed the correct version and built without a hitch! The environment variables is probably not necessary, but nice for the lazy amongst us (<-- me).
