### ISSUE TITLE
Test-build sanity check: is the user root?

### ISSUE THREAD

**Issue by j-ogas** [hpc/charliecloud#12]
Bug source:      /charliecloud/test/common.bash

## Reproduction
Assuming the user successfully compiled Charliecloud:

As root, in _/charliecloud/test/_, run `$ make test-build` 

## Expected Behavior
Compiling and building as root is unsupported; `$ make test-build` should fail.  

## Observed Behavior
The test build runs successfully
** **
## Cause
There is no test in common.bash to determine if the user is root

**Comment by reidpr** [comment]
Per comments in PR #85, this breaks common use cases, so we won't do it.
