### ISSUE TITLE
clarify installation needs and source code location in tutorial

### ISSUE THREAD

**Issue by vsoch** [hpc/charliecloud#120]
Heyo! I'm trying out the "90 seconds getting started"

```
$ ch-build -t hello ~/charliecloud
Sending build context to Docker daemon 15.67 MB
[...]
Successfully built 1136de7d4c0a
$ ch-docker2tar hello /var/tmp
57M /var/tmp/hello.tar.gz
$ ch-tar2dir /var/tmp/hello.tar.gz /var/tmp
creating new image /var/tmp/hello
/var/tmp/hello unpacked ok
$ ch-run /var/tmp/hello -- echo "I'm in a container"
I'm in a container
```
I found the executables in bin, which I've installed just locally to `/home/vanessa/Packages/charliecloud` but I'm not clear what should go into this command here:
```
$ ch-build -t hello ~/charliecloud
```
The help suggests it's the same as Docker, 
```
./ch-build --help
Wrapper for "docker build" that works around some of its annoying behaviors.

Usage:

  $ ch-build [ARGS ...]

ARGS are passed unchanged to "docker build" after the workaround arguments.

Workarounds:

  * Add the HTTP proxy environment variables with "--build-arg".

  * Default to the Dockerfile in CWD with "--file", if one exists and --file
    wasn't already specified, rather than the one at the root of the build
    context. This works around Docker's hostility to symlinks (e.g., see
    https://github.com/docker/docker/issues/1676).
```
in which case `hello` is the container I'm building, and the last part should reference a folder. Should there be a Dockerfile in the base charliecloud folder that is missing?

```
./bin/ch-build -t hello /home/vanessa/Packages/charliecloud/
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/vanessa/Packages/charliecloud/Dockerfile: no such file or directory
```
Thanks for the help!

**Comment by vsoch** [comment]
okay, going to try with my own Dockerfile!

```
ch-build -t snakemake.ch .
```
It's building!!

**Comment by vsoch** [comment]
boum!

```
ch-run /var/tmp/snakemake.ch scif

Scientific Filesystem [v0.0.72]
usage: scif [-h] [--debug] [--quiet] [--writable]
            {version,pyshell,shell,preview,help,install,inspect,run,apps,dump,exec}
            ...

scientific filesystem tools

optional arguments:
  -h, --help            show this help message and exit
  --debug               use verbose logging to debug.
  --quiet               suppress print output
  --writable, -w        for relevant commands, if writable SCIF is needed

actions:
  actions for Scientific Filesystem

  {version,pyshell,shell,preview,help,install,inspect,run,apps,dump,exec}
                        scif actions
    version             show software version
    pyshell             Interactive python shell to scientific filesystem
    shell               shell to interact with scientific filesystem
    preview             preview changes to a filesytem
    help                look at help for an app, if it exists.
    install             install a recipe on the filesystem
    inspect             inspect an attribute for a scif installation
    run                 entrypoint to run a scientific filesystem
    apps                list apps installed
    dump                dump recipe
    exec                execute a command to a scientific filesystem
```
You know if chariecloud doesn't support entrypoints, scif is so perfect! check this out:

```
ch-run /var/tmp/snakemake.ch /opt/conda/bin/scif apps
       bwa
  samtools
 snakemake
graphviz_create_dag
vanessa@vanessa-ThinkPad-T460s:~/Documents/Dropbox/Code/scif/examples/snakemake.scif$ ch-run /var/tmp/snakemake.ch /opt/conda/bin/scif help bwa
    Burrows-Wheeler Aligner
vanessa@vanessa-ThinkPad-T460s:~/Documents/Dropbox/Code/scif/examples/snakemake.scif$ ch-run /var/tmp/snakemake.ch /opt/conda/bin/scif run bwa
[bwa] executing /bin/bash /scif/apps/bwa/scif/runscript

Program: bwa (alignment via Burrows-Wheeler transformation)
Version: 0.7.17-r1188
Contact: Heng Li <lh3@sanger.ac.uk>

Usage:   bwa <command> [options]

Command: index         index sequences in the FASTA format
         mem           BWA-MEM algorithm
         fastmap       identify super-maximal exact matches
         pemerge       merge overlapping paired ends (EXPERIMENTAL)
         aln           gapped/ungapped alignment
         samse         generate alignment (single ended)
         sampe         generate alignment (paired ended)
         bwasw         BWA-SW for long queries

         shm           manage indices in shared memory
         fa2pac        convert FASTA to PAC format
         pac2bwt       generate BWT from PAC
         pac2bwtgen    alternative algorithm for generating BWT
         bwtupdate     update .bwt to the new format
         bwt2sa        generate SA from BWT and Occ

Note: To use BWA, you need to first index the genome with `bwa index'.
      There are three alignment algorithms in BWA: `mem', `bwasw', and
      `aln/samse/sampe'. If you are not sure which to use, try `bwa mem'
      first. Please `man ./bwa.1' for the manual.
```

**Comment by vsoch** [comment]
thank you!

**Comment by reidpr** [comment]
The context directory for the examples in the source code needs to be Charliecloud source code directory, not the installation `$PREFIX`. Looks like this needs to be clarified.

Docker also has problems with symlinks, so that may be an additional complication.

See issue #34 for entry points. (We are not going to support the SCI-F image format but you can set up whatever inside the image, of course.)

**Comment by vsoch** [comment]
Thanks for the details! SCIF isn't something that needs to be integrated, you just install the client with pip and then run a command to install it to the container, e.g.

```
scif install recipe.scif
```

In the case of Charliecloud, it works pretty well thus far because I'm just starting with the Docker image that has the software, and then I can hit the single scif entrypoint that controls handling the entrypoints, environments, and running stuffs for all the guts in the container. And no, definitely it's not needed to have any formal integration.

**Comment by JiaweiZhuang** [comment]
Google search brings me here... Also confused by this.

> The context directory for the examples in the source code needs to be Charliecloud source code directory, not the installation $PREFIX.

Is the "context directory" same as Docker context?  From [Docker docs](https://docs.docker.com/engine/reference/commandline/build/#extended-description):

> The docker build command builds Docker images from a Dockerfile and a “context”. A build’s context is the set of files located in the specified PATH or URL. The build process can refer to any of the files in the context. For example, your build can use a COPY instruction to reference a file in the context.

So, Docker's context directory basically contains files that you want copy into the image. But why the context dir for Charliecloud is Charliecloud source code? What directory should I use if I install the pre-built binary using package manager (e.g. https://packages.ubuntu.com/bionic/charliecloud)?

**Comment by reidpr** [comment]
I'll address that in a new issue.
