### ISSUE TITLE
document foreign architecture images

### ISSUE THREAD

**Issue by loveshack** [hpc/charliecloud#1268]
After responding to an assertion that you can't build container images for ppc64le on amd64, I looked for something about it in the docs.  I can't see anything about building images for foreign architectures, and --arch might mislead people to think it will just work generally.  Anyway, it does basically just work after installing (on Debian) the qemu-user-static package to support execution in the container.  (The -static version is necessary.)  Unfortunately that isn't in current RHEL/EPEL, but is in Fedora; I haven't checked elsewhere.

Related to that, I wonder if it's worth mentioning images.linuxcontainers.org as a source of much rootfs for when you can't pull something off docker hub (like --arch ppc64le CentOS in my case).

**Comment by reidpr** [comment]
This sounds like a good FAQ, yes. Would you be interested in submitting a draft of your procedure as a PR? We don't know enough about this area to do so based on the notes above.

**Comment by loveshack** [comment]
I'll try to concoct something when I have a chance.

I've since noticed a nuisance that if I use --arch to pull, say, a
debian:11 ppc64le image on x86_64 and then try to use `FROM debian:11`
for a native build, it picks up the foreign one.  I wonder if there's a
workaround for that.

The something else occurred to me in the spirit of unprivileged
operation, which we like:  You can't do a foreign build that isn't a
straight pull and unpack without an obviously privileged installation of
the kernel binfmt hooks to make the virtualization work transparently.
However, I think you could make dockerfiles work for foreign images
anyway if there was a hook for RUN (possibly elsewhere?) to allow the
command to be prefixed by the appropriate qemu-...-static command, like
PRoot's -q:

```
      -q command, --qemu=command
              Execute guest programs through QEMU as specified by command.

              Each time a guest program is going to be executed, PRoot inserts
              the QEMU user-mode command in  front  of  the  initial  request.
              That way, guest programs actually run on a virtual guest CPU em‐
              ulated by QEMU user-mode.
```

You can install the qemu-user-static binaries in $HOME somewhere for use
with a hook like that, if you've acquired them by unpacking a system
package or whatever, and you should then be all set without a
cooperative system manager.

Does that sound plausible?  I haven't looked at doing it.

**Comment by reidpr** [comment]
> I'll try to concoct something when I have a chance.

Fantastic, thank you.

> I've since noticed a nuisance that if I use --arch to pull, say, a debian:11 ppc64le image on x86_64 and then try to use `FROM debian:11` for a native build, it picks up the foreign one. I wonder if there's a workaround for that.

One workaround would be to rename the image at pull time; however this is kind of awkward because you can't specify the name of the pulled image. You would have to pull the image to a directory (i.e., not to `ch-image` storage) and then `ch-image import` that directory.

> Does that sound plausible? I haven't looked at doing it.

Maybe. `ch-run` replaces itself (with `exec(2)`) with the user command, but by the time it does so it's inside the container, so invoking a host binary at that point seems hairy. However I'd expect the same problem to arise if QEMU is installed by the package manager, so maybe there's a way to make it work. I might have more ideas once I see your existing procedure. I agree it sounds cool and indeed in the unprivileged spirit.

**Comment by loveshack** [comment]
Forget the idea of a hook for qemu without privileges.  If I was awake I'd have realized it won't deal with shebangs and subprograms, just one binary.  You can use PRoot to install into the initial image though.  I'll provide an example.  It works with PRoot only because it intercepts syscalls.

(My original idea was to use a native sh along with qemu, both copied into the container, and a SHELL definition.)

**Comment by reidpr** [comment]
FWIW, these folks have something for Docker that sounds possibly unprivileged install? https://dbhi.github.io/qus/faq.html

**Comment by loveshack** [comment]
> FWIW, these folks have something for Docker that sounds possibly
> unprivileged install? https://dbhi.github.io/qus/faq.html

That's also using binfmt hooks as far as I can tell.  You have to hook
into exec somehow; I think PRoot uses a combination of preload and
seccomp to do it unprivileged.  It's probably quite a rare requirement,
but PRoot will satisfy it on x86_64, and probably aarch64.

[Thinking of PRoot and things in this space, I haven't used it, but I
wonder if you know of https://indigo-dc.github.io/udocker/ just as a
point of interest.  It does say you need docker to build images,
surprisingly.]
