### ISSUE TITLE
unable to pull images built with kaniko

### ISSUE THREAD

**Issue by adrecord** [hpc/charliecloud#1280]
kaniko creates image layers with questionable content.  Specifically it [leaves an absolute root `/` entry](https://github.com/GoogleContainerTools/kaniko/blob/2ea368dde8e4ecde31f2265863ab5f40721c8ac4/pkg/util/tar_util.go#L85-L87) in all image layers on top of the base layer.  This is reported in https://github.com/GoogleContainerTools/kaniko/issues/1375.  Additionally kaniko leaves absolute hard link targets.  `ch-image pull` rejects layers for both of these reasons, making most images build with kaniko not pullable by ch-image build and also not useable as a base for images build by ch-image build.

I think kaniko should not be including entries like these in the image layers, but it would be nice if charliecloud was more tolerant of these entries, as docker and tar are.

#### Steps to Reproduce

1. Build image with kaniko and push to a registry.  Here I'm using the kaniko docker image `gcr.io/kaniko-project/executor:debug` and building an alpine based image and pushing it to docker hub as `someuser/test:latest`.  I'm mounting in my docker config.json to the place kaniko looks for it to be able to push.

```
$ printf 'FROM alpine:latest\nRUN apk add bash' | docker run --rm -i \
-v ~/.docker/config.json:/kaniko/.docker/config.json \
gcr.io/kaniko-project/executor:debug \
--dockerfile /dev/stdin --destination someuser/test:latest
```

2. Now try pulling the image with charliecloud...

```
$ ch-image pull someuser/test:latest
pulling image:    someuser/test:latest
....
validating tarball members
error: rejecting zero-length member path: /var/tmp/someuser.ch/dlcache/ec64d77e9a028729916a6743d6712a4d371075ea3cc0edda95690a37cb8af342.tar.gz
```

You can see the root entry...

```
$ tar Ptvf /var/tmp/someuser.ch/dlcache/ec64d77e9a028729916a6743d6712a4d371075ea3cc0edda95690a37cb8af342.tar.gz /
drwxr-xr-x 0/0               0 2022-02-11 01:15 /
```

After working around the root entry failure, ch-image pull failed again with the below error...

```
error: rejecting absolute hard link target: /var/tmp/someuser.ch/dlcache/ec64d77e9a028729916a6743d6712a4d371075ea3cc0edda95690a37cb8af342.tar.gz: etc/terminfo/v/vt220 -> /etc/terminfo/v/vt200
```

... because kaniko is also leaving absolute hard link targets in the image:

```
$ tar Ptvf /var/tmp/someuser.ch/dlcache/ec64d77e9a028729916a6743d6712a4d371075ea3cc0edda95690a37cb8af342.tar.gz etc/terminfo/v/vt220
hrw-r--r-- 0/0               0 2021-11-21 02:21 etc/terminfo/v/vt220 link to /etc/terminfo/v/vt200
```

**Comment by reidpr** [comment]
Hello, thanks for the very nice bug report. I agree both that Kaniko should not do this and that Charliecloud should work with the images anyway.

I see you have a patch; any chance you could submit this as a PR?

**Comment by adrecord** [comment]
submitted PR https://github.com/hpc/charliecloud/pull/1281

**Comment by reidpr** [comment]
I can reproduce this with:

```
$ printf 'FROM alpine:3.9\nRUN apk add bash\n' | sudo docker run --rm -i -v /root/.docker:/kaniko/.docker gcr.io/kaniko-project/executor:debug --dockerfile /dev/stdin --destination $repo/kanikotest:latest --build-arg http_proxy=$http_proxy --build-arg https_proxy=$https_proxy --build-arg no_proxy=$no_proxy
$ ch-image pull $repo/kanikotest:latest
[...]
error: rejecting zero-length member path: /var/tmp/reidpr.ch/dlcache/0f0005c87622dcf8999b38c5439228e34b405aa645e4cf391e7b925a1064fcd3.tar.gz
```
