### ISSUE TITLE
ch-image: build cache: move Git metadata out-of-band

### ISSUE THREAD

**Issue by j-ogas** [hpc/charliecloud#1285]
See #1255.

**Comment by reidpr** [comment]
Currently, the git repository for each image is stored in-band in the standard location, `.git` at the top of the working directory. This prevents the image from having any files named `.git` at the top level. We could instead put the repo somewhere else, using `GIT_DIR` and `GIT_WORK_TREE` environment variables (or `--git-dir` and `--git-work-tree`).

**Comment by reidpr** [comment]
Issue #1541 describes actual breakage caused by this.

**Comment by reidpr** [comment]
`.gitignore` could go in [`bucache/info/exclude`](https://git-scm.com/docs/gitignore).
