### ISSUE TITLE
confusing error when storage directory already exists

### ISSUE THREAD

**Issue by hpcpony** [hpc/charliecloud#1299]
My /var/tmp are often "noexec" (it's a pretty standard security action and not easy to simply "turn off").  I stumbled across CH_IMAGE_STORAGE at https://hpc.github.io/charliecloud/tutorial.html#seconds-to-charliecloud.  Strangely if you use a directory that already exists ch-image complains and fails

```
[user@host c7]$ setenv CH_IMAGE_STORAGE /scr/user/tmp
[user@host c7]$ mkdir /scr/user/tmp
[user@host c7]$ ls -ld /scr/user/tmp
drwxr-xr-x 2 user users 6 Mar  5 15:42 /scr/user/tmp/

[user@host c7]$ ch-image build --force .
error: storage directory seems invalid: /scr/user/tmp
```
After poking around in charliecloud.py I found what it wanted to see, and added those. Then things "worked":
```
[user@host c7]$ mkdir /scr/user/tmp/img
[user@host c7]$ mkdir /scr/user/tmp/dlcache

[user@host c7]$ ch-image build --force .
upgrading storage directory: v2 /scr/user/tmp
inferred image name: c7
  2 FROM centos:7
manifest list: downloading: 100%
manifest: downloading: 100% 
config: downloading: 100%
layer 1/1: 2d473b0: downloading: 72.6/72.6 MiB (100%)
flattening image
layer 1/1: 2d473b0: listing
validating tarball members
resolving whiteouts
layer 1/1: 2d473b0: extracting 
image arch: amd64
will use --force: rhel7: CentOS/RHEL 7
  4 RUN ['/bin/sh', '-c', 'cat /etc/redhat-release']
CentOS Linux release 7.9.2009 (Core)
warning: --force specified, but nothing to do
grown in 2 instructions: c7
```
Strangely if you set CH_IMAGE_STORAGE to a directory that does _NOT_ exist.  Then it happily creates it rather than failing:
```
[user@host c7]$ rm -rf /scr/user/tmp
[user@host c7]$ ls -ld /scr/user/tmp
ls: cannot access /scr/user/tmp: No such file or directory

[user@host c7]$ ch-image build --force .
initializing storage directory: v2 /scr/user/tmp
inferred image name: c7
  2 FROM centos:7
manifest list: downloading: 100%
manifest: downloading: 100% 
config: downloading: 100%
layer 1/1: 2d473b0: downloading: 72.6/72.6 MiB (100%)
flattening image
layer 1/1: 2d473b0: listing
validating tarball members
resolving whiteouts
layer 1/1: 2d473b0: extracting
image arch: amd64
will use --force: rhel7: CentOS/RHEL 7
  4 RUN ['/bin/sh', '-c', 'cat /etc/redhat-release']
CentOS Linux release 7.9.2009 (Core)
warning: --force specified, but nothing to do
grown in 2 instructions: c7
```

I guess this isn't really a bug, but it sure is a quirky behavior that occupied the majority of my afternoon figuring out (and only then because one time I "accidentally" typed `rm -rf /scr/user/tmp` instead of my usual `rm -rf /scr/user/tmp/*`)

**Comment by reidpr** [comment]
Thanks for the bug report!

The reasoning here is that Charliecloud wants a directory that it completely owns, which is why it wants to create it. The right incantation in your case might be `CH_IMAGE_STORAGE=/scr/user/tmp/${USER}.ch`.

That said, I can see how this is a usability problem. We could add a hint to the error message and maybe a FAQ entry.
