### ISSUE TITLE
add Spack example

### ISSUE THREAD

**Issue by reidpr** [hpc/charliecloud#130]
@hppritcha has requested an example of using [Spack](https://spack.io/) to install in a container.

**Comment by j-ogas** [comment]
I have successfully installed Spack in a Dockerfile image. You can see the Dockerfile  [here](https://github.com/hpc/charliecloud/tree/spack_example/examples/other/spack/Dockerfile).
  
I am currently in the process of reading through the Spack documentation to determine an appropriate use case (test) that would be appealing to demo in the charliecloud test suite. What exactly would be the intended use case for a container with Spack? To manage packages in other containers across a cluster?

Aside, I should note that this Dockerfile takes a **very long** time to build. We're talking 40 minutes or so in my dinky test environment (single node Ubuntu 16 VM).

**Comment by reidpr** [comment]
That's great Jordan!

My intended use case would be simply to demonstrate that Spack works inside a Charliecloud container, i.e., that one way to build a container image is to use Spack to install your stuff.

So options would include installing some basic things and perhaps running the Spack test suite if there is one.

That build time sounds not great but also not outlandish. Depending on the choices in the previous paragraph, maybe it can be optimized.

Perhaps check with @rspavel for advice? He's a local Spack expert.

**Comment by j-ogas** [comment]
So far so good. 

The initial [tests](https://github.com/hpc/charliecloud/blob/spack_example/examples/other/spack/test.bats) I have made appear to be working. Right now the tests consist of basic Spack commands and the installation of the "mpileak" package. More to come. 

The longest portion of the image build appears to be the installation the **Spack Core Utilities** environment modules (40 minutes). I will investigate whether or not I can get away with avoiding this once I have some more tests in place. Also note that the mpileak installation test is taking quite a long time too.  I imagine you want this example classified as _full scope_?

**Comment by j-ogas** [comment]
Update:

I have found that Spack does have unit testing. So far we have:

`993 passed, 2 failed, 82 skipped, 1 xfailed in 444.95 seconds`

The errors have to do with assertion, specifically file differences. I'm not sure if it is appropriate to roll out the console error message here. So I will spare you, for the meantime. ;)

**Comment by reidpr** [comment]
closed by PR #164
