### ISSUE TITLE
deleting image may fail with write-protected files

### ISSUE THREAD

**Issue by loveshack** [hpc/charliecloud#1303]
An arch image -- at least the ones I've built -- has no write permission on some files/directories, so deleting the image with an explicit `ch-image deleted`, or as part of rebuilding it, fails.  Presumably the thing to do is a recursive chmod iff the rmtree fails with errno 13, or possibly do it unconditionally beforehand.  I'll leave an implementation to you as I'm not sure how best to do it.

**Comment by reidpr** [comment]
We already did something like this (CentOS has a similar problem) but sounds like there's a gap.

Can you supply a reproduction recipe? Both of the following work for me (admittedly on the branch for PR #1276, not master):

```
$ ch-image pull archlinux:latest && ch-image delete archlinux:latest
$ printf 'FROM archlinux:latest\n' | ch-image build -t foo - && ch-image delete foo
```

**Comment by loveshack** [comment]
I thought that was a suitable recipe, but obviously not.  (It looked familiar as something that should have been fixed.)

Anyway, I now can't reproduce it, sorry.  The only cause I can think of is mixing what I was testing with commands from an old version.

**Comment by reidpr** [comment]
Charliecloud isn't very good about being atomic; one thing that sometimes happens to me is that I control-C a pull and it exits before fixing the permissions. Then I have an un-deleteable image.

I wonder if this issue should be re-opened, and what to do is add a permissions fix step to `ch-image delete`?
