### ISSUE TITLE
use external build of PMIx in OpenMPI examples

### ISSUE THREAD

**Issue by reidpr** [hpc/charliecloud#135]
Per @hppritcha, this will provide better portability than the PMIx bundled with OpenMPI.

There are no Debian packages.

I think we download the source here: https://github.com/pmix/pmix/releases

**Comment by heasterday** [comment]
@reidpr It looks like OpenMPI 3.x only supports the PMIx 2.x series so we should only need to build it externally if there was a bug in the internal PMIx that we were hitting. In case that ever happens I pushed a branch "external-pmix" that shows how to do that. I recommend closing this issue for now.

**Comment by reidpr** [comment]
Thank you!
