### ISSUE TITLE
FTBFS on RHEL7, etc.

### ISSUE THREAD

**Issue by reidpr** [hpc/charliecloud#136]
Charliecloud doesn't build at all (i.e., `make` fails) on RHEL7, CentOS7, etc. because `make all` at the source code root in turn runs `make all` in `test`, which invokes `test/make-auto`, which since the merge of PR #102 needs Python 3, but these distributions don't include Python 3 (just 2.7).

I am inclined to revert and revisit the PR.

**Comment by dirtyharrycallahan** [comment]
FTBFS : Fails To Build From Source

**Comment by reidpr** [comment]
Thanks to @mej for reporting this bug.
