### ISSUE TITLE
`ch-image`: list sha256 hash of container

### ISSUE THREAD

**Issue by qwofford** [hpc/charliecloud#1365]
I like that `ch-image list <container>` shows information about a container both on the remote and in the local CH_IMAGE_STORAGE. I would like to see sha256 info about the remote and local containers too. For example:
```
$ ch-image list myregistry.com/group/tag
details of image:    myregistry.com/group/tag:latest
sha256 remote:       abcdef01234
sha256 local:        43210fedcba
...
```

This feature would allow someone to easily capture the state of a containerized application as the container is deployed. This feature is important to establish application provenance at runtime.

Current practice would require reading a manifest JSON out of CH_IMAGE_STORAGE, and then locating the correct manifest hash in the list of manifest hashes that define the state of the container. This seems too hard...

**Comment by reidpr** [comment]
Important subtlety, copied from the PR:

> [F]or images that are available remotely `ch-image list` will now give the associated sha256 hash for each available architecture. One thing worth noting is that it does not provide the hash for local images (local hash is not calculated until the image is prepared for upload, so it isn't always available).
