### ISSUE TITLE
MD5 error in FIPS mode

### ISSUE THREAD

**Issue by mphinney1100** [hpc/charliecloud#1367]
When trying to build 00_tiny I ran into this error: 
```
File "/home/mphinney/charliecloud/bin/../lib/charliecloud/lark/load_grammar.py", line 1146, in do_import
h = hashlib.md5(text.encode('utf8')).hexdigest()                                                                                                                                             
ValueError: [digital envelope routines: EVP_DigestInit_ex] disabled for FIPS 
```

FIPS mode causes issues with MD5. 
https://code.djangoproject.com/ticket/28401

**Comment by lucaudill** [comment]
re-assigning the issue to @mphinney1100, since the issue seems to only be reproducible on your system

**Comment by lucaudill** [comment]
Just a quick note about what I learned while looking into the issue: 
The line that appears to be throwing the error isn't a part of Charliecloud, it's in `lark`, which seems (at least from my naive perspective) to limit our ability to address it. Reid suggested checking to see if a newer version of `lark` fixes the issue. Alternatively, we could try to monkey patch it. Good luck!

**Comment by reidpr** [comment]
From the current `hashlib` docs:

> *Changed in version 3.9:* All hashlib constructors take a keyword-only argument *usedforsecurity* with default value `True`. A false value allows the use of insecure and blocked hashing algorithms in restricted environments. `False` indicates that the hashing algorithm is not used in a security context, e.g. as a non-cryptographic one-way compression function.

(Emphasis in original.)

**Comment by mphinney1100** [comment]
Just tested again without updating hashlib.md5 and I didn't run into that error. Issue might be moot
