### ISSUE TITLE
`ch-image delete` should remove all stages

### ISSUE THREAD

**Issue by reidpr** [hpc/charliecloud#1368]
For multi-stage images, `ch-image delete` only removes the last stage. It should instead remove all stages.

**Comment by j-ogas** [comment]
@reidpr Does  #1447 make this issue moot? For example, deleting by glob now gives users an explicit means to remove an image and any stages, e.g., `ch-image delete foo*` deletes all `_stage*` references in storage.

**Comment by reidpr** [comment]
I think no. You're right that the glob makes it possible for users to delete all stages in one command, but it also requires them to know more about how images are stored internally than they really need to. My take is that this issue stands.

**Comment by reidpr** [comment]
Closed by PR #1474.
