### ISSUE TITLE
ch-image: image reference: reference syntax error with multistage

### ISSUE THREAD

**Issue by j-ogas** [hpc/charliecloud#1369]
`ch-image` will error about reference syntax if the image reference contains a colon and the Dockerfile has multistage instructions.

Problem reference.
```
$ ch-image build --force  -t sles15.sp1:openmpi.4.1.3 -f Dockerfile.openmpi.4.1.3 .
error: image ref syntax, char 25: sles15.sp1:openmpi.4.1.3/_stage0
hint: https://hpc.github.io/charliecloud/faq.html#how-do-i-specify-an-image-reference
```

If we replace the colon with an underscore it works.
```
$ ch-image build --force --cache -t sles15.sp1_openmpi.4.1.3 -f Dockerfile.openmpi.4.1.3 .
  8. FROM opensuse/leap:15.1 AS leap
manifest list: downloading: 100%
manifest: downloading: 100%
[...]
```

**Comment by reidpr** [comment]
This happens because `/` can't appear in the tag, and we append `/_stageN` with a slash. If we instead appended just `_stageN` (no slash) I think it would work.
