### ISSUE TITLE
"Charliecloud in 90 seconds" fails on Debian/testing

### ISSUE THREAD

**Issue by Trophime** [hpc/charliecloud#137]
Hi,
Trying to run the very first command from the doc:
```
ch-build -t hello ~/charliecloud
```
gives me:
```
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/.../charliecloud/Dockerfile: no such file or directory
```
To reproduce the pb, just install `charliecloud` and run  `ch-build`command.
Maybe I'm missing a Dockerfile but that's not clear from the tutorial.

Thanks for your help
Best

**Comment by Trophime** [comment]
To run `example/serial/hello/Dockerfile` shall be moved to `git clone directory`

**Comment by Trophime** [comment]
But then:
```
ch-run /var/tmp/hello -- echo "I'm in a container"
ch-run: error: Operation not permitted (ch-run.c:514 1)
```

**Comment by reidpr** [comment]
I am sorry for the trouble!

The `ch-build` failure is because the docs are missing a `cd` command; see issue #138. I'm sorry for this rather obvious oversight.

As for the `ch-run` error on Debian Buster: On Stretch at least you need an additional `sysctl` to enable user namespaces: `kernel.unprivileged_userns_clone=1`.

What output do you get from the following:

```
$ sysctl kernel.unprivileged_userns_clone
kernel.unprivileged_userns_clone = 1
```

If it's zero, that might be your problem.

In that case, would you try:

1. `$ examples/syscalls/pivot_root`. You should get a similar error as `ch-run`.
2. `$ sudo sysctl kernel.unprivileged_userns_clone=1`
3. `$ examples/syscalls/pivot_root`. It should print `ok`.

If that works, set the `sysctl` in a permanent way and you should be OK.

**Comment by Trophime** [comment]
> The ch-build failure is because the docs are missing a cd command; see issue #138. I'm sorry for this rather obvious oversight.

This won't be enough since `Dockerfile` includes `COPY examples... `  instruction
the `COPY`directive shall also be fixed

As for `ch-run` the `kernel.unprivileged_userns_clone` is indeed 0.
What is the impact of this change?

**Comment by reidpr** [comment]
> This won't be enough since Dockerfile includes COPY examples... instruction
> the COPYdirective shall also be fixed

`COPY` is relative to the context directory, which is the last argument to `ch-build` (here `~/charliecloud`), not the current working directory.

All the examples use the root of the source code as the context directory for consistency.

> As for ch-run the kernel.unprivileged_userns_clone is indeed 0.
> What is the impact of this change?

Debian-specific implications, I'm not sure of. I run this way. You'd need to check the Debian documentation on it. If you scare up some good links, I'm happy to add them to the documentation.

If you prefer, you can also compile in the setuid mode for testing. Then Charliecloud doesn't need the user namespace. This mode is not tested as well though, and we don't recommend it for production use.

**Comment by wiene** [comment]
> As for ch-run the kernel.unprivileged_userns_clone is indeed 0.
What is the impact of this change?

The reason for the Debian default settings is explained here: https://lists.debian.org/debian-kernel/2018/02/msg00097.html

**Comment by reidpr** [comment]
@Trophime, does the above information address your concern? If not, how else can we help on this matter?

**Comment by Trophime** [comment]
@reidpr I've just tried with 0.13 release. I still have issue with the tutorial:
```
hello$ uname -a
Linux calcul19 5.4.0-3-amd64 #1 SMP Debian 5.4.13-1 (2020-01-19) x86_64 GNU/Linux
hello$ lsb_release -cs
bullseye
hello$ sudo sysctl kernel.unprivileged_userns_clone
kernel.unprivileged_userns_clone = 1
images/hello$ ch-run /var/tmp/hello -- echo "I'm in a container"
ch-run[12095]: error (ch_core.c:406)
```

**Comment by reidpr** [comment]
Thanks for the report @Trophime. This part of the code has changed a lot, and I'm pretty sure this is a different problem, so I'll create a new issue.
