### ISSUE TITLE
cache reset while garbage collection is running crashes and corrupts storage directory

### ISSUE THREAD

**Issue by StripedMonkey** [hpc/charliecloud#1406]
(we believe) After building an image there is a race condition that results from the cleaning up of the git repos. This results in the cleanup failing. This then subsequently causes any attempts to build things to fail, as the images are not in the cache properly.

```
deleting build cache
error: can't recursively delete directory /var/tmp/bstormer.ch/bucache: gc.pid: No such file or directory
initializing empty build cache
 12. FROM ubuntu:20.04
manifest list: downloading: 100%
manifest: downloading: 100%
config: using existing file
layer 1/1: d7bfe07: using existing file
error: command failed with code 128: git checkout -B 'ubuntu+20.04#' root
 12. FROM ubuntu:20.04
manifest list: downloading: 100%
manifest: downloading: 100%
config: using existing file
layer 1/1: d7bfe07: using existing file
error: command failed with code 128: git checkout -B 'ubuntu+20.04#' root
```
The command `ch-image build-cache --reset && ch-image build --force -f Dockerfile.almalinux8` with things in the cache already should produce this error.

**Comment by reidpr** [comment]
I can repro with (on a new cache):

```
ch-image build --force -t almalinux8 -f examples/Dockerfile.almalinux8 . && ch-image build-cache --reset
```

Note that after this, the storage directory will be broken and some `ch-image delete` will be required to recover.
