### ISSUE TITLE
ch-image list show most recent modification

### ISSUE THREAD

**Issue by qwofford** [hpc/charliecloud#1413]
It would be handy to see a timestamp that reflects the most recently pulled image along with the output of ch-image list. Something like:

```
$ ch-image list
myregistry.com/my_container:mytag   | Thu Jul 21 09:07:10 MDT 2022
```

**Comment by reidpr** [comment]
@qwofford, are you thinking you want (a) the most-recently pulled image to be flagged somehow, e.g.:

```
$ ch-image list
foo
bar  | most recent, Thu Jul 21 09:07:10 MDT 2022
```

or (b) to show when each image was most recently pulled, e.g.:

```
$ ch-image list
foo  | Thu Jul 21 09:07:10 MDT 2022
bar  | Fri Feb 30 08:09:12 MDT 2022
```
