### ISSUE TITLE
remove Lark version ceiling

### ISSUE THREAD

**Issue by wiene** [hpc/charliecloud#1432]
At present the maximum allowed Lark version is [set to 0.12.0](https://github.com/hpc/charliecloud/blob/1804ea4dd27b83d036a0bb4ebb5220d6c9d2cd40/lib/charliecloud.py#L47). Is there a technical reason for this constraint (Lark version 1.0.0 involves [breaking changes](https://github.com/lark-parser/lark/releases/tag/1.0.0) but I have not checked whether they affect charliecloud)? Are there plans to lift this limit to allow for more recent versions?

**Comment by reidpr** [comment]
Thanks. My *guess* is that 0.12 is the most recently tested version, with the caveat that system Lark is tested pretty cursorily. Only the bundled Lark goes through the full test suite.

I see that our GitHub Actions CI installs `lark-parser`, not `lark`, from PyPI, and this is still there but never advanced past 0.12.0, so we didn't notice the new version.

Looking at the breaking changes in 1.0.0, I also guess none of these will be a problem for Charliecloud.

I think the first thing to do is install `pip install lark` instead, update the max version, and see if CI passes.

**Comment by reidpr** [comment]
I don't remember why we had a version ceiling so we're just going to allow any version greater than the minimum.
