### ISSUE TITLE
remove detailed information from --help output

### ISSUE THREAD

**Issue by reidpr** [hpc/charliecloud#144]
Currently, the executables print detailed help when `--help` is specified. This is redundant with the man pages.

While it would be preferable for `--help` to be relatively comprehensive, I fear we do not have the human resources to keep it up to date and consistent with the man pages. Thus, let's reduce `--help` to be a short usage message with a pointer to the man pages and the online documentation.

**Comment by mej** [comment]
Or perhaps use [help2man](https://www.gnu.org/software/help2man/)?

**Comment by reidpr** [comment]
Regarding `help2man`: right now we generate the man pages from the Sphinx documentation. If there's some enhancement to build `--help` output from the same source as the man pages, whichever direction it goes, I'd be interested in a future issue and/or pull request.
