### ISSUE TITLE
fix `File_Metadata` class

### ISSUE THREAD

**Issue by lucaudill** [hpc/charliecloud#1455]
There are a number of changes that should be made to the `File_Metadata` class. This includes the addition of an attribute that returns a path object representing the file in question. 

It should be noted that any changes made to `File_Metadata` will need to be accounted for in the unpickling process for the sake of compatibility with older versions of the class.

**Comment by lucaudill** [comment]
Note: I'm adding comments in the code that point out places where we could use the proposed `File_Metadata.path` attribute. These comments reference this issue by number, so finding them should just be a matter of performing the appropriate search.

**Comment by reidpr** [comment]
Closed by PR #1465.
