### ISSUE TITLE
`ch-run`: don’t mount user home by default

### ISSUE THREAD

**Issue by j-ogas** [hpc/charliecloud#1470]
Remove user home directory from default binds. Make `--no-home` default behavior and replace it with, `--home`, a convenience argument that binds the user home directory.

Unlike the other default binds, the user's home directory:

1. isn't required for functionality or hardware visibility; rather, it is primarily included for convenience, e.g., dotfiles for interactive sessions; and
2. can cause obscure, unintended runtime behavior when dotfiles manipulate environment variables like `PATH`, `PYTHONHOME`, `MPI_HOME`, etc.

Default binds should not have unintended run time consequences.

**Comment by qwofford** [comment]
This caught my attention. After reading the issue description, I agree with the logic. I vote for a big obvious announcement on version release! In bold! With colors! @azukaitis
