### ISSUE TITLE
docker2tar: use pv for status reporting 

### ISSUE THREAD

**Issue by junghans** [hpc/charliecloud#148]
docker2tar can take a while, using `pv` (http://www.ivarch.com/programs/pv.shtml) might help users to stay patient!

**Comment by olifre** [comment]
Thinking just now - shouldn't we also make `pv` a "recommends" for the debian / rpm package? 
For Gentoo, I'm bumping the ebuild just now, and will add pv as optional dependency. 
Pinging @wiene as Debian maintainer to collect another opinion on this.

**Comment by junghans** [comment]
@olifre when you make that Gentoo PR please assign it to me!

**Comment by olifre** [comment]
@junghans I don't have permissions to do so, I'm only a proxy maintainer and no Gentoo dev (yet) ;-). 
But you can probably self-assign it, I guess? Here it is: https://github.com/gentoo/gentoo/pull/8391

**Comment by junghans** [comment]
We should make a spack package, too!

**Comment by junghans** [comment]
spack/spack#8106

**Comment by wiene** [comment]
> Thinking just now - shouldn't we also make pv a "recommends" for the debian / rpm package?

In the Debian case I think adding `pv` to the list of "Suggests" would be reasonable. For the RPM world "Recommends" is probably appropriate.
