### ISSUE TITLE
ch-image import: lack of history metadata leads to assertion error when pushing.

### ISSUE THREAD

**Issue by j-ogas** [hpc/charliecloud#1513]
Related to #1215 and #1002.

Images in storage derived from `ch-image import` that do not have: a) any history entries in their metadata; or b) a history entry without `empty_value: false`, will trigger an assertion error or traceback due to:

```python
    assert(non_empty_winner is not None)
```
and
```python
if (   "empty_layer" not in hist[i].keys() [...]
```
 respectively.  This can be avoided if `ch-image import` is updated to add a history metadata when imported, e.g.,
 
 ```json
 {
    "history": [
      { "empty_layer": false,
        "command": "ch-image import foo bar"},
    ]
}
 ```

**Comment by reidpr** [comment]
Do you have a detailed reproducer, e.g. maybe starting with `ch-pull`, `ch-convert`, `ch-image reset`, `ch-image import`?

**Comment by j-ogas** [comment]
> Do you have a detailed reproducer, e.g. maybe starting with `ch-pull`, `ch-convert`, `ch-image reset`, `ch-image import`?

```
$ ch-image pull alpine
$ ch-image convert alpine /tmp/alpine.tar.gz
$ ch-image reset
$ ch-image import /tmp/alpine.tar.gz alpine
$ ch-image push alpine foo/test_repo
```
