### ISSUE TITLE
`ch-image pull` doesn’t work with Harbor registry

### ISSUE THREAD

**Issue by vandsten** [hpc/charliecloud#1542]
Hi,
Problems when we pull images with charliecloud version 0.30 on hpc.
If we execute "ch-image pull" of the image located in Docker hub we have no problem. But when we try to pull images located in registry harbor, whether the project is private or public, it always fails. When we configure the project as private, even passing it --auth does not ask for the username/password in interactive mode. We have also tried using CH_IMAGE_USER variables, etc, but it also fails. Previously it also happened to us with version 0.28, we have compiled 0.30 and we are still the same.
```

[user@server ~]$ ch-image -vvv --auth --password-many --tls-no-verify pull registry.server.example/hpc/centos7:latest
verbose level: 3
host architecture from uname: x86_64
host architecture for registry: amd64
registry authentication: True
found storage dir v4: /var/tmp/user.ch
validating storage directory: /var/tmp/user.ch
executing: git --version
git version 2.31.1
git version OK: 2.31.1 ≥ 2.28.1
using default build cache mode
deleted 0 stale worktree metadatas
re-linked worktrees in 0.000s
build cache mode: enabled (large=inf)
start
  image_ref
    ir_hostport	registry.server.example
    ir_path	hpc
    ir_name	centos7
    ir_tag	latest

pulling image:    registry.server.example/hpc/centos7:latest
requesting arch:  amd64
downloading image: registry.server.example/hpc/centos7:latest
initializing session
auth: no authorization
GET: https://registry.server.example:443/v2/hpc/centos7/manifests/latest
error: GET failed: HTTPSConnectionPool(host='registry.server.example', port=443): Max retries exceeded with url: /v2/hpc/centos7/manifests/latest (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc3608326d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

```
Trying with the same harbor registry server with docker client works perfectly.

Any help or reproduction of the problem will help.

Best regards

**Comment by reidpr** [comment]
Sorry about that.

This:

> Failed to establish a new connection: [Errno 101] Network is unreachable

suggests some kind of network problem, e.g. are you behind a proxy that is configured for Docker but not Charliecloud?

Can you point us to a public image on a public Harbor server so we can try to reproduce?

**Comment by vandsten** [comment]
I feel ashamed. Sorry for wasting time. Indeed it was a network access problem, it is obvious, the confusion was that the tests were being carried out from 2 different computers that were supposed to have the same level of access to the harbor service, it was not like that.

Best regards.

**Comment by reidpr** [comment]
Glad it worked out! Please don't feel ashamed though. I'd much rather get a bug report that turns out to be a different than not get one because the reporter wasn't 100% sure in their diagnosis.
