### ISSUE TITLE
multistage build: cannot reference alias from previous stage(s)

### ISSUE THREAD

**Issue by j-ogas** [hpc/charliecloud#1571]
Reproducer:
```docker
FROM alpine as a
RUN echo foo

FROM a as b
RUN echo bar

FROM b
RUN echo qux
```

Expected behavior: image builds without issue.

Actual behavior:
```
$ ch-image build -t multi .
  1. FROM alpine AS a
[...]
  4. FROM a AS b
error: unauthorized or not in registry: registry-1.docker.io:443/library/a:latest
hint: if your registry needs authentication, use --auth
```

It appears to fail for one or more of the following reasons: (1) the tag has `:latest` appended by default, (2) ch-image does store images in storage with their alias, i.e., there is no `a`, `b`, or `c` in storage; rather there is `multi_stage0`, etc., and (3) ch-image doesn't check if the FROM argument matches an previous stage image alias.

**Comment by reidpr** [comment]
Closed by PR #1581.
