### ISSUE TITLE
can’t `ch-convert` from Docker if UID > 2²¹

### ISSUE THREAD

**Issue by yaghobvtm** [hpc/charliecloud#1573]
Hello,
we are quite large university using Charliecloud for a while in our HPC center. Every person on the university (staff, student) receives unique random 10-digit number. Recently we have started using this unique number as UID for any unix user (we have used some other mapping previously). And here comes the problem.
There is a function `dockman_to_tar` in the `ch-convert` script. In this function we call `docker export` command, which unfortunately exports the docker image in old tar format with limitations for UID<2^21. Following `tar rf` command then fails with error:
> tar: value 88889462 out of uid_t range 0..2097151
> tar: Exiting with failure status due to previous errors

We have made some changes in the script, although it is not the best solution, it takes some time. Moreover, we should test UID<2^21 etc. It extracts the old tar from docker to a temporary directory and then recreate it using tar command. The following diff is valid for version 0.31.
[ch-convert-diff.txt](https://github.com/hpc/charliecloud/files/10825786/ch-convert-diff.txt)
Best regards,
Jakub

**Comment by reidpr** [comment]
Hi, thanks for the bug report! Very much appreciated.

This is an interesting subtlety, and I don't have better ideas off the top of my head, but I can poke at it a bit.
