### ISSUE TITLE
Charliecloud logs to stderr by default

### ISSUE THREAD

**Issue by wiene** [hpc/charliecloud#1603]
[Charliecloud logs to stderr](https://github.com/hpc/charliecloud/blob/0637911c027c94ba9c91933bdf6b15fe4340134d/lib/charliecloud.py#L117) by default. Often test frameworks consider it a failure if anything is written to stderr (unless otherwise specified). Therefore I wonder whether logging to stderr is done deliberately or whether this happens by mistake.

**Comment by reidpr** [comment]
Yes, that’s on purpose — substantive output to stdout, status chatter (logging) to stderr.

There is an environment variable you can set ([`CH_LOG_FILE`](https://hpc.github.io/charliecloud/ch-image.html#environment-variables)) to send it to a file instead, but it has side effects.

You probably saw that we have a fairly-standard `DEBUG`, `INFO`, `WARNING`, `ERROR` logging hierarchy. We could add `-q`/`--quiet` to change the log level from `INFO` to `WARNING`, which might meet these test frameworks’ expectations better. Would that help?

**Comment by reidpr** [comment]
Great! Since that's a different thing than changing the default log destination, I'll close this as WONTFIX and we'll proceed in the linked bug I just made.
