### ISSUE TITLE
FROM ARG: all cache hits when value of ARG changes

### ISSUE THREAD

**Issue by j-ogas** [hpc/charliecloud#1638]
Reproduce:
```
$ ch-image reset
$ ch-image import alpine.tar.gz alpine
[...]
$ ch-image import debian.tar.gz debian
[...]
$ ch-image build -t foo -f - . <<EOF
arg base=alpine
from $base
run touch foo
EOF
[...]
$ ch-image build --build-arg base=debian -t foo -f - . <<EOF
arg base=alpine
from $base
run touch foo
EOF
  1  ARG base='debian'
  2* FROM debian
  3* run touch foo
[...]
copying image from cache ...
```

`run touch foo` should not hit when the base image is changed.

**Comment by reidpr** [comment]
I suspect this is an error in how the state ID is computed for FROM. I know we take variables into account for things like `RUN`.

Note that we consider variable values for the cache when they are used, not when the are set like Docker. Hence no hit/miss at all for that `ARG`.

**Comment by reidpr** [comment]
Closing as duplicate in favor of #1658, which has a better characterization of the problem.
