### ISSUE TITLE
base.sh hangs when docker has been replaced with podman

### ISSUE THREAD

**Issue by rstyd** [hpc/charliecloud#1656]
We ran into an issue on certain systems where running ch-convert or any charliecloud shell script on flux across multiple nodes hangs indefinitely:

`flux run -N 2 ch-convert -i tar -o dir /tmp/neo4j-3.5.34.tar.gz /tmp/neo4j`

After some debugging and messing around with charliecloud code, I figured out commenting out the docker function in base.sh solves the issue. 

https://github.com/hpc/charliecloud/blob/6d094f51913be34f5e917c039476333ebad5accb/lib/base.sh#L148-L157

Checking docker info on these systems yields:

```
[rustyd@system:~]$ docker info
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
WARN[0000] Network file system detected as backing store.  Enforcing overlay option `force_mask="700"`.  Add it to storage.conf to silence this warning
```

We also tried `flux run -N 1 docker info` and that blocks as well so it looks like it's really a podman issue. We're going to submit an issue to podman as well, but until they resolve it charliecloud will have issues as well.

**Comment by reidpr** [comment]
Fixed by PR #1699 but wasn't linked before merge.
