### ISSUE TITLE
`ch-image build`: `--force=fakeroot` outputs to stderr despite `-q`

### ISSUE THREAD

**Issue by wiene** [hpc/charliecloud#1773]
As a workaround for #1772 I switched to the `fakeroot` mode on s390x. Doing this I noticed that for this mode debug output is written to `/dev/stderr` despite of the `--quiet` option. This is caused by using `set -ex` on RHEL as it is done [here](https://github.com/hpc/charliecloud/blob/5f2db10a0daea609f3bd6b9788f00d0f4c53f407/lib/force.py#L186) and [here](https://github.com/hpc/charliecloud/blob/5f2db10a0daea609f3bd6b9788f00d0f4c53f407/lib/force.py#L201).

**Comment by reidpr** [comment]
I suspect that `--force=fakeroot` will have this problem on any architecture, but I haven’t verified.
