### ISSUE TITLE
ch-image fails with fedora and libutempr 

### ISSUE THREAD

**Issue by kb1vc** [hpc/charliecloud#1774]
Apparently  #1136 was closed too soon

I’ve used fedora:35 as an example, but this fails with fedora:39 as well

Here’s the Dockerfile
```
FROM fedora:35
RUN dnf install -y git
```
The host was 
```
$ cat /etc/redhat-release 
Fedora release 38 (Thirty Eight)
```
The charliecloud build was from the git repo — v0.35
```
$ ch-run —version
0.35
```

The image build fails when I try
```
ch-image build .
```
At the end of the output: 
```
Failed:
  git-core-2.38.1-1.fc35.x86_64          libutempter-1.2.1-5.fc35.x86_64    openssh-8.7p1-3.fc35.x86_64   
  openssh-clients-8.7p1-3.fc35.x86_64    util-linux-2.37.4-1.fc35.x86_64   

Error: Transaction failed
error: build failed: --force may fix it
error: build failed: RUN command exited with 1
```

I get a less broken result with 
```
ch-image build —force .
```

But it all still fails with 
```
Installed:
  fakeroot-1.30.1-1.fc35.x86_64      fakeroot-libs-1.30.1-1.fc35.x86_64    libfdisk-2.37.4-1.fc35.x86_64 
  systemd-libs-249.13-6.fc35.x86_64  util-linux-core-2.37.4-1.fc35.x86_64 
Failed:
  libutempter-1.2.1-5.fc35.x86_64                      util-linux-2.37.4-1.fc35.x86_64                     

Error: Transaction failed
error: command failed with code 1: /usr/bin/ch-run
```

**Comment by reidpr** [comment]
Thank you for the nice bug report!

`ch-image build --force` has been the default since 0.34. Also, the build is running `/usr/bin/ch-run` which is an unusual location for a `ch-run`  build from source.

I can’t reproduce with 0.35:

```
$ which ch-image
/home/reidpr/charliecloud2/bin/ch-image
$ ch-image --version
0.35
$ printf 'FROM fedora:35\nRUN dnf install -y git\n' | ch-image build -t foo -
[...]
--force=seccomp: modified 0 RUN instructions
grown in 2 instructions: foo
```

I wonder if there is a mixed installation here, and that’s the source of your problem?

**Comment by kb1vc** [comment]
I will try this from a raw fedora 38 build in a VM.  

matt

**Comment by kb1vc** [comment]
OK.  I tried it from an Ubuntu 22.04 VM installation and it worked fine (under VirtualBox on a Fedora 38 system)

I tried it on a Fedora 38 system from a raw installation in a VirtualBox
 installed gcc and gcc-g++ 
copied the tarball for v0.35, 
built it and installed it in /usr/local
added /usr/local/bin to my path

did this:
`$ printf 'From fedora:35\nRUN dnf install -y git\n' | ch-image build -t foo -`

got this

```
initializing storage directory: v7 /home/mhreill/chimages/mhreill
initializing empty build cache
  1. FROM fedora:35
Docker Hub rate limit: 92 pulls left of 100 per 6.0 hours (71.244.141.86)
manifest list: downloading: 100%
Docker Hub rate limit: 91 pulls left of 100 per 6.0 hours (71.244.141.86)
manifest: downloading: 100%
config: downloading: 100%
layer 1/1: eadd1e6: downloading: 53.2/53.2 MiB (100%)
flattening image
layer 1/1: eadd1e6: listing
validating tarball members
layer 1/1: eadd1e6: changed 31 absolute symbolic and/or hard links to relative
resolving whiteouts
layer 1/1: eadd1e6: extracting
image arch: amd64
copying image from cache ...
something went wrong, rolling back ...
deleting image: fedora:35
error: can’t set xattr: /home/mhreill/chimages/mhreill/img/fedora+35/etc/mtab: security.selinux: No such file or directory
```

So I tried the hints in [changing SELinux state](https://docs.fedoraproject.org/en-US/quick-docs/selinux-changing-states-and-modes/) that were suggested from[installing charliecloud ](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux_atomic_host/7/html-single/getting_started_with_containers/#user_namespaces_options)

rebooted

and got the same result. 

Have y’all tested this on Fedora?

**Comment by reidpr** [comment]
That’s an xattrs problem; the selinux mention is just coincidentally the attribute in question. Try again with `--noxattrs`?

**Comment by reidpr** [comment]
This build works for me on a Fedora 38 VM with 0.35 and `--no-xattrs`.

**Comment by reidpr** [comment]
Any update here? If not, I’m going to close with WORKSFORME.

**Comment by kb1vc** [comment]
Yes.  I got it to work. Thank you.
