### ISSUE TITLE
Spack example does not build with v0.21.0

### ISSUE THREAD

**Issue by reidpr** [hpc/charliecloud#1779]
```
$ ch-image build -f examples/spack/Dockerfile examples/spack
[...]
     175    ==> libffi: Executing phase: 'build'
     176    ==> [2023-11-27-20:21:58.857243] 'make' '-j12' 'V=1'
  >> 177    make: *** cannot open jobserver /tmp/GMfifo61477: No such file or directory.  Stop.
```

(many of the same error with different path)

The build *may* work when run manually in a `--private-tmp -w -u0 -g0` container.

**Comment by j-ogas** [comment]
@reidpr The issue appears to be the `--seccomp` argument passed to `ch_run_modify`.

Below we attempt to build a package we know breaks with Spack 0.21.0.

With seccomp.
```
$ ch-run --set-env --seccomp -w -u0 -g0 --no-passwd --cd / --unsafe /tmp/spack -- spack clean --all
>> 162    make: *** cannot open jobserver /tmp/GMfifo60288: No such file or directory.  Stop.
```

Sans.
```
 $ ch-run --set-env -w -u0 -g0 --no-passwd --cd / --unsafe /tmp/spack -- spack install libsigsegv
 [+] /spack/opt/spack/linux-almalinux8-haswell/gcc-8.5.0/libsigsegv-2.14-67avppsebconcatfoev4x3apmfhqlywa
```

**Comment by reidpr** [comment]
Here is the culprit:

Working (`ch-run` without `--seccomp`):

```
29599 mknod("/tmp/GMfifo29599", S_IFIFO|0600) = 0
29599 openat(AT_FDCWD, "/tmp/GMfifo29599", O_RDONLY|O_NONBLOCK) = 3
29599 openat(AT_FDCWD, "/tmp/GMfifo29599", O_WRONLY) = 4
```

Failing (`ch-run --seccomp`):

```
35759 mknod("/tmp/GMfifo35759", S_IFIFO|0600) = 0
35759 openat(AT_FDCWD, "/tmp/GMfifo35759", O_RDONLY|O_NONBLOCK) = -1 ENOENT (No such file or directory)
```

What’s happening is that the subprocess (`make(1)` I think) is trying to create a FIFO using `mknod(2)` (an unprivileged operation). We intercept this system call, returning fake success, and then the subprocess fails to open the FIFO that doesn’t exist because we lied about `mknod(2)` success.

We block `mknod(2)` and `mknodat(2)` because they are also used to create devices, which *is* a privileged operation. So to solve this, we need to either (1) stop faking these system calls and let attempts to create devices fail the build or (2) only fake attempts to actually create devices.
