### ISSUE TITLE
"FROM libfabric" error: unauthorized or not in registry: registry-1.docker.io:443/library/libfabric:latest

### ISSUE THREAD

**Issue by j34ni** [hpc/charliecloud#1823]
In the 0.36 documentation https://hpc.github.io/charliecloud/best_practices.html the second example `examples/Dockerfile.openmpi` in "11.3.2. Third-party software compiled from source" fails to build with this error message:

```  
1. FROM libfabric
something went wrong, rolling back ...
error: unauthorized or not in registry: registry-1.docker.io:443/library/libfabric:latest
hint: if your registry needs authentication, use --auth
``

**Comment by reidpr** [comment]
Thank you for the bug report! We added another image to the chain but did not update the docs.
