### ISSUE TITLE
completely unprivileged Charliecloud workflow

### ISSUE THREAD

**Issue by reidpr** [hpc/charliecloud#184]
Possibilities:

* img (#154)

**Comment by j-ogas** [comment]
I have been investigating this topic. Thus far, I have come across a variety of tools that each seem to tackle a piece of the puzzle but offer no comprehensive solution. 

- [Skopeo](https://github.com/projectatomic/skopeo) — gives us the ability to copy images from distribution based registries (dockerhub, etc.) and container storage backends (docker daemon). For example, I was able to use skopeo to pull Alan McPherson's CoMD file from Dockerhub from within an unprivileged container. However, I did run into problems when trying to use Skopeo behind a proxy.

- [umoci](https://github.com/openSUSE/umoci) — intends to be a complete manipulation tool for OCI images. It _should_ be usable with Skopeo; umoci should be able to unpack and repack images from json blob and manifest produced from Skopeo. However, I have yet to successfully test this (I receive ann error stating that CoMD image is not an OCI image).

- [img](https://github.com/genuinetools/img) — a stand alone, daemon-less unprivileged image builder

We should note that all of these tools will implement dependencies (like go). Alternatively, we could bundle tools like these within a Charliecloud container and save the resulting images produced from the tools via `ch-run` arguments (`-w`, etc.). Just a thought.

**Comment by reidpr** [comment]
More possibilities:

* [buildah](https://github.com/projectatomic/buildah)
* Docker inside `ch-run -u 0`.

**Comment by j-ogas** [comment]
Running `docker build` inside a debian:stretch container  with Docker installed via `ch-run -u 0` produced the following:

```
root@localhost:/# docker build -t spack .
error checking context: 'no permission to read from '/dev/autofs''.
root@localhost:/# systemctl status docker
Failed to connect to bus: No such file or directory
```

I also attempted to containerize buildah (utility container #191 ) but the _inception_ didn't take. The "dream within a dream" failed (runc within charliecloud):
```
ERRO[0000] error reading allowed ID mappings: error reading subuid mappings for user "jogas" 
and subgid mappings for group "jogas": No subuid ranges found for user "jogas"
```
I took a shot in the dark and put `jogas:1000:1020` into both `/etc/subuid` and `/etc/subgid`:
```
ERRO[0000] error opening "allow" to /proc/18521/setgroups: write /proc/18521/setgroups: 
operation not permitted 
ERRO[0000] (unable to determine exit status)
```

**Comment by reidpr** [comment]
I wonder if `docker build` would work under `fakeroot` inside and/or outside a container.

**Comment by mej** [comment]
Remember, `docker build` just sends stuff to the running Docker daemon.  So using `fakeroot` won't work; you have to be able to write to the Docker socket.

**Comment by reidpr** [comment]
Good point. So this would include running the Docker daemon under `fakeroot` as well.

**Comment by mej** [comment]
There is no reason to believe Docker will work under `fakeroot`; in fact, I can almost guarantee it won't.  There's nothing magic about `fakeroot`; it does system call interposition, but it can't trick the Docker daemon.  Docker does far too much stuff that actually requires root (e.g., seccomp filtering).

**Comment by reidpr** [comment]
That addresses the outside-container part. But what about `fakeroot` inside a Charliecloud container, perhaps with some features disabled? Will the user namespace cover enough privileged stuff to make it work?

**Comment by trandles-lanl** [comment]
It looks like there is a very recent (8/14) comment on the bugzilla entry.

Is modifying buildah to not require the updated package feasible or worth the effort?

**Comment by rstyd** [comment]
@trandles-lanl  
1) Yeah. That's somewhat promising since the person who made it is actually the creator of Buildah and a Redhat employee. Definitely will need to keep watching. 

2) That's a good question for @reidpr. He implied in this [post](https://github.com/hpc/charliecloud/issues/154#issuecomment-398910478) in regard to IMG that newgidmap and newuidmap are really just wrappers for writing some files in /etc/proc. However, [this](https://github.com/hpc/charliecloud/issues/154#issuecomment-401677881) comment states that they are required. 

If Reid is correct, I think changing this would be worth the effort.

**Comment by reidpr** [comment]
So we have `img` mostly working in Ubuntu, as @rstyd demonstrates in PR #349. I'll put some brief observations here so we can better compare things.

1. `img` is not a drop-in replacement for `docker`. Thus it would need a wrapper or patches anyway.
2. `img` appears to contain two different container runtimes: an internal one, and external `runc`.

Based on this, I wonder if it's time to pause investigation on `img` and look into `buildah` more. The latter:

* supports push, pull, and interpreting Dockerfiles;
* is packaged for CentOS and RHEL7 "Extras"; and
* has documented support for "alternate OCI-compatible runtime" (`buildah bud --runtime` or `BUILDAH_RUNTIME`).

Thus, I wonder if it is a better fit for the Charliecloud workflow. How hard is it to provide a sufficient OCI wrapper to make e.g. `BUILDAH_RUNTIME=chrun-oci` work?

**Comment by reidpr** [comment]
For the record, we've discussed that by "completely unprivileged", I'd like to avoid setuid helpers as well.

**Comment by wiene** [comment]
Another option for getting unpacked images as unprivileged user is [debootstrap](https://manpages.debian.org/stretch/debootstrap/debootstrap.8.en.html). It only works on Debian systems and its derivatives. If used as unprivileged user, this approach is subject to the limitations of the [fakechroot](https://manpages.debian.org/stretch/fakechroot/fakechroot.1.en.html) command. An advantage for Debian users is that it relies only on tools available in the Debian archive.

**Comment by reidpr** [comment]
With PR #455 and #483 merged, I believe we've achieved this important goal. Closing.
