### ISSUE TITLE
tutorial: missing `hello.py` in output

### ISSUE THREAD

**Issue by VladimirFokow** [hpc/charliecloud#1852]
## Section [2.6.3. Pull and compare](https://hpc.github.io/charliecloud/tutorial.html#pull-and-compare)

In the last command:

```bash
ls ./hello.2
```

shouldn't we also see `hello.py` in its output? - the whole point is to compare that it's the same image as the one we pushed in the previous section, which had this file

**Comment by reidpr** [comment]
Thanks for the bug report. I haven't reproduced but yes that makes sense. Is that what you're seeing?

**Comment by VladimirFokow** [comment]
@reidpr I've reproduced with v 0.37, here's exactly what I'm seeing:

```
bin  ch  dev  etc  hello.py  home  lib  lib64  media  mnt  opt  proc  root  run  sbin  srv  sys  tmp  usr  var
```
