### ISSUE TITLE
Run charliecloud on centos 7.3

### ISSUE THREAD

**Issue by zjiekai** [hpc/charliecloud#189]
I'm trying charliecloud on centos 7.3, but stuck at the `ch-run` with `can't init user+mount namespaces: Operation not permitted`.

```
$ cat /proc/cmdline 
BOOT_IMAGE=/boot/vmlinuz-3.10.0-514.21.1.el7.x86_64 root=UUID=1fe358bc-19d4-44b7-a9da-8db6e5284fd4 ro crashkernel=auto rhgb quiet user_namespace.enable=1
```

```
$ ls /proc/sys/user/max_user_namespaces
ls: cannot access /proc/sys/user/max_user_namespaces: No such file or directory
```

```
$ cat /boot/config-3.10.0-514.21.1.el7.x86_64 | grep USER_NS
CONFIG_USER_NS=y
```

```
$ bin/ch-run ../hello -- echo 'hi'
ch-run[17164]: can't init user+mount namespaces: Operation not permitted (ch-run.c:661 1)
```

**Comment by reidpr** [comment]
Hello @zjiekai, thanks for trying Charliecloud and sorry you are having trouble.

CentOS 7.3 does not have the necessary kernel to use Charliecloud. Your options are to upgrade to CentOS 7.4, which has user namespace support that can be enabled with some configuration, or to install a newer kernel, for example the 4.4 or 4.17 series RPMs from ELRepo.

For more information, please see: https://hpc.github.io/charliecloud/install.html

Does that help?

**Comment by reidpr** [comment]
@zjiekai, does that answer your question?

Thanks,
Reid
