### ISSUE TITLE
Utilizing BASH inside a container via ch-run

### ISSUE THREAD

**Issue by paulbry** [hpc/charliecloud#195]
I'm not able to find anything on this currently in the documentation or any of the issues; however, I could be missing something.

If I'm running a container it seems I'm unable to utilize bash redirects within the container instance? For example, if I run Blast via:
``` sh
ch-run -b $BLAST_OUT /var/tmp/blast -- /blast/blastall -p blast \
    -d nt/nt  -I /mnt/0/small.fasta.0 -o /mnt/0/input.fasta.0.out \
    2> /mnt/0/input.fasta.0.err
```
The problem comes in with the `2>`, it is trying to redirect the entire ch-run command as opposed to the `blast/blastall` that is running in the container. If I remove this or point it to a file on the host machine everything will run.

Alternatively, there is an easier example since the above is both hard to replicate and maybe necessary in practice.
```sh
ch-run -b /var/tmp/output /var/tmp/hello -- cat /hello/README > /mnt/0/example 
```
I would assume that the contents of `README` would be sent to the `example` file that was mounted via the `-b` switch. This is not the case, and everything after the `>` is occurring outside of the container. So if I run:
```sh
ch-run -b /var/tmp/output /var/tmp/hello -- cat /hello/README > /var/tmp/output/example 
```
It is work and the `example` file will have the contents of the `README` but it did simply redirected the output of `ch-run` to the file.

**Comment by j-ogas** [comment]
Try using `sh -c "$scriptfu"`.

```
ch-run -b /var/tmp/output /var/tmp/hello -- sh -c "cat /hello/README > /var/tmp/output/example" 
```

**Comment by paulbry** [comment]
That works with a coupe of quick runs I did this morning.
Thanks, turns out it was something simple.
