### ISSUE TITLE
new script ch-tar2dir to tar up an existing image directory

### ISSUE THREAD

**Issue by reidpr** [hpc/charliecloud#198]
This issue proposes a new script `ch-dir2tar` that tars up an existing image directory (created by whatever means) so that it works well with `ch-tar2dir`, e.g. by ensuring there's no top-level directory other than dot.

It was suggested in issue #150 and may also help with issue #154.

**Comment by reidpr** [comment]
So I should have been more clear: I'm skeptical we should do this. The alternative is that the other scripts work better with images packed up with plain `tar`, which seems simpler to me. The purpose of the issue was to come to a decision.

I'll need to be convinced it's a good idea before accepting any related PRs.

**Comment by j-ogas** [comment]
FWIW, I had encountered #150 while trying to create a tarball of an altered image after a`ch-fromhost` injection. Although the instructions provided in the FAQ  are effective, the solution is unintuitive and seemingly clunky. Seems problematic that both @trandles and I experienced this same error using `tar` in a natural manner. 

If that is not convincing enough, consider that the issue from #150 is one that is not easily detected; the tarball is created without warnings or error. It isn't until we unpack the tarball and try to execute `ch-run` that a problem becomes apparent. It is reasonable to imagine a situation where a user uses`tar` in a similar way and shares a bogus image. 

If nothing else, I think we should consider providing this mechanism as an optional argument to `ch-fromhost`. It would be nice to inject files into an image directory and automatically pack the altered image into a verified tarball.

**Comment by reidpr** [comment]
My current preference would be to implement #199, which would make this script unnecessary, because you could just use standard `tar` in the usual way.

The last paragraph above is a reasonable feature proposal, but put it in a new issue.

**Comment by rstyd** [comment]
I've run into this problem while trying to tar img unpack directories. Imo, we should include tar2dir until #199 is implemented. The solution is simple but incredibly unintuitive as a longtime tar user.

**Comment by reidpr** [comment]
Closing as `WONTFIX`, since PR #198 makes it easy to just use plain `tar` in the traditional way.
