### ISSUE TITLE
Make Docker environment variables available

### ISSUE THREAD

**Issue by JiaweiZhuang** [hpc/charliecloud#224]
In the ["Environment variables" section](https://hpc.github.io/charliecloud/command-usage.html#environment-variables) of the docs I notice that:

> ch-run generally tries to leave environment variables unchanged, but in some cases, guests can be significantly broken unless environment variables are tweaked.

What's the purpose of using environment variables on the host? Both Docker and Singularity only use environment variables defined in the container (Docker's `ENV` statement, Singularity's `%environment` section), which makes great sense because compiling&running HPC models often rely on correctly-configured environment variables ($FC, $OMPI_FC, $NETCDF_HOME are extremely common in Earth science models). 

Here's the specific trouble I have:

I am experimenting with [CharlieCloud on NASA Pleiades cluster](https://www.nas.nasa.gov/hecc/support/kb/172/). My `.bashrc` on the host has already loaded tons of modules, and the environment variables are pretty messed-up (a common problem for HPC users...). I was hoping that Charliecloud can create an isolated environment, but it actually copies the host's environment variables into the container. The host sets `FC=ifort` but the container needs `FC=gfortran`, the host sets `$NETCDF_HOME` to the cluster's shared lib but the container needs `NETCDF_HOME=/usr`... My model code does not compile because of misconfigured environment. Such issue does not exist with Docker/Singularity as they do not overwrite environment variables in the container. 

Calling`unset FC` before starting the container does not help -- `FC` will be empty, which is the same as on the host, not `gfortran` as defined by the container. So, I have to manually set up the environment variables, such as preparing a special `.bashrc` for each container. This makes container much less convenient and more error-prone.

My question is, is there a way to use environment variables defined by the container (block the variables on the host), like the default behavior in Docker/Singularity? I cannot find such an option in `ch-run`.

FYI, here's the Dockerfile for the container I use: https://github.com/geoschem/Docker_GC

Thanks!

**Comment by reidpr** [comment]
Thanks for the thoughtful question.

> What's the purpose of using environment variables on the host?

The reasoning is that Charliecloud provides a container environment that's as lightweight as possible. Our goal is to provide just enough isolation to run user codes in a user-provided environment, but no more.

> Charliecloud ... copies the host's environment variables into the container.

Not quite. The new `ch-run` process simply replaces itself with the user command provided, so like any new process, the user command inherits the environment variables of its parent. Charliecloud does not manipulate these variables, i.e., it doesn't "copy" or "overwrite" any variables, with a couple exceptions as you've discovered in the `ch-run` man page;

> Docker/Singularity ... do not overwrite environment variables in the container.

Just like Charliecloud, Docker and Singularity are providing their best guess on what environment variables you need. Their philosophy is to start from nothing, guess what variables you want, and then you can add more using `ENV` statements or similar. This is in fact the active approach: they delete all the host environment variables and replace them with the default set (and figuring out a generally appropriate default environment is quite difficult).

The Charliecloud approach is to pass in the existing environment and let users choose what to exclude.

Neither approach will "just work" for all users.

> I have to manually set up the environment variables, such as preparing a special `.bashrc` for each container.

Manually setting up the variables is the current recommended approach, but you don't need a customized `.bashrc` to do it. I think something like a file in `/etc/profile.d` in the image would work, or you could manually source something in your job script or interactive shell, either inside or outside the container.

You could also consider a `module purge` to get a clean environment on the host, though this won't help with the variables you need to set. 

This is related to issue #34 for `CMD` and `ENTRYPOINT`.

> [I]s there a way to use environment variables defined by the container (block the variables on the host), like the default behavior in Docker/Singularity?

Currently no. It's a reasonable feature request, though, and it seems you have a good use case. I'll tag this issue correspondingly.

> [H]ere's the Dockerfile for the container I use....

Thanks, it's really helpful to see what real task people are trying to accomplish. This seems like a nice, tidy Dockerfile.

The one suggestion I'd have is: Everything you're doing seems to be going in a standard location. Best practices would be to have reasonable defaults for the location of things, and use those in the absence of environment variables (e.g., setting environment variables should not be a required step). However, I understand that not everyone has the time or ability to fix this, and we want Charliecloud to work as well as possible even if best practices aren't followed.

**Comment by JiaweiZhuang** [comment]
Thanks very much for the explanation. I do see that Docker/Singularity's approach is more "active" and that CharlieCloud tries to be very light.

> Best practices would be to have reasonable defaults for the location of things, and use those in the absence of environment variables (e.g., setting environment variables should not be a required step).

This would depend on the goal that a user want to achieve. For installing custom libraries on a shared HPC cluster, CharlieCloud's light weight approach probably makes more sense. However, we (Earth scientists) often use containers to encapsulate a terribly huge, complicated, legacy program that requires very specific versions of libraries and accurately configured environment variables. One single mis-configured item will crash the software compilation, and debugging is often quite hard. In this case, we want the container to behave as close to a virtual machine as possible, so there is no chance for a user to get arcane bugs... Just FYI, here's a much less tidy [Singularity recipe](https://github.com/geoschem/Singularity_GCHP/blob/master/Singularity#L123) that heavily relies on customized environment variables to just make the code compile. There is no way for us to decouple the environment variables from libraries because of our 20+ year old code base😐

Thanks for considering this suggestion. For now I will source variables manually.

**Comment by reidpr** [comment]
Sorry, I should have been more be clear. While I believe it would be nice if science codes could change in the way I described, I realize that many can't, and Charliecloud is committed to supporting them anyway.

**Comment by reidpr** [comment]
So one gotcha is that `env -i bash --noprofile --norc` yields a `$PATH` containing dot; that's a security risk. :P

**Comment by reidpr** [comment]
So here's one proposal for how it should work. This is based on an earlier offline proposal from @j-ogas.

We introduce two scripts, placed into the tarball by `ch-docker2tar`:

* `/docker-env-add` adds the environment variables specified in the Dockerfile, leaving the existing environment unchanged, then executes its arguments (`"$@"`).
* `/docker-env-only` clears the environment, makes any tweaks needed (e.g., securing `$PATH` and I recall something about `$HOME` elsewhere in Charliecloud), then adds the Dockerfile environment variables, then executes its arguments.

For example:

```
$ ch-run /var/tmp/debian9 -- /docker-env-add env | egrep '^(DEBIAN_FRONTEND|EDITOR)'
DEBIAN_FRONTEND=noninteractive
EDITOR=emacs -nw
$ ch-run /var/tmp/debian9 -- /docker-env-only env | egrep '^(DEBIAN_FRONTEND|EDITOR)'
DEBIAN_FRONTEND=noninteractive
```

An additional two cases would be to make the scripts source-able, to alter an already existing shell. I'm not sure what the use case is here, so I'm not convinced it's worth the effort. This would look like:

```
$ ch-run /var/tmp/foo -- bash
> . /docker-env-add
```

```
$ ch-run /var/tmp/foo -- bash
> . /docker-env-only
```

**Comment by JiaweiZhuang** [comment]
Something like `ch-run --docker-env` does seem like a cleaner solution!

**Comment by reidpr** [comment]
PR #319 is only a partial fix; re-opening.

**Comment by j-ogas** [comment]
Addressed with #319 and #345; closing.

Example:
```
$ docker inspect "$tag" --format='{{range .Config.Env}}{{println .}}{{end}}' > /home/jogas/docker-env
$ ch-run --unset-env='*' --set-env=/home/jogas/docker-env "$img" -- env
```

**Comment by reidpr** [comment]
Don't we want to make the variables available automatically though? Can we run that command in e.g. `ch-docker2tar`?

**Comment by JiaweiZhuang** [comment]
Glad to see this being moved forward! 

Question: `docker inspect` can't run on shared clusters, so one needs to ship the `docker-env` file together with the image?

**Comment by j-ogas** [comment]
@JiaweiZhuang Right now one would need to ship the `docker-env` file in addition to the image tarball. This is not ideal (re-opening).  

The `docker-env` file generated by `docker-inspect` should be packed inside the image tarball at `ch-docker2tar` time.
