### ISSUE TITLE
Why do the examples need a context?

### ISSUE THREAD

**Issue by reidpr** [hpc/charliecloud#225]
@JiaweiZhuang asked the following in closed issue #120. Copying to new issue.

> [I am] confused by this.
>
>> The context directory for the examples in the source code needs to be Charliecloud source code directory, not the installation `$PREFIX`.
>
> Is the "context directory" same as Docker context? From Docker docs:
>
>> The `docker build` command builds Docker images from a Dockerfile and a “context”. A build’s context is the set of files located in the specified `PATH` or `URL`. The build process can refer to any of the files in the context. For example, your build can use a `COPY` instruction to reference a file in the context.
>
> So, Docker's context directory basically contains files that you want copy into the image. But why the context dir for Charliecloud is Charliecloud source code? What directory should I use if I install the pre-built binary using package manager (e.g. https://packages.ubuntu.com/bionic/charliecloud)?

**Comment by reidpr** [comment]
> Is the "context directory" same as Docker context?

Yes, because we use Docker to build most of the examples. (E.g., `ch-build` is a wrapper for `docker build`.)

> Docker's context directory basically contains files that you want copy into the image.

Almost — it contains a superset of the files you want to copy into the image. We use the root of the source code in order to keep the examples consistent, but it means that all the examples get way more context than they really need.

> But why the context dir for Charliecloud is Charliecloud source code?

There may not be a good reason why it's the source code and doesn't work for the installed tree. The convention predates the ability to install Charliecloud (rather than run out of the source code working directory).

> What directory should I use if I install the pre-built binary using package manager (e.g. https://packages.ubuntu.com/bionic/charliecloud)?

Unfortunately, you're out of luck. You need the source code (but it's easy to get).

(As an aside, that package is version 0.2.3, which is quite dated by now.)

**Comment by reidpr** [comment]
Thanks! We'll consider that suggestion.

**Comment by reidpr** [comment]
@JiaweiZhuang: See the linked issue. We are going to change all the Dockerfiles to use `.`. Thanks for the suggestion.

**Comment by JiaweiZhuang** [comment]
Glad to see that!
