### ISSUE TITLE
Investigate 'ch-run --join' clean failures on subsequent test suite runs.

### ISSUE THREAD

**Issue by j-ogas** [hpc/charliecloud#231]
The `ipc_clean_p` function from the `ch-rub --join` test fails during subsequent full scope test suite runs; `/dev/shm` appears to have leftover charliecloud crud.

```bash
 ✗ ch-run --join: one peer, direct launch
   (from function `ipc_clean_p' in file run/ch-run_join.bats, line 8,
    in test file run/ch-run_join.bats, line 83)
     `ipc_clean_p' failed
 ✗ ch-run --join: two peers, direct launch
   (from function `ipc_clean_p' in file run/ch-run_join.bats, line 8,
    in test file run/ch-run_join.bats, line 120)
     `ipc_clean_p' failed
 ✗ ch-run --join: three peers, direct launch
   (from function `ipc_clean_p' in file run/ch-run_join.bats, line 8,
    in test file run/ch-run_join.bats, line 159)
     `ipc_clean_p' failed
 ✗ ch-run --join: multiple peers, framework launch
   (from function `ipc_clean_p' in file run/ch-run_join.bats, line 8,
    in test file run/ch-run_join.bats, line 212)
     `ipc_clean_p' failed
...
jogas@ba224:testing $ find /dev/shm -maxdepth 1 -name '*ch-run*'
/dev/shm/ch-run_52
/dev/shm/sem.ch-run_52
/dev/shm/ch-run_51
/dev/shm/sem.ch-run_51
/dev/shm/ch-run_50
/dev/shm/sem.ch-run_50
/dev/shm/ch-run_49
/dev/shm/sem.ch-run_49
/dev/shm/ch-run_48
/dev/shm/sem.ch-run_48
/dev/shm/ch-run_47
/dev/shm/sem.ch-run_47
/dev/shm/ch-run_46
/dev/shm/sem.ch-run_46
/dev/shm/ch-run_45
/dev/shm/sem.ch-run_45
/dev/shm/ch-run_44
/dev/shm/sem.ch-run_44
/dev/shm/ch-run_43
/dev/shm/sem.ch-run_43
```

**Comment by reidpr** [comment]
Does the leftover crud happen if the tests are successful too?

**Comment by j-ogas** [comment]
Yes. The first test run is always successful. Subsequent tests after that fail because the first test leaves crud.

**Comment by reidpr** [comment]
OK. I believe I tried that on my workstation and couldn't reproduce it.

I wonder if it's a Slurm thing? I see there's an internal bug too, so I'll go over there to ask about specific clusters.

**Comment by j-ogas** [comment]
Update: I have not been able to reproduce this error on the system since I have started investigating. That said, I am happy to implement the proposed changes to `ch-run_join.bats` we discussed anyway.

**Comment by reidpr** [comment]
Yes, let's do that. Then we'll be better equipped to diagnose when it re-appears.

**Comment by j-ogas** [comment]
The issue hasn't occurred in some time now. Closing.
