### ISSUE TITLE
Unavailable PSM2 version resulting in Openmpi test image build failing

### ISSUE THREAD

**Issue by heasterday** [hpc/charliecloud#239]
The current libpsm2 version used in Dockerfile.openmpi (10.3.58-1) is no longer available from http://http.us.debian.org/debian/pool/main/libp/libpsm2/ this results in all the OpenMPI docker image builds breaking. Recommend, if possible, incrementing from version 10.3.58-1 to 10.3.58-2 within Dockerfile.openmpi on line 142 which on my system resulted in successful image builds.

**Comment by reidpr** [comment]
Good find! Can you please submit a PR?
