### ISSUE TITLE
Documentation update for DNS resolution failure in docker containers at LANL

### ISSUE THREAD

**Issue by nicholas-sly** [hpc/charliecloud#265]
When trying to run docker from a fresh installation on Ubuntu 16.04 on the yellow network at LANL, `ping 8.8.8.8` worked, but `ping www.google.com` and `ping int.lanl.gov` didn't, while those commands did work on my host workstation.

The issue seems to have been that docker copies in some of the network configuration files from the host machine, but my computer didn't explicitly have the DNS servers being used listed in /etc/resolv.conf.

[This](https://development.robinwinslow.uk/2016/06/23/fix-docker-networking-dns/) page was the final thing that actually helped in fixing this issue in a concise manner.  It shows how to get the DNS servers being used on a given network interface and where to put this information for temporary and more permanent way.

The gist is that the DNS server used by the host workstation can be found using the command `nmcli dev show | grep 'IP4.DNS'`.  For a specific instance of running a docker container, the `docker run` call can be modified to include the option `--dns [xx.xx.xx.xx]`.  To fix this issue for every docker container on the system, modify the file /etc/docker/daemon.json to be:
```json
{
    "dns": ["xx.xx.xx.xx", "yy.yy.yy.yy"]
}
```
Once that file is in place, run `sudo systemctl restart docker.service` and the next `docker run` command should include these new DNS nameservers.

Testing this fix can be done simply by starting a container with `docker run -i ...` and trying to ping both `8.8.8.8` and `www.google.com`.  If both work, the DNS resolution is working.

If this could be added to the documentation near where the 'using docker behind a proxy' information is, I think it would be very helpful for users on the LANL network and on other similarly architected networks.

**Comment by reidpr** [comment]
Hello Nicholas, thanks for the bug report.

This sounds like a Docker configuration issue, though. Can you explain how this affects Charliecloud?

**Comment by reidpr** [comment]
I can't reproduce this. I'll create an internal issue so we can discuss configuration and stuff unredacted, and we'll come back here once we generalize.
