### ISSUE TITLE
'ch-fromhost --nivida with GPU' test failure

### ISSUE THREAD

**Issue by j-ogas** [hpc/charliecloud#267]
```bash
 ✗ ch-fromhost --nvidia with GPU
   (in test file run/ch-fromhost.bats, line 337)
     `[[ $status -eq 127 ]]' failed
```

The test above expects `ch-run $imgdir/nvidia -- /matrixMulCUBLAS` to fail. I suspect this is because the function `fromhost_clean`, which is called prior to `ch-run`, initially removed files injected with `ch-fromhost` that matrixMulCUBLAS once depended on. At a quick glance, I am uncertain whether the new two-stage nvidia dockerfile build made this portion of the test obsolete, or the `fromhost_clean` function needs revising (aside from the removal of the obsolete line  7: `/usr/local/cuda-9.1/targets/x86_64-linux/lib/libsotest.so.1{.0,}`).

**Comment by j-ogas** [comment]
The `fromhost_clean` function does not remove the nvidia shared objects injected with `ch-fromhost --nvidia`. We can account for these objects by adding `/usr/local/lib/libcuda.so*` and `/usr/local/lib/libnvidia-*` to this list of targets in fromhost_clean. If this is a reasonable approach I'll go ahead and submit a PR.

**Comment by reidpr** [comment]
That sounds good to me.
