### ISSUE TITLE
improve testing for helper tarball/directory creation commands

### ISSUE THREAD

**Issue by reidpr** [hpc/charliecloud#271]
Currently, as pointed out in PR #264, the testing for `ch-build2dir`, `ch-pull2tar`, and `ch-pull2dir` is not so good:

- the artifacts created (tarball or directory) are not tested to be working images
- they make clutter in `$CH_TEST_IMGDIR`

This issue is to figure out what improvements are needed and implement them.

**Comment by j-ogas** [comment]
Potential solutions:

1. In-place testing, i.e., the artifacts produced by the helper scripts are tested as they are created. This would be the simplest to implement and least invasive on existing code. A drawback is that this method deviates from separating buildtime from runtime tests.

2. We  could add a `run` flag to `make-auto` and place sentinel files in the test directory. E.g., `Run.ch-pull2dir`, `Run.ch-build2dir`, and `Build.ch-pull2tar`. This would be in line with the separation of buildtime and runtime testing, and it would also make use of our existing script. The drawback here is that the use of sentinel files is pretty messy and kludgy.
