### ISSUE TITLE
bin/base.sh: non-executable but contains shebang line

### ISSUE THREAD

**Issue by wiene** [hpc/charliecloud#282]
While preparing Charliecloud 0.9.4 for inclusion in Debian, lintian made me aware of the following inconsistency:

For the file `bin/base.sh` a shebang line was introduced by [this commit](https://github.com/hpc/charliecloud/commit/6abf1d0e660be3f320d0e154cada997047d48275), although the file remains non-executable. This gives rise to [this lintian warning](https://lintian.debian.org/tags/script-not-executable.html).

While this does _not_ do any harm I agree with lintian that this combination is not very useful.

**Comment by reidpr** [comment]
Good catch; thank you.

Unrelated, we are aiming for monthly releases now, if that is relevant to your plans.
