### ISSUE TITLE
IPC is not cleaned if a join tests fails

### ISSUE THREAD

**Issue by rstyd** [hpc/charliecloud#284]
If a test in ch-run_join.bats fails, files are left in /dev/shm. This will cause the test to fail again during the next run even if the original problem has been fixed.

**Comment by reidpr** [comment]
OK. What should we do? Stop the test and make the user clean up if we detect leftovers? Just delete them automatically? ... ?

Opinions?

**Comment by rstyd** [comment]
I suggest we delete them automatically otherwise the other tests in the batch will fail. User intervention doesn't seem necessary.

**Comment by reidpr** [comment]
So let me make a quick PR on this. What I'm inclined to do is add a tests at the beginning and/or end of `test/run/ch-run_join.bats` that checks if any IPC files remain in `/dev/shm`. If so, it deletes them *and also* fails, to highlight the problem.

**Comment by rstyd** [comment]
That sounds perfect to me.
