### ISSUE TITLE
test MPI performance

### ISSUE THREAD

**Issue by reidpr** [hpc/charliecloud#289]
Currently, the MPI tests validate functionality but not performance. I would like to add some simple performance testing to validate correctness issues exposed by bad performance; e.g., is the high-speed interconnect being used?

This would not be a benchmark.

**Comment by heasterday** [comment]
Within a small C program it should be possible to query the Open Portable Access Layer (OPAL) after the initialization of MPI and walk the list of initialized components to check whether or not the modules we desire to use are initialized (e.g. the psm2 mtl). This could be added to the test suite as a case where we provide the desired modules to check. This would not check for the resulting performance just that the modules that we deem important are available to the runtime. What are your thoughts on this approach?

**Comment by reidpr** [comment]
Is it possible for a component to report correct initialization but still perform badly?

We could also accomplish the by setting one of the debug environment variables and checking which components are reported being used. Or, modify `hello.c`, though that needs to be portable to different MPIs.

**Comment by heasterday** [comment]
I believe so.

If the goal is to do basic checking on if the component desired are initialized successfully and they are performing at a level considered adequate perhaps setting some debug environment variables like you mentioned or using something like mpirun -mca mpi_show_mca_params <option> in combination with checking the output from the Intel IMB benchmarks which are already included in the tests would meet this need.
