### ISSUE TITLE
nvidia-container-cli check in common.bash

### ISSUE THREAD

**Issue by j-ogas** [hpc/charliecloud#292]
We have the following in test/run/ch-fromhost.bats:

```
command -v nvidia-container-cli >/dev/null 2>&1 || skip 'nvidia-container-cli not in PATH'
```

I think this should be a function inside common.bash (`nvidia-cli_ok`?). It could be called in the setup portion of future GPU examples which depend on the nvidia library and binary injections provided by ch-fromhost.

**Comment by reidpr** [comment]
I think that reasonable. The `ch-fromhost` examples might have some edge cases that shouldn't use it (e.g., barfing properly if `nvidia-container-cli` is present but there are no GPUs). You will need to emit clear error messages.

The right prototype might be `need_docker`: do nothing if all needed conditions are met, skip with a good message if not.

**Comment by j-ogas** [comment]
After further consideration I am unconvinced this should be implemented at this time. Marking as deferred for the time being; will revisit and possibly close later.

**Comment by j-ogas** [comment]
Closing.
