### ISSUE TITLE
add an option to ch-run to suppress forwarding of SLURM env variables to processes in the container

### ISSUE THREAD

**Issue by hppritcha** [hpc/charliecloud#295]
Hunter and I are going around in circles on some edge cases with Open MPI and doing 
- singleton launch within a container (that means running a MPI executable without using mpirun, etc.)
- mpirun launch within a container which was in turn started within a SLURM allocation

These problems would vanish if there were a ```ch-run```  command line option to suppress forwarding of SLURM environment variables to the processes (including mpirun) within the container.

**Comment by hppritcha** [comment]
assigning to Jordan

**Comment by j-ogas** [comment]
Related to #224. The proposed solution to 224 would provide a script, `docker-env-only`, in the container root that would clean the container environment variables and add those declared in the Dockerfile via the `ENV` directive. SLURM variables would be unset in that case.

@hppritcha Would that suffice? Or is there a use case in which you may want _only_ the SLURM environment variables unset?

**Comment by reidpr** [comment]
Maybe #224 should be "add Docker environment variables to existing environment" and this issue should be "remove variables from environment".

**Comment by heasterday** [comment]
Something to bear in mind for the future, we likely will also want to drop ALPS env variables on the Crays to prevent the same behavior that breaks guest launches when Slurm is detected. In a Cray environment first Slurm env variables are detected generating in guest launches the error "The application appears to have been direct launched using "srun" but upon dropping them then a guest launch results in the following error "The application appears to have been direct launched using "aprun". It is only after dropping both sets is the launch successful.
