### ISSUE TITLE
Does lack of tty group in /etc/groups fix sshd?

### ISSUE THREAD

**Issue by reidpr** [hpc/charliecloud#298]
@olifre asks in #67:

> For `sshd`, as discussed in https://bugzilla.mindrot.org/show_bug.cgi?id=2813 right now, it seems that removing `tty` from `/etc/group` in the container helps to prevent the `chown`. Do you think it's also worthwhile to document that?

Since we changed to a custom `/etc/group`, `tty` will no longer be present unless we map that group explicitly. Does that help with `sshd`?

**Comment by reidpr** [comment]
Hello @olifre; did you have any insight on this question?

**Comment by olifre** [comment]
Hi @reidpr, 
sorry for missing this issue until now! I will give this construction (sshd in the container) another test, hopefully during the upcoming weekend and report back.

**Comment by olifre** [comment]
Hi @reidpr,
yes, I can confirm that fixes it! Very nice side-effect! :+1: 
For production `sshd` use in containers (if someone really want's that), of course it's not too practical that the default user's shell is fixed to `/bin/sh`, but it's the only generic thing that can be assumed for all containers. So it might be helpful to have that configurable, but on the other hand, I doubt that running `sshd` in unprivileged containers is a common usecase.

**Comment by reidpr** [comment]
Great! I'll close this ticket then since the question is answered. I don't believe we need to do anything then; please correct me if I'm wrong.
