### ISSUE TITLE
run user's default shell if no command specified?

### ISSUE THREAD

**Issue by reidpr** [hpc/charliecloud#3]
Generally we want `ch-run` to work like a shell, but is there enough of a use case here to merit the extra code? Are there downsides e.g. if run in non-interactive mode, what happens?

**Comment by jlowellwofford** [comment]
This can be done very easily with getpwuid.  I don't see any downside to it.  Would you like me to put a patch together?

**Comment by trandles-lanl** [comment]
Seems fragile as you have no assurance that the user's default shell is present in the container.  I vote that you either return an error if no command is given to ch-run or you always return success, as if the default command is /bin/true.

**Comment by jlowellwofford** [comment]
The only counter to that I would give is that the default behavior of `chroot` is to run `${SHELL} -i` if nothing is given, and this is a chroot-like utility.  It occurs to me that getting the env $SHELL and mimicking `chroot` might make more sense than using the value from getpwuid.  It could just fail *if* the default shell isn't in the container (with some descriptive error).

**Comment by reidpr** [comment]
The former (error) is the current behavior:

```
$ ch-run /img/chtest --
ch-run: NEWROOT and/or CMD not specified
$ ch-run -- true
ch-run: NEWROOT and/or CMD not specified
```

**Comment by reidpr** [comment]
This is what you get if the user command isn't in the shell:

```
$ ch-run /img/chtest -- foo
ch-run: can't execve(2) user command: No such file or directory
```

**Comment by trandles-lanl** [comment]
I just prefer something deterministic for default behavior because it's simpler for the user and for folks helping to debug.  If the default behavior changes depending on the container's composition that can be difficult to suss out.

**Comment by reidpr** [comment]
My weak vote would be to do nothing for now, and if we start getting user feedback that this feature is important, revisit it.

**Comment by trandles-lanl** [comment]
Perhaps:
1) if no command given, attempt to run user's default shell
2) if the shell isn't there, give an error message like "No CMD specified and default shell not available"

**Comment by reidpr** [comment]
This has been sitting for a long time; I don't think we will ever do it. Closing. Please re-open if you can argue that's a mistake.
