### ISSUE TITLE
misleading error message if $CH_TEST variables are undefined

### ISSUE THREAD

**Issue by rstyd** [hpc/charliecloud#303]
I tried running the test suite on Ubuntu with `make test` and received this error:

`/usr/lib/bats/bats-exec-suite: line 20: let: count+=: syntax error: operand expected (error token is "+=")`

There's a lengthy discussion here: https://github.com/sstephenson/bats/issues/140. I'm trying to find a workaround.

**Comment by rstyd** [comment]
This issue is actually caused by failing to define the charliecloud testing environment variables
 
>export CH_TEST_TARDIR=/var/tmp/
export CH_TEST_IMGDIR=/var/tmp/images
export CH_TEST_PERMDIRS='/var/tmp /tmp`

Kudos to @heasterday for the tip.

**Comment by reidpr** [comment]
So this is not actually erroneous: We used to print a coherent error message if those variables were missing, but now we don't. Re-opening and re-tagging.
