### ISSUE TITLE
Tests hang in Vagrant VM if host has 2 cores

### ISSUE THREAD

**Issue by atorrez** [hpc/charliecloud#304]
While going through Section 5 (Pre-installed Virtual Machine) of the Tutorial.  I ran into an issue using my 2 core MacBook Air laptop.   A hang was encountered during the Spark test (provision with test) and a Ctrl C stated a thread error.  In Consultation with Reid and Jordan I tried changing Virtual Box CPU count (was set at 4) to match my hardware and also tried manually setting CPU count to 2 in the Vagrantfile.  Both of these methods did not fix the problem.

**Comment by rstyd** [comment]
One thing that would be interesting is to turn off hyperthreading and see if the problem still persists. You have to install XCode then use their Instruments application. 
https://macperformanceguide.com/Mac-HowToDisableCPUCores.html

**Comment by reidpr** [comment]
Closing per removal of Vagrant support in #1204.
