### ISSUE TITLE
vagrant: misleading error message in --provision-with=test

### ISSUE THREAD

**Issue by rstyd** [hpc/charliecloud#309]
Running charliecloud test with vagrant reports a non-helpful error if you're provisioning with the test suite. This can be fixed by modifying the vagrant file to write the error output of the charlie user test to /dev/null.

**Comment by reidpr** [comment]
To be specific, the test for user `charlie` reports an error if the user is not present:

```
id: charlie: no such user
```

but this is simply part of a conditional, not a real error.
