### ISSUE TITLE
ch-run fails if default bind path does not exist in image

### ISSUE THREAD

**Issue by samcmill** [hpc/charliecloud#320]
If one of the required bind paths does not exist in the container image, then `ch-run` fails.

Perhaps `ch-fromhost` can be enhanced to automatically create the required bind paths inside the image if they do not already exist?

```
$ skopeo --insecure-policy copy docker://centos:7 oci:centos:7
$ umoci unpack --rootless --image centos:7 ex1
$ ch-run ex1/rootfs -- cat /etc/os-release
ch-run[68]: can't bind: not found: /home/labuser/ex1/rootfs/etc/resolv.conf (charliecloud.c:122)
$ touch ex1/rootfs/etc/resolv.conf
$ ch-run ex1/rootfs -- cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
$ ch-run --version
0.9.6
```

**Comment by reidpr** [comment]
Hello Scott, thanks for the bug report. You are correct, this is a missing feature. We have a feature request already in issue #96, so I'm going to close this one as a duplicate, but it looks like it might have been hard to search for. Again, very much appreciate your reminding us of this issue's relevance, and please participate in the other issue's comments if you have more to add that's not in one of these two issues.

**Comment by reidpr** [comment]
Sorry, I misinterpreted. I don't think this is a duplicate. #96 addresses the general case while this is talking about the default bind mounts, correct?
