### ISSUE TITLE
test suite: missing error message if Charliecloud not built

### ISSUE THREAD

**Issue by rstyd** [hpc/charliecloud#329]
Running the test suite without charliecloud being built results in this error message. 

```
/usr/local/libexec/bats-exec-suite: line 21: let: count+=: syntax error: operand expected (error token is "+=")
make: *** [test-build] Error 1
```

This is confusing and should be replaced by something explaining how the Charliecloud executables cannot be found.

**Comment by reidpr** [comment]
This is what I get:

```
$ cd ~/charliecloud
$ make clean
[...]
$ cd test
$ make test
./make-auto build chtest/Build Build.missing Dockerfile.alpine36 Dockerfile.alpineedge Dockerfile.centos6 Dockerfile.centos7 Dockerfile.debian9 Dockerfile.mpich Dockerfile.nvidia Dockerfile.openmpi Dockerfile.python3 Dockerfile.ubuntu1604 Docker_Pull.alpine36_dp ../examples/mpi/lammps/Dockerfile ../examples/mpi/paraview/Dockerfile ../examples/other/spark/Dockerfile ../examples/serial/hello/Dockerfile ../examples/serial/obspy/Dockerfile ../examples/serial/spack/Dockerfile ../examples/mpi/mpibench/Dockerfile.mpich ../examples/mpi/mpibench/Dockerfile.openmpi ../examples/mpi/mpihello/Dockerfile.mpich ../examples/mpi/mpihello/Dockerfile.openmpi > build_auto.bats
bats build.bats build_auto.bats build_post.bats
Must build with "make" before running tests.

/home/reidpr/charliecloud/test/bats/libexec/bats-exec-suite: line 20: let: count+=: syntax error: operand expected (error token is "+=")
Makefile:30: recipe for target 'test-build' failed
make: *** [test-build] Error 1
```

Are you not getting the "Must build" line?

The confusing error from `bats-exec-suite` comes from BATS. I don't know if or how it can be fixed. That's why we have a blank line after our error, to try to make it a little more obvious.

**Comment by reidpr** [comment]
OK. Thanks for the report. Let's leave it alone for now, unless someone else encounters it, because you know how to work around it and so far you're the only one who's seen it.

**Comment by j-ogas** [comment]
FWIIW, in my experience, that cryptic error is almost always due to malformed `CH_TEST_*` variables, e.g., `CH_TEST_TARDIR=./var/tmp/tar`, or the path has nested directories that do not exist #347.

**Comment by reidpr** [comment]
@epanas ran into this again in issue #505. It's a Debian VM that I set up. I can wait to tear down that environment if it helps in debugging.

**Comment by reidpr** [comment]
I think this is moot now that #447 is merged.
