### ISSUE TITLE
Is it possible to convert a charliecloud tar ball back to docker image tar.gz?

### ISSUE THREAD

**Issue by suredream** [hpc/charliecloud#350]
My colleague left a charlieCloud tgz.  Is there any way I can import it back to docker image?

Many thanks,

**Comment by reidpr** [comment]
Hello @suredream,

I have not tried it personally, but I think [`docker import`](https://docs.docker.com/engine/reference/commandline/import/) should do what you want. You will end up with a flat image, without the Docker layers originally used to build it (if it was built with Docker).

Can you try it and report back whether it worked?

Thanks,
Reid

**Comment by mej** [comment]
`zcat charlieCloud.tgz | docker import - charlieCloud`

That will make a Docker repository tagged as `charlieCloud` available in your local Docker instance which you can run against, push to a registry server (if you retag it, obviously), etc.  Keep in mind, as @reidpr said, it will only contain a single layer.  If that matters, you'll want to rebuild from the original Dockerfile if you still have it.

**Comment by reidpr** [comment]
Closing; please re-open if this doesn't answer your question.
