### ISSUE TITLE
Fedora/EL7 packaging available

### ISSUE THREAD

**Issue by loveshack** [hpc/charliecloud#362]
You might like to mention somewhere that there are rpms for EL7 and Fedora available under https://copr.fedorainfracloud.org/coprs/loveshack/charliecloud/
The packaging could probably be adapted for openSUSE, but I haven't tried to fix it myself.  I don't know if it can be made partially useful for EL6 without the old suid wrapper; there's a namespace missing.
[I should probably try to get it into Fedora, having been burned by singularity, but I'm not sure I can muster the energy in the face of increasing pain of Fedora maintenance.]

**Comment by reidpr** [comment]
Thanks @loveshack. We've got a PR in progress (#338) to get Charliecloud into Fedora and EPEL, but we'll look over your RPMs as well. I suspect there are improvements in there that may be helpful to us.

**Comment by loveshack** [comment]
OK, I can review it, but it needs to obey the packaging guidelines,
which I'd expect to bring it close to my version.  Ping me to make sure
I don't miss the view request.  In the meantime, the copr is there.

**Comment by reidpr** [comment]
This seems safe to close, given the progress on the other spec file and merging of much of your stuff. Please re-open if I've missed something.
