### ISSUE TITLE
OVA image: document why simple "passwd" doesn't work

### ISSUE THREAD

**Issue by rstyd** [hpc/charliecloud#365]
After creating an OVA with Vagrant following the steps [here](https://hpc.github.io/charliecloud/vm.html#build-ova-appliance-file-with-vagrant-and-virtualbox). I was unable to change the password with passwd. @j-ogas reported running into this issue as well. 

```
$ passwd
Changing password for user charlie.
Changing password for charlie. 
(current) UNIX password:
passwd: Authentication token manipulation error
```

**Comment by reidpr** [comment]
This works with `sudo passwd charlie`, which is documented but not justified. We should improve the documentation.
