### ISSUE TITLE
Charliecloud Won't Compile out of the box on newer Ubuntu Versions

### ISSUE THREAD

**Issue by rstyd** [hpc/charliecloud#373]
Python3 is now the standard python interpreter on Ubuntu. As a result, https://github.com/hpc/charliecloud/blob/master/doc-src/install.rst#prequisites needs to be updated to instruct Ubuntu 16.04 and 18.04 users to install the `python-minimal` package before compiling charliecloud.

**Comment by reidpr** [comment]
While we're in there, we should fix the spelling of "prerequisites" too.

**Comment by reidpr** [comment]
Can you clarify the problem? I see that we state Python 2.7 or 3.4+ as needed for the test suite. So if Ubuntu has Python 3, it should work. What is the error message?

**Comment by reidpr** [comment]
I think the new Autotools build system, specifically the report from `configure`, should cover this. Please re-open if I am wrong.
