### ISSUE TITLE
RPMs accepted into Fedora

### ISSUE THREAD

**Issue by j-ogas** [hpc/charliecloud#384]
Review request: https://bugzilla.redhat.com/show_bug.cgi?id=1690046

**Comment by j-ogas** [comment]
The 0.9.10 updates to the spec file have been submitted to Fedora.

**Comment by j-ogas** [comment]
The 0.9.10 package has been approved. I'm in the process of testing a branch with the accepted 0.9.10 spec file changes. I'll submit a PR to address this issue by COB.

**Comment by reidpr** [comment]
Can we close this?

**Comment by j-ogas** [comment]
Yes!
