### ISSUE TITLE
ch-build centos6 test takes too long for Travis

### ISSUE THREAD

**Issue by mcv21** [hpc/charliecloud#40]
Hi,

A number of builds for my recent MRs have failed, seemingly because Travis gets bored of waiting for the ch-build centos6 test to complete. I think this may just mean that it needs to be told to wait longer for output to appear?

[my MRs didn't touch that bit of the test framework, so I don't think it's my fault!]

**Comment by reidpr** [comment]
I wonder if something strange is going on with Travis. I re-ran a previously successful build ([284](https://travis-ci.org/hpc/charliecloud/builds/290609118)), and it now fails with similar problems (`ch-build alpineedge` times out).

I will continue to investigate.

**Comment by reidpr** [comment]
Here's a status page; seems they are having issues with Docker pulls. This might manifest as network timeouts, which would be consistent with the observed symptoms.

https://www.traviscistatus.com/incidents/v4jnp6nkgzqx

**Comment by reidpr** [comment]
I think this problem can be explained by the Travis outage, so closing. Please re-open if it recurs.
