### ISSUE TITLE
Allow user to skip tests that require sudo

### ISSUE THREAD

**Issue by pagrubel** [hpc/charliecloud#403]
Check for a flag such as CH_HAVE_SUDO before performing tests that need sudo

**Comment by j-ogas** [comment]
We have a similar skipping mechanism for docker, e.g., `CH_TEST_SKIP_DOCKER=yes`. Perhaps we could include `CH_TEST_SKIP_SUDO=yes` to common.bash.

**Comment by reidpr** [comment]
Right now we just test for access to the `sudo` command in `common.bash`. I think the right approach is just extend that test to only set the variable if it's unset and document it. It's already named for external access.
