### ISSUE TITLE
update tutorial and documentation for squashfs

### ISSUE THREAD

**Issue by shanegoff** [hpc/charliecloud#414]
Related: #348 squashfs becomes supported and preferred image distribution method

Section 1.1 (dependencies)

Squashfuse isn't absolutely required for run time if you plan on not using it. Should we include it as a requirement anyway to move towards squashfs becoming the default image distribution method?

The low-level FUSE API binary is not available in the apt package, debian users would need to build from source if they wanted to use it, but do not have to use it. It is available in the RPM package.

squashfs-tools is available in yum and apt. Should this be added as a build time dependency? You don't need it to build a container, but you do need it to flatten container iamges.

Section 3 (tutorial)
Somewhere in here we should mention and give examples of using tarballs if the user requires, but the existing items will be changed to reflect a squashfs workflow.

**Comment by reidpr** [comment]
Today we decided:

* We can just depend on distribution squashfuse packages. On Debian the performance will be a little lower, but that seems OK.
* The tutorial should be updated to use squashfuse for the most part, but include a little blurb to translate to tarballs if the user doesn't have squashfuse. Updating the tutorial should be a separate PR from the main squash stuff.
