### ISSUE TITLE
test 'broken image errors' fails on Ubuntu 19.04

### ISSUE THREAD

**Issue by Brofessional** [hpc/charliecloud#430]
The broken image test does not work on Ubuntu 19. On centos7 the test completes normally.

`✗ broken image errors
   (in test file run/ch-run_misc.bats, line 576)
     '[[ $output = *"can't execve(2): true: No such file or directory"* ]]' failed
   ch-run[3864]: can't execve(2): true: Not a directory (charliecloud.c:437 20)
`

The output for `execve(2)` in Ubuntu 18 appears slightly different than the output expected.

Tested using the squashfs branch of charliecloud on both machines.

**Comment by reidpr** [comment]
Good find! Shouldn't be too hard to fix.
