### ISSUE TITLE
Add BATS tests for squashfs

### ISSUE THREAD

**Issue by Brofessional** [hpc/charliecloud#432]
#408 related

New tests should be added to the BATS tests for squashfs.

The existing BATS tests all use the tar method.

We could:
- change all tests to use squashfs
- add a small number of examples to use squashfs and keep existing tests the same
- make tests work on a tar or a squashfs

Running all tests twice for squashfs doesn't seem like the way to go. Running all tests for squashfs is most likely unnecessary. Testing mount/unmount, squashing a directory, and running `ch-run` on at least one squashfs would be the minimum.

Thoughts?

**Comment by Brofessional** [comment]
Today it was decided to add a small number of squashfs related tests. Further down the line the existing tests that can be converted will be converted.

**Comment by reidpr** [comment]
Included in #408.
