### ISSUE TITLE
Packaged squashfs-tools do not support -quiet

### ISSUE THREAD

**Issue by Brofessional** [hpc/charliecloud#435]
The packaged version of the squashfs-tools do not support the quiet flag. This will make the verbose option for anything that creates a squashfs break unless using verbose mode. 

The verbose option should probably be removed, users with a newer version can pass `-quiet` at the end if they would like to.

`ch-dir2squash /tmp/debian /tmp -quiet`

This was tested on Ubuntu 19.04. I checked the packages for Ubuntu and Centos7, they both use the same version packed in 2014 and lack the -quiet flag.

**Comment by reidpr** [comment]
Included in #408.
