### ISSUE TITLE
Add test for Openmpi errors which don't result in failure

### ISSUE THREAD

**Issue by heasterday** [hpc/charliecloud#440]
If a plugin such as UCX fails during initialization OpenMPI will fall back to tcp resulting in the test suite still passing but simply taking longer to run. This means we currently may not catch regressions in the images until a test is ran outside of the suite or a particularly observant tester notices the suite took longer than usual. 

I plan to add a basic test to check for this.

**Comment by reidpr** [comment]
Related but not duplicate: #289.
