### ISSUE TITLE
handle install when test suite is not built

### ISSUE THREAD

**Issue by j-ogas** [hpc/charliecloud#446]
Related to #389 and #381.

When valid version of python is not detected the top level Makefile will not descend into the test suite and attempt and to build it. However, the top level Makefile still references files, e.g., libsotest.so via `make install` that have not yet been built:

```
#       shared library tests
    install -d $(TEST)/sotest $(TEST)/sotest/bin $(TEST)/sotest/lib
    install -pm 755 -t $(TEST)/sotest test/sotest/libsotest.so.1.0 \
                                      test/sotest/sotest
    install -pm 644 -t $(TEST)/sotest test/sotest/files_inferrable.txt \
                                      test/sotest/sotest.c
    ln -sf ./libsotest.so.1.0 $(TEST)/sotest/libsotest.so
    ln -sf ./libsotest.so.1.0 $(TEST)/sotest/libsotest.so.1
    install -pm 755 -t $(TEST)/sotest/bin test/sotest/bin/sotest
    install -pm 755 -t $(TEST)/sotest/lib test/sotest/lib/libsotest.so.1.0
```

**Comment by j-ogas** [comment]
I propose we do not include the tests and examples in the absence of python. The two thoughts behind this are: 1)  the test suite is dependent on python and 2) we can eliminate the `BuildRequires /usr/bin/python3` from the base charliecloud package.

**Comment by wiene** [comment]
I've just stumbled across this issue:
```
install: cannot stat 'test/sotest/libsotest.so.1.0': No such file or directory
install: cannot stat 'test/sotest/sotest': No such file or directory
```
What are your plans concerning PR #453?

**Comment by j-ogas** [comment]
@wiene We plan to merge it. I recently merged changes from master and requested another review. I suspect it will be merged soon.
