### ISSUE TITLE
Some tests expect unpacked images and writable space

### ISSUE THREAD

**Issue by shanegoff** [hpc/charliecloud#456]
Some bats tests have a wider scope than they should. They expect a directory to be unpacked already and in a certain place. We could remove this dependency by unpacking the image in the test instead. This way we wouldn't have to unpack all images which would save a great deal of time in the testing phase.

Some tests require a writable space (for now). Some tests could possibly be changed to simply mount an expected squash, run, then unmount instead of run on an unpacked image directory.

**Comment by reidpr** [comment]
The current test strategy is to validate both unpacked and SquashFUSE mode, and so we just disable the tests that need unpacked or writeable images in SquashFUSE mode. I don't expect that to go away anytime soon. Therefore, I think this has become moot.
