### ISSUE TITLE
genericize ch-docker2squash

### ISSUE THREAD

**Issue by reidpr** [hpc/charliecloud#465]
When the unprivileged builder PRs are merged, that will make Docker-specific scripts obsolete. I believe `ch-docker2squash` is the only one left.

**Comment by Brofessional** [comment]
Are we renaming `ch-docker2tar` to `ch-builder2tar` in #460?
Should I open a branch, or make commits to #460?

**Comment by reidpr** [comment]
> Are we renaming `ch-docker2tar` to `ch-builder2tar` in #460?

PR #455 will land first, but yes.

> Should I open a branch, or make commits to #460?

Wait until PR #455 lands, then make a new PR.
