### ISSUE TITLE
Sudo required for test-build 

### ISSUE THREAD

**Issue by alazzaro** [hpc/charliecloud#467]
This is with Charliecloud master version, installed on a Ubuntu machine. Note that I don't have sudo access.

I do install charliecloud, i.e.
1) `git clone --recursive https://github.com/hpc/charliecloud`
2) `cd charliecloud`
3) `make`
4) `make install PREFIX=<install dir>`

Then, following the instructions at https://hpc.github.io/charliecloud/test.html#getting-started, I go to <install dir>/libexec/charliecloud-0.9.11~pre+44b677f/test/, I see the variables:

```
export CH_TEST_DONT_SUDO="yes"
export CH_TEST_TARDIR=/var/tmp/tarballs                                                                                                                                          
export CH_TEST_IMGDIR=/var/tmp/images                                                                                                                                             export CH_TEST_PERMDIRS=skip   
```
and finally I run

`TERMINFO=/lib/terminfo make test-build`

The problem is that the test is still requiring to insert the sudo password:

```
> TERMINFO=/lib/terminfo make test-build
bats build.bats build_auto.bats build_post.bats
 ✓ create tarball directory if needed
 - documentation seems sane (skipped: Sphinx is not installed)
 ✓ version number seems sane
 ✓ executables seem sane
 ✓ ch-build --builder-info
 - lint shell scripts (skipped: no shellcheck found)
 ✓ proxy variables
 ✓ sotest executable works
 ✓ custom build chtest
 - custom build buildah (skipped: prerequisites not met)
 ✓ custom build centos7xz
 ✓ custom build ch-build2dir
 ✓ custom build ch-pull2dir
 ✓ custom build ch-pull2tar
 - custom build missing (skipped: prerequisites not met)
 - custom build skopeo-umoci (skipped: prerequisites not met)
 [sudo] password for alazzaro:                                                                                                                                                17/61

[sudo] password for alazzaro: 

[sudo] password for alazzaro: 

 ✗ ch-build alpine39
   (from function `builder_tag_p' in file common.bash, line 31,
    from function `builder_ok' in file common.bash, line 38,
    in test file build_auto.bats, line 163)
     `builder_ok alpine39' failed
   building with: docker
   Sending build context to Docker daemon    322kB
   Step 1/3 : FROM alpine:3.9
    ---> 055936d39205
   Step 2/3 : RUN apk add --no-cache bc
    ---> Using cache
    ---> f706590e1e9e
   Step 3/3 : CMD ["true"]
    ---> Using cache
    ---> f477a97482f6
   Successfully built f477a97482f6
   Successfully tagged alpine39:latest
   image tag alpine39:latest ... Sorry, try again.
   Sorry, try again.
   sudo: 3 incorrect password attempts
   not found
 ✓ builder to archive alpine39
```

The test continues with other tests requiring sudo access.
I assume this is because he wants to download/build some images in docker, but I really want to have rootless installation/testings. Is there way to drop sudo access by removing the tests requiring it (I thought #403 was meant for that)

**Comment by reidpr** [comment]
Sorry for the hassle. This is definitely a bug. Thank you for the excellent bug report. Yes, you're correct that #403 should have fixed this.

One thing to try immediately would be to set the variable `CH_TEST_SKIP_DOCKER`; this has been around for a while and should turn off all the Docker tests, giving you a subset of the test suite.

We also just merged to master one of the two unprivileged build methods that are targeted to 0.9.11. If you set `CH_BUILDER=ch-grow`, it will use our internal builder `ch-grow`, which is completely unprivileged. The non-Docker unprivileged builds are what we're targeting for the future. This should build most of the test suite but is weakly tested right now.

Does that help?

**Comment by alazzaro** [comment]
Great! So, 
```
export CH_TEST_SKIP_DOCKER="yes"
```
does pass the tests and I get

58 tests, 0 failures, 47 skipped

However, I really like the idea to have rootless as much as possible, so I'm interested in whatever it comes for 0.9.11. Therefore I did:

```
export CH_TEST_DONT_SUDO="yes"
export CH_BUILDER=ch-grow
export CH_TEST_TARDIR=/var/tmp/tarballs                                                                                                                                          
export CH_TEST_IMGDIR=/var/tmp/images                                                                                                                                            
export CH_TEST_PERMDIRS=skip  
```
and then run

```
TERMINFO=/lib/terminfo make test-build  
```
I get the following output:
```
✓ create tarball directory if needed
 - documentation seems sane (skipped: Sphinx is not installed)
 ✓ version number seems sane
 ✓ executables seem sane
 ✓ ch-build --builder-info
 - lint shell scripts (skipped: no shellcheck found)
 ✓ proxy variables
 ✓ sotest executable works
 ✓ custom build chtest
 - custom build buildah (skipped: prerequisites not met)
 ✓ custom build centos7xz
 ✗ custom build ch-build2dir
   (in test file build_auto.bats, line 79)
     `[[ $status -eq 0 ]]' failed
   + /home/alazzaro/Work/containers/charliecloud/charliecloud_44b677f/bin/ch-build -t build2dir --file=Dockerfile.alpine39 .
   building with: ch-grow
   missing dependency: Python module "lark"
   
 ✗ custom build ch-pull2dir
   (in test file build_auto.bats, line 98)
     `[[ $status -eq 0 ]]' failed
   3.9: Pulling from library/alpine
   Digest: sha256:7746df395af22f04212cd25a92c1d6dbc5a06a0ca9579a229ef43008d4d1302a
   Status: Image is up to date for alpine:3.9
   building with: ch-grow
   exporting
   /home/alazzaro/Work/containers/charliecloud/charliecloud_44b677f/bin/ch-builder2tar: 49: cd: can't cd to /var/tmp/tarballs/_ch-grow/img/alpine:3.9
   compressing
   -rw-rw-r-- 1 alazzaro alazzaro 20 Jul  1 17:51 ./alpine:3.9.tar.gz
   creating new image ./alpine:3.9
   /home/alazzaro/Work/containers/charliecloud/charliecloud_44b677f/bin/ch-tar2dir: 129: /home/alazzaro/Work/containers/charliecloud/charliecloud_44b677f/bin/ch-tar2dir: cannot create ./alpine:3.9/WEIRD_AL_YANKOVIC: Directory nonexistent
```
I have installed the lark-parser for python3. 

But then it misses skopeo. Should I have to install it?

**Comment by reidpr** [comment]
Yes, you'll need both skopeo and umoci. You should be able to install these without sudo. URLs would be in `doc-src/install.rst` where the new install instructions are.

You shouldn't need `CH_TEST_DONT_SUDO` with `CH_BUILDER=ch-grow`.

**Comment by alazzaro** [comment]
OK, I did a clean installation. 
Unfortunately, skopeo requires some packages, which are not installed on my system:

sudo apt install libdevmapper-dev go-md2man

I asked the sysadmin to install them. 

Then, the instructions at https://github.com/containers/skopeo require a sudo installation, which I've just ignored by using

make install PREFIX=<local dir>

The umoci installation went fine.

Concerning `CH_TEST_DONT_SUDO`, if I don't set it I get:
```
 > make test-build 
bats build.bats build_auto.bats build_post.bats
[sudo] password for alazzaro: 
```
so something is broken there...

Finally, I set the directory env variables + `export CH_BUILDER=ch-grow`, and I do the command `TERMINFO=/lib/terminfo make test-build`, and I get:
```
✗ custom build ch-build2dir
   (in test file build_auto.bats, line 79)
     `[[ $status -eq 0 ]]' failed
   + /home/alazzaro/Work/containers/charliecloud/charliecloud_44b677f/bin/ch-build -t build2dir --file=Dockerfile.alpine39 .
   building with: ch-grow
   growing: /var/tmp/tarballs/_ch-grow/img/build2dir:latest
     2 FROM alpine:3.9 
   time="2019-07-01T21:37:24+02:00" level=fatal msg="Error loading trust policy: open /etc/containers/policy.json: no such file or directory" 
   skopeo failed with return code 1
```

I think `/etc/containers/policy.json` is inside `skopeo/integration/fixtures/policy.json`, but I cannot copy in /etc. It seems the problem is somehow address here:

https://github.com/containers/skopeo/issues/181

Anyway, given the current status, I will go back to use:
`export CH_TEST_SKIP_DOCKER="yes"`

and wait for an official release to support CH_BUILDER=ch-grow.

**Comment by alazzaro** [comment]
OK, I went back to use
`export CH_TEST_SKIP_DOCKER="yes" ` 

and just tried the current master, it still requires sudo after the message:
```
bats build.bats build_auto.bats build_post.bats
 ✓ create tarball directory if needed
 - documentation seems sane (skipped: Sphinx is not installed)
 ✓ version number seems sane
 ✓ executables seem sane
 ✓ ch-build --builder-info
 - lint shell scripts (skipped: no shellcheck found)
 ✓ proxy variables
 ✓ sotest executable works
 ✓ custom build chtest
 - custom build buildah (skipped: prerequisites not met)
 ✓ custom build centos7xz
 ✓ custom build ch-build2dir
 ✓ custom build ch-pull2dir
 ✓ custom build ch-pull2tar
 - custom build missing (skipped: prerequisites not met)
 - custom build skopeo-umoci (skipped: prerequisites not met)
 [sudo] password for alazzaro:   
```

Then I tried v0.9.10 and there it works as before:
```
> make test-build
....
58 tests, 0 failures, 47 skipped
```

Then I tried `make test-run` and I get two failures:
```
✗ ch-run --join: multiple peers, framework launch
   (from function `joined_ok' in file run/ch-run_join.bats, line 30,
    in test file run/ch-run_join.bats, line 229)
     `joined_ok 2 2 1 "$status" "$output"' failed
   ch-run[6234]: join: no valid peer group size found (ch-run.c:312)
   ch-run[6235]: join: no valid peer group size found (ch-run.c:312)
     exit status: fail (1)
```

and

```
ch-run --unset-env
   (in test file run/ch-run_misc.bats, line 417)
     `diff -u <(env | grep -Ev "$ex") <(echo "$output" | grep -Ev "$ex")' failed
```

Finally, the `make test-test` doesn't run anything (all tests are skipped)

Any help would be appreciated.

**Comment by alazzaro** [comment]
**Update and summary.**

I have asked to install the file `/etc/containers/policy.json`.
With that, the current master runs all tests fine:
```
> export CH_TEST_DONT_SUDO="yes"
> export CH_BUILDER=ch-grow
> export CH_TEST_TARDIR=/var/tmp/tarballs
> export CH_TEST_IMGDIR=/var/tmp/images
> export CH_TEST_PERMDIRS=skip
> make test-build 
bats build.bats build_auto.bats build_post.bats
 ✓ create tarball directory if needed
 - documentation seems sane (skipped: Sphinx is not installed)
 ✓ version number seems sane
 ✓ executables seem sane
 ✓ ch-build --builder-info
 - lint shell scripts (skipped: no shellcheck found)
 ✓ proxy variables
 ✓ sotest executable works
 ✓ custom build chtest
 - custom build buildah (skipped: prerequisites not met)
 ✓ custom build centos7xz
 ✓ custom build ch-build2dir
 ✓ custom build ch-pull2dir
 ✓ custom build ch-pull2tar
 - custom build missing (skipped: prerequisites not met)
 ✓ custom build skopeo-umoci
 ✓ ch-build alpine39
 ✓ builder to archive alpine39
 - ch-build alpineedge (skipped: full scope)
 - builder to archive alpineedge (skipped: full scope)
 - ch-build centos6 (skipped: full scope)
 - builder to archive centos6 (skipped: full scope)
 ✓ ch-build centos7
 ✓ builder to archive centos7
 ✓ ch-build debian9
 ✓ builder to archive debian9
 ✓ ch-build exhaustive
 ✓ builder to archive exhaustive
 - ch-build mpich (skipped: full scope)
 - builder to archive mpich (skipped: full scope)
 - ch-build nvidia (skipped: full scope)
 - builder to archive nvidia (skipped: full scope)
 - ch-build openmpi (skipped: full scope)
 - builder to archive openmpi (skipped: full scope)
 - ch-build python3 (skipped: full scope)
 - builder to archive python3 (skipped: full scope)
 - ch-build ubuntu1604 (skipped: full scope)
 - builder to archive ubuntu1604 (skipped: full scope)
 - docker pull alpine39_dp (skipped: requires Docker)
 - builder to archive alpine39_dp (skipped: requires Docker)
 - ch-build lammps (skipped: full scope)
 - builder to archive lammps (skipped: full scope)
 - ch-build paraview (skipped: full scope)
 - builder to archive paraview (skipped: full scope)
 ✓ ch-build spark
 ✓ builder to archive spark
 ✓ ch-build hello
 ✓ builder to archive hello
 - ch-build obspy (skipped: developer-skipped; see comments and/or issues)
 - builder to archive obspy (skipped: developer-skipped; see comments and/or issues)
 - ch-build spack (skipped: full scope)
 - builder to archive spack (skipped: full scope)
 - ch-build mpibench-mpich (skipped: full scope)
 - builder to archive mpibench-mpich (skipped: full scope)
 - ch-build mpibench-openmpi (skipped: full scope)
 - builder to archive mpibench-openmpi (skipped: full scope)
 - ch-build mpihello-mpich (skipped: full scope)
 - builder to archive mpihello-mpich (skipped: full scope)
 - ch-build mpihello-openmpi (skipped: full scope)
 - builder to archive mpihello-openmpi (skipped: full scope)
 ✓ nothing unexpected in tarball directory

61 tests, 0 failures, 36 skipped
```
**Open problems**

1) It still requires to set `export CH_TEST_DONT_SUDO="yes"` in combination with `export CH_BUILDER=ch-grow`, otherwise `make test-build` requires to insert sudo password

1) `make test-run` still fails on two tests:
```
✗ ch-run --join: multiple peers, framework launch
   (from function `joined_ok' in file run/ch-run_join.bats, line 30,
    in test file run/ch-run_join.bats, line 229)
     `joined_ok 2 2 1 "$status" "$output"' failed
   ch-run[4584]: join: no valid peer group size found (ch-run.c:314)
   ch-run[4585]: join: no valid peer group size found (ch-run.c:314)
     exit status: fail (1)
✗ ch-run --unset-env
   (in test file run/ch-run_misc.bats, line 417)
     `diff -u <(env | grep -Ev "$ex") <(echo "$output" | grep -Ev "$ex")' failed
   
   # Nothing
```

3) I will inquire with skopeo people on how to install locally.

**Comment by alazzaro** [comment]
Cross-referencing: https://github.com/containers/skopeo/issues/687#issuecomment-507619077

**Comment by reidpr** [comment]
Hello Alfio, thanks for your patience and continued thorough updates. Let me split these problems out into separate issues:

1. Test suite with `CH_BUILDER=ch-grow` should not try to sudo: #469.

2. Test failures in `make test-run`: #470.

3. skopeo install problems. We do have some people here at LANL who want to install skopeo without root, so that may help. Let's see how this shakes out; a doc update may be in order. I would prefer not to document how to install third-party tools, but that may be a reasonable interim measure.

4. `CH_TEST_SKIP_DOCKER` should actually have been removed (it's replace by `CH_BUILDER`): #471.

Have I missed anything?

Finally, I think that despite your problems with the test suite, you can probably use `ch-grow` to make some progress on your real work.

**Comment by alazzaro** [comment]
The summary is correct!
Currently, I'm using the images built with docker on my local VM (where I have sudo privileges), so rootless building will come at the next stage. The first step is to get some performance results on Cray systems.

Thanks for your help!

**Comment by reidpr** [comment]
Hello @alazzaro, is this still an issue? We've re-done the test suite extensively since July; if it doesn't apply any more, we should close.

**Comment by alazzaro** [comment]
I've tried your latest fixes (lack of time), but you can close the issue... Thanks!
