### ISSUE TITLE
test suite tries to sudo with CH_BUILDER=ch-grow

### ISSUE THREAD

**Issue by reidpr** [hpc/charliecloud#469]
@alazzaro reports in #467:

> It still requires to set `export CH_TEST_DONT_SUDO="yes"` in combination with `export CH_BUILDER=ch-grow`, otherwise `make test-build` requires to insert sudo password.

Unless `CH_BUILDER=docker`, the test suite should not try to sudo at all.

**Comment by reidpr** [comment]
I realized that we do have tests that need sudo even with the unprivileged builders, e.g. messing with `ch-run` owner UIDs. However, if someone does not have sudo, they should not be prompted for a password, and these tests should be skipped.

@alazzaro, what is the output you get from `sudo -v`?

For someone without sudo, I'd expect this:

```
$ sudo -v
Sorry, user <foo> may not run sudo on <bar>.
$ echo $?
1
```

For me, with full sudo, I get this:

```
$ sudo -v
[sudo] password for reidpr:
$ echo $?
0
```

**Comment by alazzaro** [comment]
Ah, that's interesting:
1) On a system where I do have the sudo privileges, I get the latter message:
```
> sudo -v
[sudo] password for alazzaro: 
```

2) On the cluster, where I don't have any sudo, I get the former message:
```
> sudo -v
Sorry, user alazzaro may not run sudo on daint104.
```
So your assumption is correct.
I think it is clear the reason for the confusion: the system tries to figure out if I have sudo and ask me for the password, even if I don't want to use it in any way...

**Comment by reidpr** [comment]
Thanks for the clarification.

I think that it may be working as intended: guess if sudo is available and desired (the assumption being that if it's available, the user wants to use it), and provide an override (`CH_TEST_DONT_SUDO`) for when we get it wrong. Does that sound reasonable?

The above also suggests another building approach: build images using Docker on the system where you do have sudo, and then copy them to the cluster.

**Comment by alazzaro** [comment]
> I think that it may be working as intended: guess if sudo is available and desired (the assumption being that if it's available, the user wants to use it), and provide an override (`CH_TEST_DONT_SUDO`) for when we get it wrong. Does that sound reasonable?

Yes, it does. The idea is that the system checks automatically for `sudo`, unless the user specifically asks to avoid that.

> 
> The above also suggests another building approach: build images using Docker on the system where you do have sudo, and then copy them to the cluster.

Correct, that's what I do now. In the future, I can consider using rootless charliecloud to build too...

**Comment by reidpr** [comment]
OK, I'll go ahead and close this issue then. I apologize for misleading you about how things work.
