### ISSUE TITLE
SUPP_GIDS_MAX is fixed to 32

### ISSUE THREAD

**Issue by olifre** [hpc/charliecloud#47]
Hardcoded here: 
https://github.com/hpc/charliecloud/blob/b134cb52b3e009519e314e3eca2ea27d6e4e25d1/bin/ch-run.c#L41

The actual limit should be:
```
NGROUPS_MAX (32 before Linux 2.6.4; 65536 since Linux 2.6.4).
```
according to the man page of `getgroups`. 
`NGROUPS_MAX` is defined in: `linux/limits.h`. 

I actually ran into this with a desktop user here ;-).

**Comment by reidpr** [comment]
It's hardcoded so we can use a static array and avoid allocating memory.

I'm happy to raise it to meet real use cases, but does anyone really have 64K groups? How many groups is your desktop user in?

**Comment by olifre** [comment]
> It's hardcoded so we can use a static array and avoid allocating memory.

Ok, that's understandable. It's always nice if allocation (or even dynamic allocation) can be avoided. 

> How many groups is your desktop user in?

```
$ groups | tr ' ' '\n' | wc -l
40
```
So it's 40 groups (containing many things like pulse, pulse-access, pulse-rt, networkmanager... typical Desktop bloat). 

Indeed, `4*65536` would be 256 kBytes, which is not such a small amount to put on the stack, so I understand you don't want to bump that number for a static allocation. 

I guess that something like 64 or (maybe safer) 128 is sufficient for quite everybody. 

Maybe in addition, it would be nice to add an extra call to `getgroups(0, supp_gids)` to check whether the limit would be exceeded and produce an easier to grasp error message ;-).
