### ISSUE TITLE
ch-grow: running skopeo installed by user

### ISSUE THREAD

**Issue by paulbry** [hpc/charliecloud#475]
If running an installation of Skopeo installed as a user it leads to the following error:

```console
  1 FROM debian:stable-slim
FATA[0000] Error loading trust policy: open /etc/containers/policy.json: no such file or directory
skopeo failed with return code 1
```

Skopeo offers a few flags to deal with this and I  can't find any way that I'm able to install it as a user without running into the issue.

```console
   --policy value           Path to a trust policy file
   --insecure-policy        run the tool without any policy check
```

To test I changed the ch-grow to the following:

```python
cmd(["skopeo", "--insecure-policy", "copy", "docker://" + self.fullname,
           "oci:%s/%s" % (dir_ocis(), self.fullname)])
```

This worked but is not an ideal solution. Maybe supplying a default policy or allowing a user specified one?

**Comment by reidpr** [comment]
Since we are not using skopeo to pull images any more (PR #616), this issue is moot. Thank you for the report, and please file additional issues if you're having trouble with the new approach. Closing.
