### ISSUE TITLE
more friendly image management (“Goff Plan”)

### ISSUE THREAD

**Issue by shanegoff** [hpc/charliecloud#484]
With the new builders and squashfs support we've created a number of new scripts and helpers for managing all this stuff. It's awesome to support so many things but it might be easier for users to have the utility crammed into one place.

We have files to create different output files between tar and squash. Adding the new builders, the new support was added into a single file instead of multiple files. We should follow that idea farther I think.

Example:

`ch-export -b [BUILDER] -t [OUT_TYPE] IMAGE OUTDIR`

This would make it so flattening an image from a builder to a file would be a one stop shop. 

`ch-export -b ch-grow -t dir alpine /tmp`
`ch-export -b docker -t squash lammps /dev/shm`

This would be easier for people when managing images. They wouldn't have to call separate files for different output types.

It would also clear up some confusion regarding that the builders don't actually build something when you call `ch-builder2tar` so it would be more clear that you are creating a flattened image that was already created by the builder, not building it.

**Comment by reidpr** [comment]
In our discussion today, it was pointed out that we now have 17 executables, which is a lot. We decided that the next step is to articulate the workflow better so we can understand how best to reorganized.

**Comment by j-ogas** [comment]
Recommend using something like`-o, --out-type` instead of `-t, --out-type`. `-t` is closely related to `TAG`.

**Comment by reidpr** [comment]
@Brofessional is suggesting that `ch-run` should know how to run tarballs and squashes in addition to directories.

**Comment by Brofessional** [comment]
I also suggest using a single command with sub commands for the future

`ch-run $IMAGE -- $COMMAND` ---> `ch run $IMAGE $COMMAND`
`ch-builder2squash $IMAGE $OUTDIR` ----> `ch export $IMAGE $OUTDiR`

etc
I'll look into creating bash completion scripts for the use case.

**Comment by reidpr** [comment]
This has been done, with two exceptions: (1) `ch-convert` doesn't speak Podman (issue #1360), and (2) `ch-run` doesn't know how to call `ch-fromhost` automatically (issue #1361). Closing.
