### ISSUE TITLE
ch-run as root: root with non-zero gid refused (skip if requirements are not met)

### ISSUE THREAD

**Issue by j-ogas** [hpc/charliecloud#485]
The `run/ch-run_escalated.bats` test `ch-run as root: root with non-zero gid refused ` has caused confusion for some time now. Section 2.2.2 of the run phase documentation states that a user needs to be a member of two groups. The actual requirement is that they need a sudoers config to allow groups other than root (GID 0) without a password.

In any case, the output from the error isn't helpful in describing why the test failed. This test should skip if the condition for the test isn't met.

```
✗ ch-run as root: root with non-zero gid refused
   (in test file run/ch-run_escalated.bats, line 70)
      `[[ $output = *'error ('* ]]' failed
   Sorry, user vagrant is not allowed to execute '/usr/bin/ch-run -v
--version' as root:vagrant on localhost.localdomain.
```

**Comment by loveshack** [comment]
Note that the failure was under an account that satisfied the requirements (although README.TEST in the rpm packaging doesn't mention it). Also I get other failures, like in https://bugzilla.redhat.com/show_bug.cgi?id=1690046, if I set CH_TEST_DONT_SUDO.  Sorry I don't have time to debug it at present.

**Comment by j-ogas** [comment]
@loveshack Does the sudoers config have `(ALL:ALL)`? For example, if the secondary group was `charlie`:

```
%charlie ALL=(ALL:ALL) NOPASSWD: ALL
```

**Comment by reidpr** [comment]
It shouldn't require no password, just be able to sudo to the other group. That configuration (password required) works on my dev box.

That second part is an unusual configuration though, and the bug report stands regardless of the password requirement IMO.

**Comment by loveshack** [comment]
This is in an el7 vagrant box (for which I can provide a recipe if
necessary); I can't run on bare metal under a Fedora-ish OS with user
namespaces, and I got other errors on bare Debian.  The vagrant account
under which things run is installed with

  $ sudo cat /etc/sudoers.d/vagrant
  %vagrant ALL=(ALL) NOPASSWD: ALL

like the same as the default %wheel configuration.  Changing that to
ALL:ALL does fix "74 ch-run as root", but it still fails on subsequent
tests.
