### ISSUE TITLE
ch-grow: preserve dockerfile environment

### ISSUE THREAD

**Issue by CalvinDSeamons** [hpc/charliecloud#488]
It would appear that the environment file: `ch/environment` no longer exists inside the generated image when using ch-grow. Would it be possible to keep this file?

**Comment by reidpr** [comment]
It should be there, and the test suite should test for this. Retagging as bug. Can you provide a reproducer?

**Comment by CalvinDSeamons** [comment]
I was referencing an old location for the environment file, `ch-build` and `ch-grow` both generate the environment file.
