### ISSUE TITLE
change build system to GNU autotools?

### ISSUE THREAD

**Issue by reidpr** [hpc/charliecloud#499]
Related to #169, I am concerned that our hand-maintained makefiles are becoming unwieldy. I looked at some options (CMake, Scons, GNU autotools), and it seemed the most viable option was GNU autotools.

The first step is to determine feasibility, i.e.:

* How hard is converting to GNU autotools?
* What, specifically, are the steps needed to convert? (e.g., how do we deal with `.so` files in the test suite?)
* What improvements can be gained? (e.g., patching Python scripts against Python 2 or 3 at build time)

**Comment by rstyd** [comment]
**How hard is converting to GNU autotools?**
Getting a basic build does not look too difficult. Building the documentation and setting up the tests looks to be the most challenging. 

**What, specifically, are the steps needed to convert? (e.g., how do we deal with .so files in the test suite?)**

Autotools requires a couple files: `configure.ac` and `Makefile.am`. configure.ac is used by autoconf to create a configure script which generates a Makefile. Makefile.am is used by automake to generate Makefile.in which is used by configure to generate the makefile.   

The makefile.am is essentially a list of targets executables and sources which looks something like this:

```
bin_PROGRAMS = hello
hello_SOURCES = hello.c
```

To support building the .so files in the test suite, we will need to use automake’s  libtool support. It _should_ be as simple as:

```
lib_LTLIBRARIES = libsotest.la
mylibrary_la_SOURCES = sotest/libsotest.c
```

The configure.ac sets up the overall configuration for autoconf.  Here is an example:
```
AC_INIT([charliecloud], [0.10])
AC_CONFIG_SRCDIR([ch-grow])
```

The work will mostly be getting the automake scripts to line up with our current build process. 

**What improvements can be gained? (e.g., patching Python scripts against Python 2 or 3 at build time)**

We can decide which pieces of charliecloud to build at compile-time according to the user's environment. For example, if the user doesn’t have Python, don’t install `ch-grow` and related scripts. If the user doesn’t have the capabilities to use docker, ch-grow, or buildah we can provide just the bare essentials so they can run OCI images. 

Autotools has a lot of features geared toward providing packages. I think this will solve some of the issues we’ve had re: the documentation in the Fedora package. It will also enable us to choose Python 2 or 3 at build time. This hopefully shouldn’t be an issue for much longer with the upcoming sunsetting of Python 2.

**Comment by reidpr** [comment]
Thanks Rusty.

What are the `configure` options we would need? E.g., off the top of my head, I can think of Python present or absent, Python 2 or 3 installed, path to Python (e.g., `--with-python=/usr/bin/python3`), is `lark-parser` installed, is skopeo installed, is umoci installed, Buildah installed and proper version, etc.

**Comment by rstyd** [comment]
Including what you listed: 

* Are unprivileged user namespaces turned on? (This will likely be hard) 
* Is gcc installed? (Can we use Clang?)
* Is Docker installed?
* Is Python installed?
	* Python 2 or 3
		* Build the documentation? 
		* Is lark-parser installed?
			* Install ch-grow?
	* Path to Python 
* Is Bats installed?
* Does the user have sudo?
* Is skopeo installed?
* Is umoci installed?
* Is Buildah installed with the proper version?
	* Is set[u,g]id installed?

Is that missing anything?
