### ISSUE TITLE
update C code to take full advantage of C99

### ISSUE THREAD

**Issue by reidpr** [hpc/charliecloud#500]
We build (or should be building) the C files with `-std=c11`, but we don't actually take advantage of C11 features. This issue is to:

* audit the code and make a checklist of changes to make it really C11
* lead discussion on what to do
* do it

**Comment by rstyd** [comment]
Here are features of C11 that could apply to charliecloud

    * A reimplementation of fopen called fopen_s
        - More secure than fopen
        - Instead of returning a FILE pointer, fopen_s accepts a FILE pointer as an argument
        - Validates parameters are invalid and errors out instead of providing undefined behavior

    * New implementations of the various formatted output and input functions
        - Ones we include are printf, fprintf, asprintf, dprintf
        - Each of these are appended with _s
        - Much like fopen_s they provide a more secure interface than the original

    * A native C thread library and atomic types
        - Doesn't support semaphores so we would have to rewrite charliecloud.c
        - There isn't any killer feature we'd gain from this

    * Unicode strings
        - Provides native unicode support with u8"¿String?"
        - This would provide charliecloud with better support for other languages

    * A new _Noreturn keyword l
        - The compiler can make additional optimizations when _noreturn is prepended in front of a void function

    * Type-generic macros
        - Gives access to macros that can accept any type
            #define fabs(X) _Generic( (X), \
                                 long double: fabsl, \
                                 default: fabs, \
                                 float: fabsf \
                                ) (X)

    * static_assert
        - Works much like the current test functions we have
            - Prints the line number, file, and function where the error occurs
        - Requires a string literal which won't work for us since we can't use the msg function

     * Anonymous Structs and unions


Of these features, only unicode, static_assert, atomic types, and anonymous structs/unions are included in gcc. 

The annex K functions (fopen_s, printf_s) are pretty controversial. They're not included in gcc, and it appears they may be removed from future C specifications.

**Comment by reidpr** [comment]
Thanks Rusty. I spent a little time poking too. I just looked at the [C99](https://en.wikipedia.org/wiki/C99) and [C11](https://en.wikipedia.org/wiki/C11_(C_standard_revision)) Wikipedia pages, which have nice change lists.

I did find some C99 features that we aren't using consistently but possibly should be:

* More specific [data types](https://en.wikipedia.org/wiki/C_data_types).
* Designated initializers (e.g. `struct foo = { .bar = 1, .baz = 2 }`).
* Compound literals.
* Variadic macros, we are already using.
* Proper use of `static` throughout the code for function arguments and return values. (I never really understood this and couldn't get it right, so I took them all out.)

From your list above, the following seem possibly useful, but in a minor way:

* Unicode string.
* Anonymous structs ([e.g.](https://github.com/hpc/charliecloud/blob/aaff1222ae3126b625db3af04ef4c4ddd965476d/bin/charliecloud.c#L76)).

All that said, it seems we are not actually using any C11 features? I wonder if we should reduce the requirement to C99.

Note that we are relying heavily on `asprintf(3)`, which is not standard, but I suspect it's widely supported.

**Comment by rstyd** [comment]
> All that said, it seems we are not actually using any C11 features? I wonder if we should reduce the requirement to C99.

That's where I stand on this. There doesn't seem to really be anything to gain, and it makes the project less portable.

**Comment by reidpr** [comment]
Meeting discussion outcome was to reduce the dependency to C99, and update the code to take advantage of any C99 features we're not using, e.g. but not limited to above list.

Question: How closely do we actually align with the C99 standard? We can find out with something like `-std=c99 -Wpedantic` (though see [caveat](https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html)).

This issue is to update the code. Restating the dependency will happen in #499.

**Comment by rstyd** [comment]
I added `-std=c99 and -Wpedantic` to `CFLAGS`, and the tests passed on `quick` scope. It didn't have a problem with asprintf. The gcc man page explains this:
```
Some users try to use -Wpedantic to check programs for strict ISO C conformance.  They soon find that it does not do quite what
           they want: it finds some non-ISO practices, but not all---only those for which ISO C requires a diagnostic, and some others for
           which diagnostics have been added.

           A feature to report any failure to conform to ISO C might be useful in some instances, but would require considerable
           additional work and would be quite different from -Wpedantic.  We don't have plans to support such a feature in the near
           future.
```
I'm going to start looking for areas to add c99 features and propose a list.
