### ISSUE TITLE
executables should show help if run with no arguments

### ISSUE THREAD

**Issue by ana** [hpc/charliecloud#503]
If you run ch-run-oci without arguments you get a python traceback instead of a help message:

```
ana@green:~> ch-run-oci 
Traceback (most recent call last):
  File "/usr/bin/ch-run-oci", line 365, in <module>
    main()
  File "/usr/bin/ch-run-oci", line 33, in main
    args = args_parse()
  File "/usr/bin/ch-run-oci", line 82, in args_parse
    bundle_ = bundle_from_cid(args_.cid)
AttributeError: 'Namespace' object has no attribute 'cid'
```
By the way, the command wrapped `ch-run` also shows an error  when it's run without arguments:

```
ana@green:~> ch-run
ch-run[19635]: NEWROOT and/or CMD not specified (ch-run.c:139)
``` 

It would be nice to get a short help message.

In case it's not evident, this is with version 0.10

**Comment by rstyd** [comment]
Hi Ana,
Good find!

**Comment by reidpr** [comment]
@ana, I think you've hit on a larger problem. I believe none of the executables do the right thing without arguments. Seems to me that the behavior should be equivalent to `--help` and we should test this.
