### ISSUE TITLE
Orange ch-grow text persists in terminal after a crash

### ISSUE THREAD

**Issue by rstyd** [hpc/charliecloud#509]
![image](https://user-images.githubusercontent.com/840943/62738078-a732f380-b9ee-11e9-8744-df5d60069f9d.png)
We need to reset the text in the case of a crash.

**Comment by reidpr** [comment]
I think the way to fix this is register a clean-up function to be run at exit and reset the colors there. I believe there are different ways to do this, and only some will be run after an exception.
