### ISSUE TITLE
Vagrant docs recommend old version of Charliecloud

### ISSUE THREAD

**Issue by rstyd** [hpc/charliecloud#511]
The documentation [here](https://github.com/hpc/charliecloud/blob/master/doc-src/vm.rst#build-and-provision-1) instructs users to use vagrant with `CH_VERSION=v0.9.1 vagrant up`. This command installs a version of Charliecloud from August of last year. I think it should instead say just `vagrant up` which will install the newest version of charliecloud. Thoughts?

**Comment by reidpr** [comment]
The current behavior is that omitting `CH_VERSION` installs Git master, which is probably not a good default at this point.

We could change the default to the newest tagged version though. For example:

```
$ git tag --sort=-version:refname --format='%(refname:strip=2)' | head -1
v0.10
```

**Comment by rstyd** [comment]
Sounds good to me.
