### ISSUE TITLE
Friendlier error message if user has too many supplementary groups

### ISSUE THREAD

**Issue by reidpr** [hpc/charliecloud#52]
@olifre suggests in #47:

> Maybe in addition, it would be nice to add an extra call to getgroups(0, supp_gids) to check whether the limit would be exceeded and produce an easier to grasp error message ;-).

I think we might not need a second call and could just check for `EINVAL`?

**Comment by olifre** [comment]
> I think we might not need a second call and could just check for EINVAL?

I believe you are right, my manpage tells me:
```
       EINVAL size is less than the number of supplementary group IDs, but is not zero.
```
Since that seems to be the only error reason for `EINVAL`, it should be sufficient to check for that from the already existing call. Nice catch! :-)
