### ISSUE TITLE
document use of PR_SET_NO_NEW_PRIVS

### ISSUE THREAD

**Issue by loveshack** [hpc/charliecloud#525]
PR_SET_NO_NEW_PRIVS is used, but isn't documented (except for a mention under OCI use) and I can't see a rationale.
Could you document it with an explanation?  It could preclude reasonable use of setgid, in particular, and I don't see how it can be useful as a security feature, specifically as anyone could build with that removed.

**Comment by reidpr** [comment]
@mej, can you write a few sentences on this? Here is fine, and I'll put it where it should go.
