### ISSUE TITLE
update tutorial, add best practices

### ISSUE THREAD

**Issue by j-ogas** [hpc/charliecloud#536]
Our documentation is written and organized for a time that has since passed. We've come a long a way, our documentation is due for a makeover.

Updating the documentation is coupled with: #499, #484, and #445.

**Comment by Brofessional** [comment]
Also related #414 and #348

**Comment by reidpr** [comment]
So looking over all the issues tagged `doc`, there are a lot of specific critiques and then this one, which basically says “do a revision pass on the documentation to update it”. Given that, I'd expect a PR that addresses this issue along with several others selected from the `doc` tag. Maybe Hunter you can propose a set of issues to go together in that PR?
