### ISSUE TITLE
test Vagrantfile

### ISSUE THREAD

**Issue by reidpr** [hpc/charliecloud#554]
Currently we do not test that the Vagrantfile can build and pass the Charliecloud test suite, so it breaks a lot.

Should we add it to Travis? Soon (#517) it will take 40–50 minutes to run, because we'll run the test suite three times with different builders.

Alternately, we could write a `test.sh` that we can periodically run manually.

**Comment by rstyd** [comment]
We should evaluate how Github Actions might help with this. We could use a cron Actions job to run a periodic Vagrant test.

**Comment by reidpr** [comment]
Closing per removal of Vagrant support in #1204.
