### ISSUE TITLE
make docs build with EPEL Sphinx

### ISSUE THREAD

**Issue by reidpr** [hpc/charliecloud#565]
I believe we are close to making the docs build without error in EPEL's Sphinx (which is either 1.1.3 or 1.2.3 depending on if we choose the Python 2 or Python 3 version?). Docutils looks to be 0.11 or 0.14, and RTD theme 0.2.4.

If this is true, let's make those changes, because it makes packaging easier.

I do believe we should put a note saying that while the docs build with these old versions, it is not recommended.

**Comment by reidpr** [comment]
@j-ogas proposes this patch:

```
   --- 0.10/doc-src/conf.py	                2019-09-03 18:42:01.250000000 -0600
   +++ 0.10-patch/doc-src/conf.py	2019-09-04 10:07:51.390000000 -0600
   @@ -91,8 +91,9 @@

   # The theme to use for HTML and HTML Help pages.  See the documentation for
   # a list of builtin themes.
   +import sphinx_rtd_theme
   html_theme = 'sphinx_rtd_theme'
   -
   +html_theme_path = [sphinx_rtd_theme.get_html_theme_path()]
   highlight_language = 'console'
```

**Comment by j-ogas** [comment]
> @j-ogas proposes this patch:
> 
> ```
>    --- 0.10/doc-src/conf.py	                2019-09-03 18:42:01.250000000 -0600
>    +++ 0.10-patch/doc-src/conf.py	2019-09-04 10:07:51.390000000 -0600
>    @@ -91,8 +91,9 @@
> 
>    # The theme to use for HTML and HTML Help pages.  See the documentation for
>    # a list of builtin themes.
>    +import sphinx_rtd_theme
>    html_theme = 'sphinx_rtd_theme'
>    -
>    +html_theme_path = [sphinx_rtd_theme.get_html_theme_path()]
>    highlight_language = 'console'
> ```

FWIIW, this patch reverts a change introduced in commit d8ed5e6cd9a859186dbaa33610ab86fbbe1c57b7
