### ISSUE TITLE
Can Rstudio Server be made to work with Charliecloud?

### ISSUE THREAD

**Issue by jhawe** [hpc/charliecloud#569]
Hi,

I'm currently running into an issue with charliecloud when I want to run a service which would enable users to 'logon' (i.e. normal system users which can e.g. ssh into the server).

Specifically, I'm trying to run an Rstudio Server from within charliecloud. It seems to work to some degree, i.e. I can get to the login page but whenever I enter my username and password it tells me that my username/password are wrong. I double checked my input. 

My question: Should this be possible with charliecloud or is this not possible anyways? If it should work, what could I be missing?

Apparently, Rstudio uses PAM authentication, so maybe this is an issue? (I'm not too familiar PAM so not sure what could be going wrong.

Many thanks in advance!
Johann

**Comment by reidpr** [comment]
Hello @jhawe, thanks for the question.

Charliecloud runs unprivileged and has access to only one UID, which would be whoever started Rstudio Server. I.e., if you start Rstudio Server, even if we get this working, everyone who logs in will be acting as you.

Generally speaking, logging into an application container doesn't quite make sense. Can you run Rstudio Server natively, and then once someone logs in, wrap their session in Charliecloud?

Is there a documented workflow you're trying to follow that you can link us to?

**Comment by jhawe** [comment]
Hi @reidpr ,

thanks for the quick response and explanation! I'm not yet too familiar with the workings of charliecloud, but now a little more :)

We will, at least for now, not be able to run Rstudio Server natively on our infrastructure, since 'everyone should provide their own software with charliecloud'.

Also, I guess it is hard to mix a native Rstudio session (properly) with charliecloud, since you'd have to specify the R version etc. for the server and hence a user cannot use charliecloud for that, defeating parts of its purpose imho.

I think you are right in saying that this approach doesn't quite make sense. I'll think about it a bit more, though, maybe I come up with something.

Thanks again!
Johann

**Comment by reidpr** [comment]
Hello Johann,

I apologize for being short above.

I spoke with one of our statisticians earlier. I'm not familiar with Rstudio myself, but my understanding is that this workflow lets you run Rstudio locally but use a remote compute resource, and it looks something like:

1. Start Rstudio.
2. Connect to Rstudio Server and log in.
3. Rstudio Server starts some process that will service Rstudio's requests.
4. Rstudio connects to that process.
5. You do your thing in Rstudio.

Is that accurate? If so, Charliecloud should be able to serve. The difference would be that "some process" in Step 3 is started by you directly rather than Rstudio Server.

If it would help, I'm happy to chat on the phone. Please send me an e-mail at reidpr@lanl.gov and we can arrange it.

Thanks,
Reid

**Comment by jhawe** [comment]
Hi Reid,

no problem at all and thanks for coming back to me!

It is pretty accurate: In essence, the Rstudio Server manages 'R sessions' on the remote compute resource for different users and a user can connect to his session via a browser-interface. So a user can develop and run code via this interface (essentially an IDE), though in a HPC environment this should really mostly be used for dev/testing (imho).

I'm not 100% certain on how the Rstudio Server manages the sessions internally, however, I seem to need to run a privileged container for it to be able to manage the sessions (not sure though, compare e.g. [this dockerfile](https://hub.docker.com/r/rocker/rstudio/dockerfile)). I'll dig more into this.

We can gladly chat on the phone/skype if that helps, thanks for the offer! I'll drop you a line.

Thanks,
Johann

**Comment by reidpr** [comment]
From offline e-mail thread:

> The four options for moving forward that we discussed are (IIRC):
>
> 1. Use Rstudio Server’s standard authentication. This seems incompatible with unprivileged containers and may cause difficulty with Slurm as well.
>
> 2. Authentication in Rstudio Server, then kick off a Slurm job. This would require an environment where Server could run, and then Slurm features that may require Pro with extra licensing.
>
> 3. No authentication in Rstudio Server. Users would start Server in a Slurm allocation, then connect to it and proceed without logging in. You’ve demonstrated this works. It requires an additional authentication layer on top to make sure users only connect to their own Server instance. One option would be port blocking and then an SSH tunnel, and Slurm may be able to help with an active firewall or whatnot too.
>
> 4. Users run Rdesktop and then connect to an R binary running in a Slurm allocation. We didn’t discuss this in detail.

**Comment by johrstrom** [comment]
Hi, I just happened to be browsing this repository and came upon this ticket and thought I should comment because we do run this within Singularity at our hpc site, so I may have some insight into this.

We just generate a random password and fake out the auth mechanism. This is all within a scheduled job, so the password is only valid for as long as the job (and the server) run. The next job just gets a new password. 

You can see the [script/repo here](https://github.com/OSC/bc_osc_rstudio_server/blob/master/template/script.sh.erb#L63-L68) (note that erb file extension is a ruby templating thing) for reference. 

Hope that helps and I'm not just commenting out of nowhere!

**Comment by jhawe** [comment]
Hi @johrstrom !

Thanks for your the information. I tried to adjust your template and to execute rstudio server similarly to how you are doing it, but to no avail.

my current approach is as follows: 
- start an interactive SLURM session
- prepare charliecloud image (i.e. extract it to a local directory)
- run the image

From within the image, I then call the following script (adjusted from your template):
```
export LD_LIBRARY_PATH=/usr/local/lib/R/lib
export RSTUDIO_PASSWORD=test

# PAM auth helper used by RStudio
# NOTE: '/bin/auth' not available, so using a similar one (?) in rstudio bin
export RSTUDIO_AUTH="/usr/lib/rstudio-server/bin/pam-helper"

# Generate an `rsession` wrapper script
export RSESSION_WRAPPER_FILE="${PWD}/rsession.sh"
(
umask 077
sed 's/^ \{2\}//' > "${RSESSION_WRAPPER_FILE}" << EOL
  #!/usr/bin/env bash
  # Log all output from this script
  export RSESSION_LOG_FILE="${RSTUDIO_SINGULARITY_HOST_MNT}${PWD}/rsession.log"
  exec &>>"\${RSESSION_LOG_FILE}"
  # Launch the original command
  echo "Launching rsession..."
  set -x
  exec rsession --r-libs-user "${R_LIBS_USER}" "\${@}"
EOL
)
chmod 700 "${RSESSION_WRAPPER_FILE}"

/usr/lib/rstudio-server/bin/rserver --www-port 8383 \
 --auth-none 0 \
 --auth-pam-helper-path "${RSTUDIO_AUTH}" \
 --auth-encrypt-password 0 \
 --rsession-path "${RSESSION_WRAPPER_FILE}"
```

Now when I try to access the server, I get to the login page, but I cannot login using my user-name + the 'generated' password ('test'). Error message is "**Error: Incorrect or invalid username/password**"

Maybe I am just missing something obvious and this *should* work?
Also, do I need to provide a different username to Rstudio for this setup?

Since I'm not an expert with charliecloud, maybe @reidpr can figure something out using your information?

Thanks again!

**Comment by johrstrom** [comment]
It could be the `RSTUDIO_AUTH`.  We provide [this very simple script](https://github.com/OSC/bc_osc_rstudio_server/blob/master/template/bin/auth).  Looks like what you're using is something rstudio provides? And likely doesn't recognize the `RSTUDIO_PASSWORD` env variable.

**Comment by jhawe** [comment]
Indeed, I missed that you are providing your very own authentication script, and using your approach I now got it to work, which is fantastic, **thank you so much for your input!!** 
I believe our institute should be able to work with this approach.

> For my understanding: Generally, you *completely* circumvent the standard Unix authentication procedure by supplying the custom script, is that correct?

I'd have two more questions if you got the time:

1) In my case I had to remove the RSESSION_WRAPPER_FILE. Can you please enlighten me as to why this part was necessary for you? Am I likely to run into problems by not implementing this part (e.g. was it maybe necessary to avoid the secure-cookie-key file)?

2) I am now planning to generate a random password hash anytime the server is started and print it to the user starting the server, thus only the user is able to authenticate and does not have to hardcode a password e.g. in the dockerfile used to create the image. 
Do you think this is a valid strategy? I believe you are doing something similar?

Thanks you so much again!

@reidpr I'm thinking that this solution suffices and is secure enough to use Rstudio server with charliecloud on HPC environments. Though one might want to think about whether it's possible to use the default Unix authentication to make it even easier for the user, I don't think this is absolutely necessary. What do you think?

**Comment by johrstrom** [comment]
> 1. In my case I had to remove the RSESSION_WRAPPER_FILE

It was before my time but it looks like running [multiple R sessions](https://github.com/OSC/bc_osc_rstudio_server/issues/1)? I can't be completely sure. 

> 2. I am now planning to generate a random password hash anytime

Yes this is what we do (we write it to a file in the job directory) but it's transparent to the user. That is, yes you shouldn't hard code it (there'd be little point in using a hardcoded password right?) but also make it as easy as possible for the user however you present this information to them. In our case, they don't even know there is a password, they just click through the open ondemand portal and it works.

**Comment by jhawe** [comment]
gotcha, thanks for you thoughts! 
the ondemand portal sounds interesting, however, for our current purpose and strategy we'll just supply the user with the password so he can login on his own.

thanks again!

**Comment by reidpr** [comment]
@johrstrom, @jhawe: Fabulous that this worked out! It seems that this issue can be closed? If not, please do not hesitate to re-open.

We do want to follow up; see the new issue linked above.

**Comment by jhawe** [comment]
For documentations sake, I created a small github repo with a working version of the dockerfile +script:
https://github.com/jhawe/rstudio-charliecloud/

**Comment by jhawe** [comment]
I just wanted to suggest to close it :) thanks for your support!
