### ISSUE TITLE
Make tests work with bats-core 

### ISSUE THREAD

**Issue by reidpr** [hpc/charliecloud#582]

**Comment by rstyd** [comment]
Just ran the standard test-suite with bats-core. The `build` tests run fine, but there are 9 failures in the `run` tests. 

Here's one failure:
```
 ✗ filesystem permission enforcement
   (in test file run/ch-run_uidgid.bats, line 57)
     `ch-run --no-home --private-tmp \' failed
   no ID arguments

   verifying: /var/tmp/pass
   ch-run[25930]: can't bind: not found: /var/tmp/pass (charliecloud.c:118)
```

It looks like it would take a good bit of work to get the tests passing bats-core.
