### ISSUE TITLE
ch-grow: add internal repository puller/unpacker

### ISSUE THREAD

**Issue by reidpr** [hpc/charliecloud#587]
It turns out that skopeo and umoci are kind of a PITA. Currently we use them for pulling an image from a repository (skopeo) and flattening it (umoci). How hard would it be to instead implement this in Python?

**Comment by reidpr** [comment]
@j-ogas reports: "I have a statically compiled skopeo.... Unfortunately, full scope tests do not pass with it."

**Comment by reidpr** [comment]
Is there a Python library already? @mej recalls one. @rstyd will look into this.

**Comment by j-ogas** [comment]
I'd add that compiling a building a pure Go (static) binary disables devicemapper, btrfs, and gpgme. I'm sure this has something to do with the test suite failures.
