### ISSUE TITLE
writeable images via overlayfs?

### ISSUE THREAD

**Issue by flying-sheep** [hpc/charliecloud#592]
Hi, I wondered if it’s possible to get charliecloud to have the advantages of `docker run`, namely:

1. A *clean* container within <½ second
2. The whole file system is modifiable, but changes are ephemeral
3. Mounts are possible everywhere for permanent IO

As far as I can see, the current state has two alternatives that both have their trade-offs:

1. `*2dir`: We get a clean container directory, but have to have to wait minutes and pay heavy IO costs.
2. `2squash` & `ch-mount`: We get a clean (because immutable) container file system, but the read-only file system isn’t flexible

I feel like having all that Docker has is not far off, because we could create an ephemeral rw-layer over a SquashFS base using OverlayFS, right?

Now please tell me what I missed, walking in here all starry-eyed and naive :smile:

**Comment by reidpr** [comment]
Hello @flying-sheep, thanks for your question.

The reason that we don't have a writable overlay option is that overlayfs plus unprivileged user namespaces is not available on most distributions (Ubuntu is the only major distro that has it, last time I checked), and a core principle of Charliecloud is to remain fully unprivileged throughout the workflow.

This issue has come up for us in the context of injecting GPU and MPI drivers; see issue #286. Our planned solution is symlink tricks and a tmpfs, but that doesn't scale to every directory in the image.

All that said, your item 3 is the case now, depending on the precise definition of "everywhere"; you just need to identify where you want to write and mount a writeable directory there with `ch-run --bind`. The mount point will need to already exist. This is less convenient and doesn't always work, but when it does, it does encourage a more disciplined workflow.

You could also add the overlayfs yourself, if you are willing to run a privileged helper first (i.e., after `ch-tar2dir` or `ch-mount` but before `ch-run`). If you try this, we'd be happy to include your helper in a contrib directory.

**Comment by flying-sheep** [comment]
Thank you for the detailed answer. Seems like a lot of people have thought about this and it’s not trivial: https://rootlesscontaine.rs/

It seems that fuse-overlayfs exists: https://github.com/containers/fuse-overlayfs

**Comment by reidpr** [comment]
Yes, we've been looking at fuse-overlayfs with some interest. IIRC it requires a 4.18 kernel, which is pretty new, so we can't require it for everything. But, if there's enough demand, we could add some optional modes.

**Comment by reidpr** [comment]
Looks like this question is answered, so closing. Please re-open if that's not true!
