### ISSUE TITLE
turn off maintainer mode

### ISSUE THREAD

**Issue by reidpr** [hpc/charliecloud#595]
Currently, we use the default Autotools "maintainer mode" setting, which I believe is enabled. The practical consequence, AFAICT, is that `configure` gets re-run at weird times, and we can't put `make clean` in `autogen.sh`.

This behavior makes me nervous; I feel we should disable maintainer mode by default with `AM_MAINTAINER_MODE([disable])` in `configure.ac`. However, I couldn't find an obvious consensus immediately on the interwebs.

So, this issue is to figure out what to do and do it.

Follow-up to PR #589.

**Comment by reidpr** [comment]
Bottom line for me: Maintainer mode has (1) never re-build the build system in a situation where I felt it helped, but (2) fairly regularly re-builds at surprising times.

I don't 100% know why I wrote that one can't put `make clean` in `autogen.sh` with maintainer mode enabled. It seems to work OK in a brief test; there must be more to the problem than its simple presence. But I definitely feel `make clean` should just clean everything up, without rebuilding the build system.

I did a little more googling where I wrote down the results. This also did not reveal a consensus.

Pro-maintainer mode:

* [Automake docs](https://www.gnu.org/software/automake/manual/html_node/maintainer_002dmode.html), unsurprisingly
* [a lowercase mainfesto](https://blogs.gnome.org/desrt/2011/09/08/am_maintainer_mode-is-not-cool/) blog post

Anti-maintainer mode:

* [Flameeyes’ blog](https://flameeyes.blog/2008/06/13/maintaner-mode/)
* [Muddle docs](https://muddle.readthedocs.io/en/latest/autotools.html#muddle-won-t-pull-because-files-have-changed)
* [Geoff Wozniak’s blog](https://wozniak.ca/blog/2019/01/10/1/index.html)

Unclear:

* [Autotools Mythbuster](https://autotools.io/automake/maintainer.html), also by Flameeyes interestingly

**Comment by reidpr** [comment]
@olifre @lnussbaum @wiene @ana, do packagers care about this? And if so, is the presence of `./configure --enable-maintainer-mode` sufficient?

**Comment by reidpr** [comment]
Discussion with a colleague and a night's sleep clarified my annoyance with `make clean` et al. rebuilding the build system. When I do some flavor of clean, I want to remove what is currently there, not what *would have been there* had I built with a not-yet-existing build system.

**Comment by olifre** [comment]
@reidpr I agree with your conclusion, also after thinking about this for a bit. Essentially, Flameeyes is much more experienced in Gentoo packaging than I am, but while I think he did not formulate it as clearly, he essentially advices to disable maintainer mode at least for releases — and packagers who may need to patch downstream for some projects should in any case take care of rebuilding the build system if needed, and should not rely on maintainer mode nor keep it active when packaging. 

And my personal opinion matches yours: I also would not want maintainer mode during development, at least not by default. 
So all in all: :+1:
