### ISSUE TITLE
ch-test: allow execution of individual files

### ISSUE THREAD

**Issue by reidpr** [hpc/charliecloud#607]
It would be nice if we could use `ch-test` to execute individual `.bats` files ~~or even individual tests~~. Currently the man page advertises this as a not-yet-implemented scope. Possible UI:

```
$ ch-test ./examples/hello/test.bats
```

~~or~~

```
$ ch-test './build.bats:lint shell scripts'
```

~~The latter form maybe should imply full scope, since if the user is going to the trouble of requesting a specific test, they probably want to run it even if the (perhaps unstated) scope argument says otherwise.~~

**Comment by CalvinDSeamons** [comment]
I do like the idea of running `ch-test` and then point to a specific file (straight to the point). The other option I thought was to following the scope command. 
```console
$ ch-test -scope singleton ./example/hello/test/bats
```
This way I feel mitigates the confusion around a user selecting `--scope full` on top of trying to choose just a single test.

**Comment by reidpr** [comment]
I think the UI would be simpler if specifying an individual test just implied `--scope full`.

I don't think specifying a `.bats` file should imply anything about scope, because files can be mixed. Though, we will want to do something intelligent if none of the tests in that file are in scope.

**Comment by reidpr** [comment]
Scope change. This issue is for individual files; #703 is for individual tests.
