### ISSUE TITLE
Manual install not working

### ISSUE THREAD

**Issue by audreystott** [hpc/charliecloud#609]
Hi all, I cloned the repository and tried to build Charliecloud on Ubuntu 18.04 as root, by following [this](https://hpc.github.io/charliecloud/install.html#manual-build-and-install), but am getting an error message when I run make: 
`make: *** No targets specified and no makefile found.  Stop.` I am guessing it's because the file is not a Makefile but a Makefile.am. Am I missing something here? Thank you.

**Comment by reidpr** [comment]
Hi, your guess is correct. We overhauled the build procedure for 0.13, out soon; it's now Autotools-based. You need to run `./autogen.sh`. The new docs are not yet on the web, but you can see the un-rendered versions in `doc`.

Does that help? I apologize for the confusion.

**Comment by audreystott** [comment]
Thank you Reid. I did `apt-get install autoconf` and installed all the prompted suggested packages (without them it won't work). Then ran `./autogen.sh`, `./configure,` `make` and `make install`. And it's installed now. Thank you!

**Comment by reidpr** [comment]
Great! I'm glad it worked out, and thanks for your patience with the documentation mismatch.

This issue seems resolved, but please re-open if I'm wrong, and let us know what further questions you have.
