### ISSUE TITLE
ch-test sudo check

### ISSUE THREAD

**Issue by CalvinDSeamons** [hpc/charliecloud#610]
From a user perspective (without access to sudo) the test suite can be a bit problematic. Mainly, there is a lot of waiting for `[sudo] password for $USER` to timeout so the tests can continue. 

My first suggestion is an enhancement for ch-test that would check for a docker group. On Bieber I have group access to Docker but the test still prompts me for a sudo password.

```console
[calvin@biebz charliecloud]$ ch-test --scope full
ch-test version 0.12

ch-run: 0.12 /home/calvin/git/charliecloud/bin/ch-run
bats:   0.4.0 /usr/bin/bats
tests:  /home/calvin/git/charliecloud/test

phase:                build run examples
scope:                full (command line)
builder:              docker (default)
use generic sudo:     no (default)
unpacked images dir:  /var/tmp/images/ (environment)
packed images dir:    /var/tmp/tarballs/ (environment)
fs permissions dirs:  skip (default)

checking namespaces ...
ok

checking builder ...
[sudo] password for calvin: 
```
Another way to address this issue is would be checking for sudo with `sudo -v` and then echoing `$?`. This won't trigger the password, but I'm unsure of its reliability.

**Comment by reidpr** [comment]
Interesting. I think you've found a usability bug.

The Travis tests, I thought, ran a non-sudo test. Would you look over that test, make sure it is real, and figure out how it doesn't catch your situation?

We do assume that using Docker requires sudo, and there's no support for the docker group configuration. We could look into changing that.

**Comment by CalvinDSeamons** [comment]
Being added into `sudo docker` resolves the issues for the user. This needs to be addressed later if a user cannot be given sudo.

**Comment by reidpr** [comment]
I'm pretty sure this bug is stale.
