### ISSUE TITLE
change spark dir from home to BATS_TMP?

### ISSUE THREAD

**Issue by j-ogas** [hpc/charliecloud#637]
Can we move the spark dir away from home?

```
spark_dir=~/ch-spark-test.tmp  # runs before each test, so no mktemp
```

**Comment by reidpr** [comment]
I think maybe it needs to be at a path shared between all the workers? But, there's no fundamental reason it needs to be in the home directory. I also don't recall if it needs shared writing, or if copying it to all the nodes would be OK.

**Comment by reidpr** [comment]
Point being, proceed with putting in a better place if you think that's best.
