### ISSUE TITLE
user+mount namespaces check always fails in chroots

### ISSUE THREAD

**Issue by wiene** [hpc/charliecloud#638]
The user+mount namespaces check as implemented in the [`configure.ac` file](https://github.com/hpc/charliecloud/blob/master/configure.ac#L279-L288) always fails if run in a chroot environment. Such setups are common to ensure a clean build environment. According to the [`unshare` man page](http://man7.org/linux/man-pages/man2/unshare.2.html), `unshare` always throws an EPERM error in this case:

>        EPERM (since Linux 3.9)
>              CLONE_NEWUSER was specified in flags and the caller is in a
>              chroot environment (i.e., the caller's root directory does not
>              match the root directory of the mount namespace in which it
>              resides).

**Comment by reidpr** [comment]
Thanks Peter, good catch.

Off the top of my head, it's not clear what to do about it. The man page quotation above seems to imply that user namespaces simply cannot be created within a chroot, i.e., it would be impossible to fix the check.

That said, the check is informational only; `configure` doesn't make any decisions based on it. So we could simply document the flaw to clarify this issue.

What is your opinion?

**Comment by reidpr** [comment]
Check that: it looks like we could [test if we're in a chroot](https://unix.stackexchange.com/questions/14345) and have the check warn about false negatives or something like that.

**Comment by wiene** [comment]
I like your proposals:
1. Mention this issue in the documentation.
2. Add an extra check which prints a warning if the build runs in a chroot.

**Comment by reidpr** [comment]
Great! We'll do that.
