### ISSUE TITLE
ObsPy test doesn't work any more

### ISSUE THREAD

**Issue by reidpr** [hpc/charliecloud#64]
The ObsPy test stopped working on about 10/31/2017 with the following error:

     pkg_resources.DistributionNotFound: The 'pytz' distribution was not found and is required by matplotlib

I couldn't figure out how to fix it on short notice, so I disabled it for now.

As an aside, this also reduced the Travis run time from 16–20 minutes to 5–6 minutes. I'm not sure this is a good use of test wall time. Perhaps the test can be shortened before returning it to service.

See also: obspy/obspy#1660

**Comment by reidpr** [comment]
@jkmacc-LANL, maybe you have some insight on this?

**Comment by jkmacc-LANL** [comment]
ObsPy has made some changes in its matplotlib version, but I’m not sure on this.  I’ll look into it...

**Comment by jkmacc-LANL** [comment]
Are these tests still running ObsPy 1.0.2? It's hard for me to tell.  1.1.0 was just released, and I wonder if it is either causing or may alleviate problems.

**Comment by reidpr** [comment]
Yes, still 1.0.2. I agree updating to 1.1.0 is probably appropriate.

I recall updating to 1.1.0 in an attempt to fix this, but I ran into a problem that I don't recall and gave up quickly because I didn't have much time. It was probably not a complicated issue, esp. for someone familiar with ObsPy.

**Comment by jkmacc-LANL** [comment]
Happy to help debug.  It's hard to see the ObsPy errors in the builds in Travis.  Could you post a link?

**Comment by reidpr** [comment]
For example, scroll down to the bottom of this: https://travis-ci.org/hpc/charliecloud/jobs/295030747

I don't recall if this was reproducible locally, but the procedure to do so would be to remove the `.skipped` from the ObsPy test files, then something like:

```
$ cd test
$ make test-build
$ cd ../examples/serial/obspy
$ ../../../test/bats test.bats
```
