### ISSUE TITLE
docs do not build in parallel

### ISSUE THREAD

**Issue by Trophime** [hpc/charliecloud#643]
Hi,
trying to upgrade the charliecloud package for Debian I run into this error:
```
configure.ac:35: error: possibly undefined macro: AC_MSG_ERROR
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:51: error: possibly undefined macro: AC_SUBST
configure.ac:66: error: possibly undefined macro: AC_MSG_RESULT
configure.ac:119: error: possibly undefined macro: AS_UNSET
autoreconf: /usr/bin/autoconf failed with exit status: 1
```

**Comment by wiene** [comment]
I think this happens if the `autoconf-archive` package is missing.

**Comment by Trophime** [comment]
Thanks it help but now I've got this error:
```
cat ../config.log | ./make-deps-overview > _deps.rst
make[3]: *** No rule to make target 'html/searchindex.js', needed by 'all-am'.  Stop.
make[3]: *** Waiting for unfinished jobs....
make[3]: Leaving directory '/build/charliecloud-0.13/doc'
make[2]: *** [Makefile:387: all-recursive] Error 1
make[2]: Leaving directory '/build/charliecloud-0.13'
dh_auto_build: make -j8 returned exit code 2
```

**Comment by reidpr** [comment]
Thanks @Trophime, really pleased to hear that.

Is there somewhere we can see the complete build log, including configure output?

**Comment by Trophime** [comment]
What is called:
```
```
	./configure --build=x86_64-linux-gnu --prefix=/usr --includedir=\${prefix}/include --mandir=\${prefix}/share/man --infodir=\${prefix}/share/info --sysconfdir=/etc --localstatedir=/var --disable-silent-rules --libdir=\${prefix}/lib/x86_64-linux-gnu --runstatedir=/run --disable-maintainer-mode --disable-dependency-tracking
```
[charliecloud_0.13-1_amd64.build.log](https://github.com/hpc/charliecloud/files/4199275/charliecloud_0.13-1_amd64.build.log)

**Comment by reidpr** [comment]
Thank you @trophime! We will take a look. I develop on a Buster box, so I'll see if I can reproduce the issue.

**Comment by reidpr** [comment]
p.s. I reformatted your comment a little for clarity.

**Comment by Trophime** [comment]
I think I have found the issue.
To reproduce the problem:

make -j 2 -C libexec
make -j 2 -C doc

In other words, the build needs to be done in sequential mode since doc does not support parallel build. The default in debian is to build in parallel...

**Comment by reidpr** [comment]
Fantastic, thank you. We will look into fixing the Makefiles to disallow parallel build where it doesn't work. (`doc` is the messiest subdirectory build-wise IIRC.)

**Comment by olifre** [comment]
This also affects Gentoo. According to packaging docs:
https://devmanual.gentoo.org/ebuild-writing/functions/src_compile/building/index.html
`make -j1` should be considered the last possible solution. Maybe we can identify what's breaking the parallelization and fix it, or does Sphinx itself cause the issue?
