### ISSUE TITLE
documented dependencies should mention ShellCheck

### ISSUE THREAD

**Issue by rstyd** [hpc/charliecloud#645]
I noticed the Contributor's Guide doesn't mention ShellCheck. It should list ShellCheck as a development dependency  and state which version we require. Installation instructions are located at https://github.com/koalaman/shellcheck/tree/v0.7.0#installing.

**Comment by reidpr** [comment]
This should go in configure, since it's needed to run the complete test suite, and also the installation instructions so we can provide a link. It's a bit hidden how to find the static binary.
