### ISSUE TITLE
several files in libexec are erroneously executable

### ISSUE THREAD

**Issue by wiene** [hpc/charliecloud#648]
Charliecloud installs various files marked as executables (e. g. `base.sh` or `version.*`) although those files do not contain shebang lines (and are not binaries either). This is an unusual combination which triggers warnings when using lint tools. I would suggest to remove the executable bit for those files.

**Comment by reidpr** [comment]
Yes, that's definitely a mistake. The reason is that was how we were able to persuade Autotools to install them. If you or anyone has better ideas, I'm all ears. :) Related issue is #596.

**Comment by j-ogas** [comment]
This will important for the updated Fedora package. However, I can always change their permissions in the spec file.
