### ISSUE TITLE
ch-image pull: include metadata

### ISSUE THREAD

**Issue by reidpr** [hpc/charliecloud#651]
Follow-up to PR #616. Currently, `ch-image` does not fetch Docker metadata, so things like `ENV` statements in base images are lost. We should have parity with metadata recorded during Dockerfile build.

See also issue #276.

**Comment by ajyounge** [comment]
Having ENV is important, and we're seeing more use of LABEL metadata that could have valuable future use cases with image specialization. Also, does this help with architecture detection (eg: pulling x86_64 or aarc64 images automatically)?

**Comment by reidpr** [comment]
> Also, does this help with architecture detection (eg: pulling x86_64 or aarc64 images automatically)?

No, but see PR #865.
