### ISSUE TITLE
test: remove /bin/true tests

### ISSUE THREAD

**Issue by reidpr** [hpc/charliecloud#653]
Currently, we test all test images with `ch run ... -- /bin/true`. These have never failed and consume testing time, and inability to run will be caught because `ch-run` is used everywhere in the test suite, so let's remove them.

**Comment by j-ogas** [comment]
Do we want any of the other logic in `test/make-auto.d/run_image.bats.in`?

**Comment by reidpr** [comment]
I'm not sure if we test `ch-mount` and `ch-umount` anywhere else. But, maybe `unpack.bats.in` should be changed to mount or unpack depending on the format, and we add an unmount step at the end.

Also `unmount.bats.in` has an unnecessary `if [[ -n $ch_multinode ]]` in it.
