### ISSUE TITLE
/test/dev_proc_sys.py fails on kernels built without CONFIG_STRICT_DEVMEM=y

### ISSUE THREAD

**Issue by heasterday** [hpc/charliecloud#677]
It appears when a REHL7/CentOS7 system with a recent kernel (4.x) is built without `CONFIG_STRICT_DEVMEM=y` then `/dev/mem` is not present which is tested by `dev_proc_sys.py` leading to test failure.

```
 ✗ /dev /proc /sys
   (in test file run/ch-run_uidgid.bats, line 49)
     `ch-run $uid_args $gid_args "$ch_timg" -- /test/dev_proc_sys.py' failed
   no ID arguments
   
   ERROR	/dev/mem: exception: [Errno 2] No such file or directory: '/dev/mem'
   SAFE	/proc/kcore: read not allowed
   SAFE	/sys/kernel/mm/page_idle/bitmap: read not allowed
```

Relevant: http://man7.org/linux/man-pages/man4/mem.4.html

**Comment by heasterday** [comment]
It's worth noting both of the systems presenting the issue are aarch64.

**Comment by reidpr** [comment]
Good find.

Can you figure out an alternate device that unprivileged users shouldn't be able to read? Ideally it would be broadly available and could simply replace `/dev/mem`, but if we have to try more than one, it's OK too.

**Comment by heasterday** [comment]
@reidpr the device `/dev/cpu_dma_latency` looks like a decent candidate to me. This device is part of the [power management quality of service framework](https://www.kernel.org/doc/html/v5.0/admin-guide/pm/cpuidle.html) in the linux kernel, appears to be ubiquitous, and requires privilege to access. 

I think trying `/dev/mem` and if it is not found `/dev/cpu_dma_latency` like what is done with the `/proc` test should resolve this.

**Comment by reidpr** [comment]
Sounds good to me.
