### ISSUE TITLE
don't hard-code path to Python and sh libraries

### ISSUE THREAD

**Issue by ana** [hpc/charliecloud#683]
Hi,

After the build system rewrite, several ch-* scripts and base.sh have harcoded the path `../libexec/charliecloud`.  This wants to create `/usr/libexec/charliecloud` but `/usr/libexec`  is not a standard directory in the Filesystem Hierarchy Standard.
I have patched this directly for openSUSE, please see: https://build.opensuse.org/package/view_file/network:cluster/charliecloud/0001-Replace-hardcoded-libexec.patch?expand=1
This will be also problematic for Debian.

However, I think a variable in the buildsystem so the path can be chosen would be a better solution for this. There was a previous discussion in this issue https://github.com/hpc/charliecloud/issues/93

**Comment by reidpr** [comment]
Hello Ana, thanks for the report. We'll look into it.

We do know that a lot, but not all, of the stuff currently in `libexec` needs to be moved to `lib`; see issue #596. The current state also causes problems with Autocools; see issue #648. Looking at your patch, this move alone may address your immediate concern.

A couple of constraints that are relevant:

1. We want to keep Charliecloud working when built in the source directory, without install. I'm not sure how to do a build system variable and keep this; have I missed something?
2. Fedora/CentOS/Red Hat *insists* on certain things going in `libexec`; e.g., we got a lot of blowback trying to put the test suite in `doc`.

**Comment by reidpr** [comment]
Looks like `/usr/libexec` is in [FHS 3.0](https://refspecs.linuxfoundation.org/FHS_3.0/fhs-3.0.html#usrlibexec) but not 2.3. Debian policy manual says the project [follows FHS 3.0](https://www.debian.org/doc/debian-policy/ch-opersys.html#file-system-hierarchy), but you know better — what am I missing?

**Comment by ana** [comment]
Hi @reidpr 

Indeed, after checking the Debian policy and also some Debian tools (lintian, debhelper, etc), you can use `/usr/libexec` without problems from a few months before the release of buster.

I'm afraid this is still not the case in openSUSE/SUSE, where it's still FHS 2.3: https://build.opensuse.org/package/show/Base:System/fhs

In any case, paths shouldn't be hard coded and given you're using autotools I've have expected I could have used the parameter `--libexecdir=$PREFIX/lib` to use `usr/lib` instead of `usr/libexec` without more changes. But this didn't work because the ch-* script have hard coded 
 `../libexec/charliecloud`

About the variable I meant something similar to what you were doing now, I was using `%make_install PREFIX=%{_prefix} LIBEXEC_DIR=lib/charliecloud` to install files under `usr/lib` instead of `usr/libexec`.
See: https://build.opensuse.org/request/show/781878#n29

**Comment by reidpr** [comment]
Thank you @ana. I am convinced that we should use a variable (it would also eliminate the `lib/charliecloud` symlink kludge), so this issue should stay open. However, I still don't know how to do this while still meeting our goal that the scripts should still work in the build directory, before install. I will noodle on it, but any suggestions would be most welcome.

Note that with the merge of PR #685, the hard-coded path will be `lib` instead of `libexec`.

**Comment by reidpr** [comment]
This popped up again as part of the problems in #947.
