### ISSUE TITLE
ch-grow: add --list to list images

### ISSUE THREAD

**Issue by rstyd** [hpc/charliecloud#696]
Currently, there is no way for users to see what images they've built with ch-grow besides `ls $CH_GROW_STORAGE`. I propose we add a flag to ch-grow that shows this and some relevant metadata similar to `docker images` and `buildah images`.

**Comment by j-ogas** [comment]
I wonder if a `list` or `show` command would be more clear?

For example:
```
$ ch-grow list dl-cache
[...]
$ ch-grow list images
```

**Comment by rstyd** [comment]
Yeah, that definitely adds clarity. I was thinking `images` since that seems to be what people would expect from other builders.

**Comment by rstyd** [comment]
@reidpr How you feel about `ch-grow images` vs `ch-grow list images`?

**Comment by reidpr** [comment]
1. We could just do both.
2. Is `docker list` a thing?

**Comment by rstyd** [comment]
1. We could. I'm personally of the opinion that there should generally be one suggested way to do something to keep the UI straightforward. 
2. Docker has `docker image`, `docker image list`, and `docker image ls` which as far as I can tell all give the same result.

**Comment by reidpr** [comment]
I think `list` is more clear than `images` personally. If we picked only one, I'd vote for that.
