### ISSUE TITLE
Tutorial example lacks "hello" directory ?

### ISSUE THREAD

**Issue by quellyn** [hpc/charliecloud#70]
Minor nitpick:

https://hpc.github.io/charliecloud/tutorial.html#share-image-and-other-standard-docker-stuff

When I run the hello example run using Docker as shown: 
sudo docker run -it hello /bin/bash

And then "ls /" I see a "hello" directory:

root@28368f1cb44e:/# ls
bin   dev  hello  lib	 media	opt   root  sbin  sys  usr
boot  etc  home   lib64  mnt	proc  run   srv   tmp  var

The example in the Tutorial doesn't have this directory.

Q

**Comment by reidpr** [comment]
@quellyn, if you can take this on, that would be wonderful. I can help walk you through building the docs and committing the change if you like.

**Comment by quellyn** [comment]
Sure, I’ll give it a whirl!

Q
