### ISSUE TITLE
Respecting all ENV settings?

### ISSUE THREAD

**Issue by tylerjereddy** [hpc/charliecloud#719]
I'm guessing this may be related to Charliecloud providing less "host isolation" than Docker, but I'm nonetheless slightly surprised that there is no warning/error related to overriding `ENV` settings in `Dockerfile`, since they are [documented in this way](https://docs.docker.com/engine/reference/builder/#env):

> The environment variables set using ENV will persist when a container is run from the resulting image. 

In particular, I set `ENV HOME=/tyler` and I expect this to persist so that activation of an interactive container with `--no-home` will allow for automatic sourcing/loading of spack packages/modules, etc. at an appropriate path to the `~/.bashrc`, independent of the user running the container.

It seems that Charliecloud is actually lifting the `$HOME` from the host? Do you have recommended way to do this differently?

What if I tried using [`USER`](https://docs.docker.com/engine/reference/builder/#user) in the `Dockerfile`?

Is that actually going to set as documented below, given the namespace details of Charliecloud operation?

> The USER instruction sets the user name (or UID) and optionally the user group (or GID) to use when running the image

The broader motivation here is to reduce the bifurcation in workflows between Docker and Charliecloud to the extent reasonable for developers. Is it crazy to try to use the same Dockerfile for both?

**Comment by reidpr** [comment]
Hello @tylerjereddy, is `ch-run --set-env` what you want? The [`ch-run` man page](https://hpc.github.io/charliecloud/command-usage.html#environment-variables) has a section on handling environment variables.

**Comment by tylerjereddy** [comment]
Ideally, what I'd like is for `printenv` inside the Charliecloud image to match the behavior documented for `ENV` in the Dockerfile reference; i.e., environment variable behavior parity with the Docker runtime.

It looks like manual intervention from the user is needed on a case-by-case basis for the variable setting in Charliecloud, or possibly through a file that Charliecloud stores somewhere?

The docs show:

> The purpose of --set-env=FILE is to set environment variables that cannot be inherited from the host shell, e.g. Dockerfile ENV directives

Why can't we inherit from those directives like the Docker runtime can? Is Docker using some format that can't be read easily or?

**Comment by reidpr** [comment]
Does `ch-run --set-env $IMG/ch/environment $IMG -- ...` not do what you want?

Yes, it is reasonable to use the same Dockerfile with both Docker and Charliecloud, and we want to make it so Charliecloud can most of the important things Docker can do. However, keep in mind that Charliecloud is a lightweight container runtime; it is not a re-implementation of Docker. So, some things will be different.

In particular, environment variables are a tricky area. We've designed it the way we have for specific reasons, though of course there are probably some mistakes.

**Comment by tylerjereddy** [comment]
Looks close to working yeah--only problem now is that my `ENV` settings sometimes point to paths that do not exist in the image on the assumption I will mount there (a specific clean working directory where a repo ends up bind mounted). I guess a reasonable compromise there is just to create that path in the Dockerfile so Charliecloud can bind mount to it and have PATH working without user intervention.

Maybe I'm surprised by the separation of the variables like that. I guess Docker just points to a config file hidden somewhere too though, maybe. I just never noticed I guess.

**Comment by reidpr** [comment]
Re. your workaround, we hope to fix that in issue #96, which you also commented on.

I think maybe your full incantation might be something like:

```
$ ch-run --no-home --unset-env='*' --set-env $IMG/ch/environment $IMG -- ...
```

We could package up those three options (and maybe there are others) into a shorthand like `--builder-env`. Would that be helpful for your use case?

**Comment by tylerjereddy** [comment]
Hmm, it might be useful yeah. I should probably see what happens if/when people on the team start using the images before I suggest what we need though.

From my side, I'm already up and running on LANL HPC infrastructure with it so that's good. A few kinks to work out, but looks close to Docker workflow so far apart from needing to prevent some things leaking in from host.

My invocation is pretty similar to that; haven't used the `--unset-env`, but the rest is the same. Perhaps that will tidy up the remaining deviations from Docker behavior.

I haven't thought much yet about multi-node workflows and the inside vs. outside MPI calls--that will depend on what my team really needs I think, so the "leaking" of ENV variables may actually be needed in some of those cases I haven't thought through yet.

**Comment by reidpr** [comment]
It seems this question has been addressed?

**Comment by tylerjereddy** [comment]
Yeah, we have an incantation that works. It is a bit long maybe, but it works, thanks.
