### ISSUE TITLE
documentation: 404 when searching

### ISSUE THREAD

**Issue by j-ogas** [hpc/charliecloud#748]
I seem to reach a 404 file not found error when using the documentation search feature.

**Comment by rstyd** [comment]
Ah. Thanks! I mentioned this to Reid a while ago and forgot to add an issue.

**Comment by tbugfinder** [comment]
A working search would be really beneficial for users.

**Comment by reidpr** [comment]
See issue #822 for the specific trouble that @tbugfinder is having because (in part) they can't search.
