### ISSUE TITLE
ch-run[336112]: can't init user+mount namespaces

### ISSUE THREAD

**Issue by aruhela** [hpc/charliecloud#754]
Hi CharlieCloud Team,

I have been successful in running CharlieCloud inside a VirtualBox on my Laptop but see the following issue on the Frontera clusters. I was wondering if anyone has tried CharlieCloud on other clusters and how to resolve the issue.

frontera(1009)$  ch-run /var/tmp/hello -- /bin/bash
ch-run[330272]: can't init user+mount namespaces: Invalid argument (ch_core.c:358 22)

frontera(1011)$  ch-run -u 0 /var/tmp/hello -- /bin/bash
ch-run[336112]: can't init user+mount namespaces: Invalid argument (ch_core.c:358 22)

Thanks,
Amit

**Comment by reidpr** [comment]
Hello Amit, thanks for getting in touch & glad to hear of your interest in Charliecloud.

My initial guess would be that user namespaces are not configured. I looked a bit and it's not clear to me what OS Frontera uses.

I suggest you run Charliecloud's configure script and paste the report you get here. That will tell us what features are enabled. It's OK if you didn't build Charliecloud yourself or there is a different version installed; we just want the configure report. The steps will be something like:

```
$ wget https://github.com/hpc/charliecloud/releases/download/v0.16/charliecloud-0.16.tar.gz
$ tar xf charliecloud-0.16.tar.gz
$ cd charliecloud-0.16
$ ./configure
```

It will run some tests and then print out a report.

We would also be happy to work with the Frontera admins directly. They could e-mail me at reidpr@lanl.gov.

**Comment by aruhela** [comment]
Thanks, Reid

Please find the output of the configure command and other details in the attached file.  

[CharlieCloud_1.txt](https://github.com/hpc/charliecloud/files/4756075/CharlieCloud_1.txt)

Regards,
Amit

**Comment by aruhela** [comment]
Thanks Reid,

What is the safe/recommended value of this parameter to be set on a production cluster? Does it depend upon cores per node or the memory? Are you aware of any potential runtime/performance issues that may affect cluster operations?

Thanks,
Amit

**Comment by reidpr** [comment]
I am not aware of any specific recommendation. We just set it to be the same as the other namespaces, i.e., “many”. There should be no runtime or performance implications.

**Comment by aruhela** [comment]
I am able to verify the "hello-world" program on a test machine at Frontera Cluster and it has run fine. The only change that was required is to increase the value of max_user_namespaces(10000).

Let's hope to see it soon systemwide.

**Comment by reidpr** [comment]
Fantastic!

I am going to close this issue since it seems the question has been resolved, but please re-open it if I'm wrong or that turns out not to be true. Thanks again for reaching out to us!
