### ISSUE TITLE
Vagrantfile should install Virtualbox Guest Additions

### ISSUE THREAD

**Issue by rstyd** [hpc/charliecloud#755]
Currently, the Vagrantfile does not install the virtualbox guest additions. This is a usability issue since at least on my machine, the initial window is tiny making it difficult to set one's password on the appliance.

**Comment by reidpr** [comment]
It did install for me. Do we know why?

**Comment by rstyd** [comment]
I don't know. I'll find my Vagrantfile output for when it attempts to do that, and we can compare.

**Comment by reidpr** [comment]
Closing per removal of Vagrant support in #1204.
