### ISSUE TITLE
ch-grow: implement multi-stage build

### ISSUE THREAD

**Issue by reidpr** [hpc/charliecloud#768]

**Comment by trandles-lanl** [comment]
Rough estimate on release date? A resolution of month/year would be good for my purposes. Will PR #835 complete the work or is it only part of what's required?

**Comment by reidpr** [comment]
PR #835 will be in master within a few days and then 0.19; I'd expect September 2020. I would call it complete after that PR. There is a bug #833 which may be significant but I'd classify it as a bug rather than making the feature incomplete.
