### ISSUE TITLE
ch-grow: document a minimum version of lark-parser

### ISSUE THREAD

**Issue by j-ogas** [hpc/charliecloud#792]
We currently do not document a minimum version of lark-parser. 0.7.8 does not work.

**Comment by rstyd** [comment]
Agreed: the current minimum working version is `0.8.6`. In addition, we should add a check on the current lark-parser version to `configure.ac`. Currently, we just check if lark-parser exists on the system with `${have_lark}`. This was sufficient before `0.8.6` changed the instruction order.

**Comment by reidpr** [comment]
Last I checked 0.8.5 worked too. A binary search shouldn't be too hard.

**Comment by reidpr** [comment]
Distro packages:

* CentOS 7 has 0.7.1 via EPEL; CentOS 8 has 0.8.1 via EPEL.
* Debian Bullseye (test) has 0.8.6 and Sid (unstable) has 0.8.9; does not appear to be in any stable.
* Ubuntu Focal (20.04 LTS) has 0.8.1 and Groovy (20.10?) has 0.8.8.

**Comment by rstyd** [comment]
In that case, should we just suggest users acquire it via `pip`?

**Comment by reidpr** [comment]
Using `test/Dockerfile.argenv` and current master; `lark-parser` installed via `pip3`:

```
0.8.9  ok
0.8.8  ok
0.8.7  ok
0.8.6  ok
0.8.5  ok
0.8.4  ok
0.8.3  ok
0.8.2  ok
0.8.1  ok
0.8.0  ok
0.7.8  fail: no attribute 'visit_topdown'
```

**Comment by reidpr** [comment]
Same, but replace `visit_topdown()` with `visit()`:

```
0.8.9  fail: out of order
0.8.6  fail: out of order
0.8.5  ok
0.8.1  ok
0.8.0  ok
0.7.8  ok
0.7.7  ok
0.7.5  ok
0.7.4  ok
0.7.3  ok
0.7.2  ok
0.7.1  ok
```

**Comment by reidpr** [comment]
I propose we:

1. Document 0.7.1 as the minimum version.
2. Add a small monkey patch: if `lark.Visitor.visit_topdown()` does not exist, add it as an alias to `visit()`. Or we could just call `visit()` directly.

This would make it work with the `lark-parser` in EPEL7.

**Comment by rstyd** [comment]
I think those are both excellent ideas.
