### ISSUE TITLE
better error message with image tags containing upper-case letters

### ISSUE THREAD

**Issue by samuelkgutierrez** [hpc/charliecloud#794]
Hi,

I noticed this behavior when using master at 254fa07a2241ea0349179ea42471b1abdefafeea.

Given the following command:
`ch-build -b ch-grow -t CapName -f /home/samuel/devel/bueno/examples/build-n-run/Dockerfile.mpich /home/samuel/devel/bueno/examples/build-n-run`

I see the following error:
```
building with: ch-grow
error: image ref syntax, at end: CapName
```

May I suggest providing a nicer error message that points to the problematic tag name? I don't know if that's really the underlying problem here, but when I provide a tag name without capitalization (anywhere), things work as expected.

Thank you.

**Comment by reidpr** [comment]
Yeah, image names have to be lower case but I agree we could be clearer about it.

FWIW, gory details: https://hpc.github.io/charliecloud/faq.html#how-do-i-specify-an-image-reference
