### ISSUE TITLE
not able to add centos ius repo phpfpm7 while build nginx server

### ISSUE THREAD

**Issue by tiwariabhishek697** [hpc/charliecloud#803]
ERROR
![image](https://user-images.githubusercontent.com/47290000/87709891-97a55880-c7c2-11ea-949c-00ae3b461fdd.png)
DOCKERFILE
![image](https://user-images.githubusercontent.com/47290000/87709947-ac81ec00-c7c2-11ea-8926-96a3a1d3193c.png)
DOCKERFILE
![image](https://user-images.githubusercontent.com/47290000/87710005-c7ecf700-c7c2-11ea-8cb0-fb71277919e1.png)

**Comment by reidpr** [comment]
Thanks for getting in touch.

Can you please post the build command you used and attach the Dockerfiles as text files?

Thanks!

**Comment by tiwariabhishek697** [comment]
thanks for reaching so quickly. Command used to build image is "docker-compose build". Also i am using aws ec2 . 

FROM centos:7

RUN yum -y install openssh-server openssh-clients

RUN yum -y install passwd

RUN useradd remote_user && \
    echo "1234" | passwd remote_user  --stdin && \
    mkdir /home/remote_user/.ssh && \
    chmod 700 /home/remote_user/.ssh

COPY remote-key.pub /home/remote_user/.ssh/authorized_keys

RUN chown remote_user:remote_user   -R /home/remote_user && \
    chmod 600 /home/remote_user/.ssh/authorized_keys

RUN /usr/sbin/sshd-keygen

RUN yum -y install mysql
RUN yum -y install epel-release && \
    yum -y install python-pip && \
    pip install --upgrade pip && \
    pip install awscli

CMD /usr/sbin/sshd -D





FROM remote-host

COPY ./conf/nginx.repo /etc/yum.repos.d/nginx.repo

RUN                                                                          \
  yum -y install nginx-1.12.2 openssl --enablerepo=nginx                  && \
  curl -I https://centos7.iuscommunity.org/ius-release.rpm                 && \
  curl -I https://dl.iuscommunity.org/pub/ius/stable/CentOS/7/x86_64/ius-release                                                                                        -1.0-14.ius.centos7.noarch.rpm && \
  yum -y install                                                             \
    php71u-fpm                                                               \
    php71u-cli                                                               \
    php71u-mysqlnd                                                           \
    php71u-soap                                                              \
    php71u-xml                                                               \
    php71u-zip                                                               \
    php71u-json                                                              \
    php71u-mcrypt                                                            \
    php71u-mbstring                                                          \
    php71u-zip                                                               \
    php71u-gd                                                                \
     --enablerepo=ius && yum clean all

EXPOSE 80 443

VOLUME /var/www/html /var/log/nginx /var/log/php-fpm /var/lib/php-fpm

COPY ./conf/nginx.conf /etc/nginx/conf.d/default.conf

COPY ./bin/start.sh /start.sh

RUN chmod +x /start.sh

CMD /start.sh

**Comment by reidpr** [comment]
Great, thank you. It seems you are building with Docker directly, not the Charliecloud wrapper `ch-build`? I'm not yet understanding how Charliecloud fits in with this issue.

**Comment by reidpr** [comment]
Closing since this appears to be a Docker issue, not Charliecloud. Please re-open if I am wrong!
