### ISSUE TITLE
ch-run-oci: test fails with "unsupported OCI version: 1.0.2-dev"

### ISSUE THREAD

**Issue by heasterday** [hpc/charliecloud#813]
Looks like the OCI spec got a version bump that filtered downstream into buildah. [ch-run-oci](https://github.com/hpc/charliecloud/blob/master/bin/ch-run-oci.py.in#L25) is very strict on the supported version and is now failing.

**Comment by heasterday** [comment]
To provide more information this was noticed with a branch off of `master`  in PR #812 .

**Comment by reidpr** [comment]
Are there substantive changes, or should we just bump the version?

We could believe OCI's semantic versioning guarantees and put a max of 1.∞ or 1.0.∞ rather than 1.0.2-dev.

**Comment by rstyd** [comment]
@reidpr Running the test suite with the version of buildah used in the travis run. Just bumped `1.0.1` to `1.0.2`. Will report back when it's done.

**Comment by rstyd** [comment]
Everything appears to be in working order with the number bumped up to 1.0.2! I think changing the max to 1.0.∞ is the best option. There could possibly be some weird changes at 1.1.0.
