### ISSUE TITLE
add man pages

### ISSUE THREAD

**Issue by reidpr** [hpc/charliecloud#82]
@olifre in PR #59:

> Which approach would you take:
>
> 1. Automatic generation with help2man ( https://www.gnu.org/software/help2man/ ), which essentially works by calling the binaries with --help and --version adding some nice formatting,
> 2. hand-written full-fledged manpages (which may as well be based on help2manoutput to have a starting point, but need more love, e.g. example calls, maybe some FAQ etc., and manual adaptation for any newly added option)?

I think my preference would be for option 2, since I feel the `--help` output should be pretty concise (less than a screen) and hand-written man pages would let us say a bit more about the various nuances and trade-offs.

It would be nice if there were tests to verify that the same options were described in `--help` and the man page, and also frankly the code itself. But I don't think it's worth holding things up over that.

Do man pages need to be build before installing?

**Comment by olifre** [comment]
> Do man pages need to be build before installing?

Depends. You can hand-write them directly in the classic syntax, which is a bit arcane, see for example:
https://gist.github.com/olifre/ff35b108c9f6876cc7222046d3c1ca25
(it looks worse than it actually is, this is what `help2man` generates for `ch-run`)
Like that, they can be installed as-is, and you can even open them with `man` directly when specifing the full path to them. 
That is for sure the most lightweight solution, and means that in principle, they could be looked at even without any pre-processing or installation. 

Other options involve writing them in a different format and converting them to that format. 
For example, `rst2man` from `docutils` allows to write elaborate manpages, for example:
https://github.com/mpv-player/mpv/blob/master/DOCS/man/mpv.rst
I think also `sphinx-build` can build manpages.

**Comment by reidpr** [comment]
`sphinx-build` can output man pages.

This seems the way to go, since we already have ReST documentation (the web docs).
