### ISSUE TITLE
LD_PRELOAD and way to distinguish container environment

### ISSUE THREAD

**Issue by aruhela** [hpc/charliecloud#823]
Hi Charliecloud team,

I have two questions.

1. Does Charlieclud support following env variables or sth similar to these?
 SINGULARITYENV_LD_PRELOAD
 SINGULARITY_BINDPATH

1. How can I distinguish Charliecloud environment and the native non-container environment during runtime? Is there any file or env variable that is kept inside Charliecloud containers to find it?

Thanks.
Amit Ruhela

**Comment by reidpr** [comment]
Hello Amit, thanks for getting in touch.

Generally speaking, Charliecloud (`ch-run` specifically) tries to be as hands-off as possible regarding environment variables. Specifics are documented in the `ch-run` man page](https://hpc.github.io/charliecloud/command-usage.html#id32).

Re. Q1: No, Singularity environment variables are not supported. From what I've gathered incidentally, Singularity has extensive and complex environment manipulation capabilities, which isn't consistent with Charliecloud's minimalistic philosophy.

Re. Q2: There is currently no documented way to know if you are in a Charliecloud container. You could examine the `/ch` directory but that's likely to be brittle.

What is your use case? I can give better advice if I know what you are trying to do.

**Comment by aruhela** [comment]
Thanks, Reid,

Q1. We need to LD_PRELOAD a monitoring library for the submitted jobs.  Is there any recommended way to do so with Charliecloud containers? This need not require to have same environment variables as exposed by Singularity. 

Q2. The operations/functionality of the monitoring library is different when running with the container software. We, therefore, want to make sure whether the monitoring library is running with the default application-run or inside the container.

**Comment by reidpr** [comment]
Aha, fantastic!

Q1. Do the environment variable features above meet your needs (e.g., `--set-env` with a file, or possibly even Bash process substitution, `--set-env <(echo LD_PRELOAD=foo)`)?

Q2. For right now, you could use the same features to set an environment variable yourself. But, this seems to be a straightforward feature request, so I will create a new issue for that.

Does that help?

**Comment by aruhela** [comment]
Thanks Reid,

--set-env should be fine for our work.

Amit

**Comment by reidpr** [comment]
Great! I'll close this issue since it seems the question is answered. If I'm wrong, please do not hesitate to re-open.

**Comment by aruhela** [comment]
Hi Reid,

I am opening the ticket again as we can't force users to specify the "--set-env". We want something like SINGULARITY_BINDPATH that TACC administrators export when charliecloud module is loaded by users to bind mount certain directories that does the monitoring work. Users should be able to run their applications without manually specifying the --set-env or -b command. Right now, the containers fail to run as they import LD_PRELOAD from the outside environment and the library is not found inside the containers.  

Thanks
Amit
