### ISSUE TITLE
ch-image: add delete subcommand

### ISSUE THREAD

**Issue by rstyd** [hpc/charliecloud#838]
With the advent of ch-grow caching, we should provide a way for users to delete images. I suggest adding a `ch-grow --delete` command. 

Assuming we have an image named `image1`,  `ch-grow --delete image1` would delete that image. Getting this working with the ch-grow caching mechanism is going to take some thought. One simple solution would be to just kill the cache for all associated images, but that's a bit heavy handed. Another issue is how will users know what base image is associated with their images. See #837.

**Comment by reidpr** [comment]
I think this feature is a good idea.

As for the cache, IMO it would be best if we could just delete a reference and then let Git garbage-collect later.

**Comment by rstyd** [comment]
After thinking about this further, in practice as long as the image we're deleting isn't the _active_ image for a particular base image cache, I think we can just delete it no harm, no foul.
