### ISSUE TITLE
ch-run:  --cd is not persistent

### ISSUE THREAD

**Issue by pagrubel** [hpc/charliecloud#843]
For ch-run --cd  doesn't seem to be persistent, it seems to start in that directory and then reverts to the directory I ran it from
Here are a couple of examples:
```
ch-tar2dir /usr/projects/beedev/toss-tiny-3-5.tar /tmp
replacing existing image /tmp/toss-tiny-3-5
 276MiB 0:00:00 [==================================================================>] 100%            
/tmp/toss-tiny-3-5 unpacked ok
pagrubel@fg005 BEE_Private$ ch-run /tmp/toss-tiny-3-5 --cd /home/$USER -- pwd;pwd
/home/pagrubel
/users/pagrubel/BEE/BEE_Private
```
In the following example I was assuming the file would end up in my home directory.  Please explain if my assumption is incorrect.
```
pagrubel@fg005 BEE_Private$ ls hello.txt
ls: cannot access hello.txt: No such file or directory
pagrubel@fg005 BEE_Private$ ls ~/hello.txt
ls: cannot access /users/pagrubel/hello.txt: No such file or directory
pagrubel@fg005 BEE_Private$ ch-run /tmp/toss-tiny-3-5 --cd /home/$USER -- echo Hello > hello.txt
pagrubel@fg005 BEE_Private$ cat hello.txt
Hello
pagrubel@fg005 BEE_Private$ cat ~/hello.txt
cat: /users/pagrubel/hello.txt: No such file or directory
```

**Comment by reidpr** [comment]
Hi Pat,

```
$ ch-run /tmp/toss-tiny-3-5 --cd /home/$USER -- pwd;pwd
```

Here the first `pwd` is executed inside the container, but the second is executed on the host. The semicolon is being interpreted by your shell. If you want both interpreted inside the container, you could say:

```
$ ch-run /tmp/toss-tiny-3-5 --cd /home/$USER -- sh -c 'pwd;pwd'
```

Does that help?

**Comment by pagrubel** [comment]
Unfortunatley I didn't parse it in my head the way it is really parsed. Thanks for the answer, I'll close this issue.
