### ISSUE TITLE
tests: Spark: bump version and download from archive.apache.org

### ISSUE THREAD

**Issue by reidpr** [hpc/charliecloud#847]
Maybe we should compute the version somehow? Or is there somewhere we can download from that has old versions? This keeps happening, e.g. PR #807 just two months ago.

**Comment by rstyd** [comment]
Old releases are stored at https://archive.apache.org/dist/spark/ going back to 2014. We could switch to that over the main distribution mirror.

**Comment by reidpr** [comment]
Thanks Rusty! We'll try that.
