### ISSUE TITLE
ch-image: registry non-interactive authentication

### ISSUE THREAD

**Issue by reidpr** [hpc/charliecloud#849]
Currently, `ch-grow` requests credentials interactively from the user whenever they are needed. In #822, @tbugfinder proposes non-interactive authentication.

Approaches off the top of my head:

1. Piggy-back on Docker credentials file. This is tricky because it will be in `/root` if Docker is invoked with `sudo`, which is the recommended approach. However, we could add e.g. `--auth PATH` to use any file.

2. Command line options, e.g. `ch-grow pull --user foo --password b4r`. This reveals secrets to anyone who can see the history file but also more importantly `ps` output.

3. Environment variables, e.g. `CH_GROW_USER` and `CH_GROW_PASSWORD`. Hard to get secrets into these without leaking, but it won't be in `ps` output at least.

4. Credentials store such as the OS X keychain. This smells complicated.

Note that credentials may vary depending on the remote registry.

**Comment by tbugfinder** [comment]
If the registry is provided by a cloud provider, e.g. AWS ECR or Azure Container registry then authentication itself might depend on additional provider specific authentication mechanisms.

**Comment by tbugfinder** [comment]
Referring to 1.) IMHO using docker with sudo isn't common / recommended or needed. There's the docker group so that users can connect to the daemon.
It (1.) would help using AWS ECR as the aws credential helper could be used.

**Comment by reidpr** [comment]
> using docker with sudo isn't common / recommended or needed. There's the docker group so that users can connect to the daemon.

I believe the thinking here is that because adding people to the `docker` group is equivalent to root, many folks prefer to centralize privilege escalation through `sudo`. E.g.:

* Docker [manual section](https://docs.docker.com/engine/security/security/#docker-daemon-attack-surface).
* Stack Exchange [question](https://security.stackexchange.com/questions/178542/is-adding-docker-group-not-a-good-idea).

Thanks for the other information!
