### ISSUE TITLE
Preserving environment from a Docker image

### ISSUE THREAD

**Issue by DavidBrayford** [hpc/charliecloud#852]
Is there a way of preserving the Docker image environment when converting to a Charliecloud image?

As I've created a Docker image from a Dockerfile, which sets up the environment. I then run the docker image to test that the software is correctly configured, before converting the image to a Charliecloud image with ch-tar2dir. However, when I execute the Charliecloud image with ch-run the environment that was correctly configured in the Docker image is wiped in Charliecloud container.

David

**Comment by reidpr** [comment]
Hello David, modulo bugs, those variables should be in `/ch/environment` and you can set them with `ch-run --set-env=$IMG/ch/environment`; [more details](https://hpc.github.io/charliecloud/command-usage.html#setting-variables-with-set-env).

Of course, “modulo bugs” are pretty famous last words. Does the above work as you expect?

**Comment by DavidBrayford** [comment]
Thanks, ch-run --set-env=$IMG/ch/environment works great

**Comment by reidpr** [comment]
Fantastic! Glad we could help. Please let us know any further questions.
