### ISSUE TITLE
configure yum to stop if packages can't be found

### ISSUE THREAD

**Issue by reidpr** [hpc/charliecloud#858]
Turns out `yum -y` will [happily return success](https://bugzilla.redhat.com/show_bug.cgi?id=1274211) if *any* of the requested packages can be installed, not *all*. Because this behavior is ludicrous, and it can be [configured otherwise](https://serverfault.com/questions/694942) for CentOS/RHEL 7 and 8, let's configure it that way for all our tests and examples. Packages that we ask to install, but then silently aren't installed, causes confusing bugs.

Whether to do this in `yum.conf` or `yum` command lines I'm not sure. We do already have an option set multiple times on the command line; a second one would be pretty verbose.

**Comment by heasterday** [comment]
It looks like this is not the behavior for `dnf` so I'm thinking this will only effect `Dockerfile.centos7`, `Dockerfile.spack`, and potentially our `Vagrantfile`. I'm going to test added this via command line and see how messy it ends up.

**Comment by reidpr** [comment]
Sounds good. I recommend you don't finalize a patch until PR #857 lands b/c I already put in in `Dockerfile.centos7` (which you may want to adjust) on that branch.
