### ISSUE TITLE
build funkiness if .git present but Git not installed

### ISSUE THREAD

**Issue by reidpr** [hpc/charliecloud#86]
@olifre wonders in PR #84 what happens

> if a user somehow got hold of a Charliecloud checkout including .git, but does not actually have git installed on the machine used to compile. Then, not-so-helpful error messages will be generated.
>
> So maybe a check in the VERSION.full target and in the export target checking whether git is in path (before calling it) and producing a nicer error message would be helpful.

This is the result (abridged):

```
$ sudo mv /usr/bin/git /usr/bin/git.foo
$ make
printf '%s+%s%s\n' \
       $(cat VERSION) \
       $(git rev-parse --short HEAD) \
       $(git diff-index --quiet HEAD || echo '.dirty') \
       > VERSION.full
/bin/bash: git: command not found
/bin/bash: git: command not found
echo "#define VERSION \"$(cat VERSION.full)\"" > bin/version.h
echo "version () { echo 1>&2 '$(cat VERSION.full)'; }" > bin/version.sh
cd bin && make SETUID= all
[... successful build follows ...]
$ cat VERSION.full
0.2.3~pre+.dirty
```

I labeled this `enhancement` rather than `bug` because it seems like an unusual situation and the outcome is not so bad.

**Comment by reidpr** [comment]
`make export` does fail but the errors seem relatively straightforward:

```
$ make export
printf '%s+%s%s\n' \
       $(cat VERSION) \
       $(git rev-parse --short HEAD) \
       $(git diff-index --quiet HEAD || echo '.dirty') \
       > VERSION.full
/bin/bash: git: command not found
/bin/bash: git: command not found
test -d .git -a -f test/bats/.git  # need recursive Git checkout
git diff-index --quiet HEAD        # need clean working directory
/bin/bash: git: command not found
Makefile:48: recipe for target 'export' failed
make: *** [export] Error 127
```

**Comment by olifre** [comment]
That's less bad than I expected it to look like, all written together - well, in the first case, the `error` is a bit hidden. 
So yes, `build funkiness` is surely the more appropriate term here, and it's really only an enhancement ;-).

**Comment by reidpr** [comment]
I propose we simply change `make VERSION.full` to fail if `git` command is expected but not available. The errors seem OK and if they're near the end, they'll be sufficiently salient IMO.
