### ISSUE TITLE
Add MacOS Support

### ISSUE THREAD

**Issue by rstyd** [hpc/charliecloud#882]
Add support for building images via docker and pushing images via `ch-grow push` on MacOS. Will also require modifying `configure.ac` to support MacOS builds.

**Comment by pagrubel** [comment]
Is this the same as issue #42?

**Comment by reidpr** [comment]
It might be. #42 didn't articulate what that support would look like, but I think now we know what the options are.

**Comment by reidpr** [comment]
Closing in favor of #42.
