### ISSUE TITLE
`ch-run --set-env`: expand environment variables

### ISSUE THREAD

**Issue by DavidBrayford** [hpc/charliecloud#886]
Would it be possible to have a prepend PATH/LD_LIBRARY option in ch-run?

The example I have is a user wants to use the original Docker environment, but want to use executables and/or libraries from the host. For example, A user want to use the performance tools (perf), debugger, profiler that reside on the host system on a containerized application running on a HPC system

The following commands work,
```
ch-run --set-env=/image/ch/environment -b /host/dir/.:/host/dir image -- bash
export PATH=/host/dir/bin:$PATH
export LD_LIBRARY_PATH=/host/dir/lib:$LD_LIBRARY_PATH
 likwid-perfctr -m -g L2CACHE -C 0 julia mandelbrot.jl
```
However, passing in the parameters to ch-run be preferable when executing via a batch system such as Slurm.
For example,

`mpiexec -n 16 ch-run --set-env=/image/ch/environment --prepend-path=/host/dir/bin --prepend-ld_library_path=/host/dir/lib -b /host/dir/.:/host/dir image --   likwid-perfctr -m -g L2CACHE -C 0 julia mandelbrot.jl`

David

**Comment by reidpr** [comment]
Hi David, thanks for the feature request. Let me think a bit about how best to accomplish this.

Couple other workarounds that may work now:

* The container will read your dotfiles, so the exports could go there.
* `ch-run` mostly does not change environment variables, so they can be exported before `ch-run`.
* Can the bind-mount go to a directory that's already in the paths (e.g., `/usr/local/bin` and `/usr/local/lib`)?
