### ISSUE TITLE
Put warning about Cray branch in README

### ISSUE THREAD

**Issue by trandles-lanl** [hpc/charliecloud#89]
It needs to be clearly stated in the documentation that the Cray branch is the version of Charliecloud to use on all Cray systems until the patch for Cray Case #188073 is applied.  I spoke with a number of interested people at SC17 who are heading home to try out Charliecloud on their Crays.  I _think_ in all cases I told them about the crashing bug and the Cray branch, but I want this to be explicitly stated.

**Comment by reidpr** [comment]
I'll do this right now.

**Comment by reidpr** [comment]
@trandles-lanl, do you feel this is important to put in `README.rst` or is at the top of the [installation instructions](https://hpc.github.io/charliecloud/install.html) sufficient?

**Comment by trandles-lanl** [comment]
Both places?  I think it's important that we give ample warning before people inadvertently crash production resources and Charliecloud gets the blame for it.
