### ISSUE TITLE
ch-image: can't pull public images from nVidia NGC registry

### ISSUE THREAD

**Issue by reidpr** [hpc/charliecloud#897]
`ch-grow pull` does not work on [nVidia NGC](https://ngc.nvidia.com) images. For example:

```console
$ bin/ch-grow pull nvcr.io/nvidia/cuda:11.1-devel-ubuntu16.04
pulling image:   nvcr.io/nvidia/cuda:11.1-devel-ubuntu16.04
manifest: downloading
error: WWW-Authenticate missing key: service
```

Note, this may be hard to test because all the images I found were humongous.

**Comment by ajyounge** [comment]
NGC requires an API key, which needs to be procured ahead of time. Maybe just need a mechanism to point to a shared key file? I wish this NGC requirement would just go away.

https://docs.nvidia.com/dgx/ngc-registry-for-dgx-user-guide/

**Comment by cr458** [comment]
Hi, is there any way around this currently?

**Comment by reidpr** [comment]
Well, `ch-grow` makes assumptions that aren't correct for NGC. But, if you can build with Docker or Buildah, they probably are able to pull from NGC.

Also if you want to contact me behind the firewall I would be more than happy to discuss your specific needs a bit and try to come up with a path forward.

**Comment by reidpr** [comment]
This image might be good for testing; it's only 40MiB: https://ngc.nvidia.com/catalog/containers/hpc:foldingathome:fah-gpu

**Comment by reidpr** [comment]
It seems NGC does allow anonymous access now?
