### ISSUE TITLE
ch-image: only public image pulls work with Harbor

### ISSUE THREAD

**Issue by reidpr** [hpc/charliecloud#899]

**Comment by heasterday** [comment]
Tested this with a dev Harbor instance with the following results:
|  | public repo | private repo |
| ------------- | ------------- | ------------- |
| pull  | ✅  | ❌  |
| push  | ❌  | ❌  |

Push operations failed with a 403 and no prompt for credentials (even tried with the undocumented env vars). Pull operations failed with a 401.

**Comment by adrecord** [comment]
I was thinking this may be the same issue as #1318, so tried to repro it.  I couldn't repro this with current master even without the fix for 1318.  I was able to both push to and pull from a protected harbor repo, and ch asked for credentials in both cases.

**Comment by reidpr** [comment]
Thank you @adrecord, we'll close this. If someone else sees it, please feel free to comment and re-open.
