### ISSUE TITLE
ch-image: ENTRYPOINT support

### ISSUE THREAD

**Issue by qwofford** [hpc/charliecloud#930]
My experience with Docker leads me to assume that I can define an ENTRYPOINT in a Dockerfile and that this script will run prior to anything defined in SHELL or COMMAND. 

I use entrypoint.sh to define and set environment variables, and lacking this entrypoint mechanism can be a problem when converting some workflows. This can be resolved by prepending `. /entrypoint.sh` to SHELL or COMMAND, but this expectation mismatch can cause some confusion in my opinion.

**Comment by reidpr** [comment]
I think this is a duplicate of #780. If you have preferences on `ENTRYPOINT` vs. `CMD` vs. both equally, maybe you could put a comment there — that information would be helpful. Thanks for filing the issue!
