### ISSUE TITLE
remove packaging/debian?

### ISSUE THREAD

**Issue by reidpr** [hpc/charliecloud#935]
We have some Debian packaging material in the Charliecloud source code (directory `packaging/debian`, but it's unmaintained and AFAICT not used by anyone. The [actual Debian package](https://packages.debian.org/source/charliecloud) is ably maintained [elsewhere](https://salsa.debian.org/hpc-team/charliecloud). Thus, I'm inclined to remove `packaging/debian`.

Related: #113, #390.

@wiene @lnussbaum, any comments?

**Comment by wiene** [comment]
> Thus, I'm inclined to remove `packaging/debian`.

This is fine with me.

**Comment by lnussbaum** [comment]
Fine with me as well
