### ISSUE TITLE
bundle lark-parser with Charliecloud

### ISSUE THREAD

**Issue by shanegoff** [hpc/charliecloud#953]
Charliecloud currently needs users to manually install lark-parser in order to use `ch-image` which could be a barrier for people. If we shipped a version of lark-parser with Charliecloud we could default immediately to using unprivileged image building with `ch-image` instead of defaulting to docker. A lot of our builder scripts default to docker if you don't specify something else. With some changes users could not have to install docker or another builder.

Options

1. Install lark-parser using `setup.py` from either a git submodule or tar release
2. Include lark-parser as a submodule and just change charliecloud module paths to look for it internally instead of in the system python
3. Make `ch-image` a python module and let pip handle the requirements of requests and lark-parser
4. ??

There could be distribution options I have not considered or learned of we could explore.
lark-parser has an MIT license so we should be able to ship it with Charliecloud.
This could help clear up confusion for users between the lark module and lark-parser module.
This could simplify the install process for users.

**Comment by reidpr** [comment]
Newer Lark does have some nice features, so if it had a predictable version, we could take advantage of those.

**Comment by shanegoff** [comment]
So far there are several options for bundling lark-parser. We could use a git submodule but that puts extra steps on users to do a recursive clone. We could ship a release tar, unpack it, build lark, then manually put it in the right spot in the build phase. We can also just use the installer to install it only for the user, but that might get hairy if users are running as root.

Just running `python3 setup.py buildd` then copying the output under charliecloud/lib works out of the box with very little effort.
