### ISSUE TITLE
Change default ch-image build --bind behavior

### ISSUE THREAD

**Issue by qwofford** [hpc/charliecloud#977]
I'd like to propose changes to the default behavior of `--bind` during a `ch-image build`. It's very possible that I'm using these tools the wrong way, so feel free to educate me as needed.

1. The current `--bind` only supports binding directories. I would like to be able to bind files or directories into the container. ex- `ch-image build -b /usr/bin/gcc:/mnt/gcc`. Binding `/usr/bin` into `/mnt/` seems to be the alternative, which seems like overkill.
2. The current `--bind` will present an error if a destination path does not exist. I would like it if destination files/directories were created as necessary. Something like `mkdir -p`. ex- `ch-image build -b /usr/bin/gcc:/mnt/mystuff/gcc` would be a valid command .
3. The current `--bind` default behavior places the contents of a directory into `/mnt/` within the container during the course of a build. I would like the default behavior to mimic the host configuration and directory structure. ex- `ch-image build -b /my/long/path/ == ch-image build -b /my/long/path:/my/long/path`
4. The current `--bind` behavior is to bind things ephemerally. I would like the option to copy them into the destination. I would also like the option to keep them ephemeral. Maybe a `--bind-copy` option?

If these changes were to be implemented, pre-existing build scripts on a host system will require minimal changes to work during the container build process.

## Example
Consider a spack environment with a `packages.yaml` file that includes a reference to a package on the host `/my/fun/gcc`. Given the proposed changes I could run `ch-image build -b /my/fun/gcc` and build the spack environment with no modification. The current method would require that that I create directories `/my/fun` in some other way. I might try to create those directories in `RUN mkdir -p /my/fun` in the Dockerfile, but this command won't run before the bind operation so the bind operation will fail. Unless I'm mistaken, this means that without the proposed changes, it will be required for me to build a container with a preferred directory structure and then import it with a `FROM` statement in the Dockerfile, just so I can bind to a path that does not exist in the `FROM` base container.

**Comment by reidpr** [comment]
> * The current `--bind` only supports binding directories. I would like to be able to bind files or directories into the container. ex- `ch-image build -b /usr/bin/gcc:/mnt/gcc`. Binding `/usr/bin` into `/mnt/` seems to be the alternative, which seems like overkill.

I thought files worked (and we do just that internally). Did you confirm they don't?

That said, if you bind in just `/usr/bin/gcc`, I'd expect it to be very confused b/c the rest of its install will not be present.
 
> * The current `--bind` will present an error if a destination path does not exist. I would like it if destination files/directories were created as necessary. Something like `mkdir -p`. ex- `ch-image build -b /usr/bin/gcc:/mnt/mystuff/gcc` would be a valid command .

New issue #993 for this.

> * The current `--bind` default behavior places the contents of a directory into `/mnt/` within the container during the course of a build. I would like the default behavior to mimic the host configuration and directory structure. ex- `ch-image build -b /my/long/path/ == ch-image build -b /my/long/path:/my/long/path`

New issue #994 for this.

> * The current `--bind` behavior is to bind things ephemerally. I would like the option to copy them into the destination. I would also like the option to keep them ephemeral. Maybe a `--bind-copy` option?

Well, by definition a bind-mount is a mount, not a copy. But, in principle we could provide an option that was like `--bind` but instead did a copy.

You can do this now by providing `/` for the context (unlike Docker, this is safe because Charliecloud uses the filesystem directly rather than tarring it up) and then `COPY` instructions. Does that fit your use case?

**Comment by qwofford** [comment]
I might be using something incorrectly, but here's a reproducer:

```
-bash-4.2$ ch-image --version
0.22

-bash-4.2$ find .
.
./hello
./Dockerfile

-bash-4.2$ cat ./hello
hihihi

-bash-4.2$ cat Dockerfile 
FROM spack/centos7
RUN ls -altrh /mnt 
RUN cat /mnt/hello
```

## Binding files directly
What I did:
```
-bash-4.2$ ch-image build -t tmp -b ./hello:/mnt/hello -f ./Dockerfile .
  1 FROM spack/centos7 
available --force: rhel7: CentOS/RHEL 7
  2 RUN ['docker-shell', 'ls -altrh /mnt ']
ch-run[31738]: can't bind: not found: /ram/var/tmp/qwofford/ch-image/img/tmp/mnt/hello (ch_core.c:100)
error: build failed: current version of --force wouldn't help
error: build failed: RUN command exited with 1
```
What I expected:
```
-bash-4.2$ ch-image build -t tmp -b ./hello:/mnt/hello -f ./Dockerfile .
  1 FROM spack/centos7 
available --force: rhel7: CentOS/RHEL 7
  2 RUN ['docker-shell', 'ls -altrh /mnt ']
total 160K
drwxrwxr-x 17 root root 440 Mar  4 17:11 ..
-rw-rw-r--  1 root root   7 Mar  4 17:15 hello
-rw-rw-r--  1 root root  58 Mar  4 17:30 Dockerfile
drwxrwxr-x  3 root root  75 Mar  4 17:30 .
  3 RUN ['docker-shell', 'cat /mnt/hello']
hihihi
```
What I did:
```
-bash-4.2$ ch-image build -t tmp -b ./hello:/mnt/ -f ./Dockerfile .
  1 FROM spack/centos7 
available --force: rhel7: CentOS/RHEL 7
  2 RUN ['docker-shell', 'ls -altrh /mnt ']
ch-run[32301]: can't bind ./hello to /ram/var/tmp/qwofford/ch-image/img/tmp/mnt/: Not a directory (ch_core.c:105 20)
error: build failed: current version of --force wouldn't help
error: build failed: RUN command exited with 1
```
What I expected:
```
-bash-4.2$ ch-image build -t tmp -b ./hello:/mnt/hello -f ./Dockerfile .
  1 FROM spack/centos7 
available --force: rhel7: CentOS/RHEL 7
  2 RUN ['docker-shell', 'ls -altrh /mnt ']
total 160K
drwxrwxr-x 17 root root 440 Mar  4 17:11 ..
-rw-rw-r--  1 root root   7 Mar  4 17:15 hello
-rw-rw-r--  1 root root  58 Mar  4 17:30 Dockerfile
drwxrwxr-x  3 root root  75 Mar  4 17:30 .
  3 RUN ['docker-shell', 'cat /mnt/hello']
hihihi
```

**Comment by reidpr** [comment]
Bind-mounting files does work:

```
$ echo hello > /tmp/hello
$ bin/ch-run -b /tmp/hello:/etc/fstab $IMAGE -- cat /etc/fstab
hello
```

I think the error above is because the target mount point did not exist.

**Comment by reidpr** [comment]
With @qwofford's blessing, I'm closing this. Changes 1 and 2 are done in separate issues. Change 3 seems to not be a bug. Change 4 we decided is not needed at this time.
