### ISSUE TITLE
test suite fails on aarch64

### ISSUE THREAD

**Issue by j-ogas** [hpc/charliecloud#979]
`ch-test` depends on Dockerfiles in `test` and `examples`. These Dockerfiles pull x86_64 base images. Thus tests fail with `Exec format` errors from  `ch-run` on aarch64.

There a couple ways to handle this, e.g., add aarch64 Dockerfile variants, inject `arm64v8/` into the FROM tag at test build time, etc. In any case, perhaps `ch-test` should take an `--arch` argument; otherwise make a reasonable guess by default.

**Comment by reidpr** [comment]
See also #1017.

**Comment by reidpr** [comment]
See also #1252.
