### ISSUE TITLE
ch-builder2tar: Special handling of "/" vs "%"

### ISSUE THREAD

**Issue by qwofford** [hpc/charliecloud#983]
ch-image pull/build will place a prepared image into /var/tmp with "/" replaced with "%", however, when using ch-builder2tar "/" is preserved, and the user must know that "/" should be replaced with "%".

**Comment by reidpr** [comment]
Is this fixed in 0.22, which contains a fix for #957?

**Comment by qwofford** [comment]
Yes, that fixed it. I confirmed that it did not work in 0.21, and now does work in 0.22
