### ISSUE TITLE
ch-image build: inherit "--no-cache"

### ISSUE THREAD

**Issue by qwofford** [hpc/charliecloud#984]
I see the `--no-cache` option in `ch-image --help`, but not in `ch-image build --help`. Using this flag is natural for me when building, but I have to hunt to find that the argument is supported. Maybe it could be inherited?

**Comment by reidpr** [comment]
All the common options are inherited by the sub-commands.

Does that help?

**Comment by reidpr** [comment]
Closing b/c no further discussion and I think it's answered.
