### ISSUE TITLE
refactor Python code to take advantage of 3.6-isms

### ISSUE THREAD

**Issue by reidpr** [hpc/charliecloud#992]

**Comment by reidpr** [comment]
Background: Back in the day, Charliecloud supported an earlier version of Python. Then we updated to requiring 3.6. So, this issue is review all the Python code, and if there's anything that can be improved by dropping <3.6 compatibility, do that.

Note this issue does *not* include updating the code to use different string formatting. I want to stick with the `%` operator for now.

**Comment by lucaudill** [comment]
refactoring Python code in #1439
