### ISSUE TITLE
ch-image/ch-run --bind: default destination path is same as host

### ISSUE THREAD

**Issue by reidpr** [hpc/charliecloud#994]
From @qwofford in #977, which is about `ch-image build`, but IMO the behavior should be the same for `ch-run`:

> The current `--bind` default behavior places the contents of a directory into `/mnt/` within the container during the course of a build. I would like the default behavior to mimic the host configuration and directory structure. ex- `ch-image build -b /my/long/path` == `ch-image build -b /my/long/path:/my/long/path`

I will say that the reasoning for the `/mnt/[0-9]` was to *avoid* burdening containers with long paths from the host.

**Comment by reidpr** [comment]
Per discussion this morning, we will make this change.

**Comment by qwofford** [comment]
🎉 Thanks! For my notes, would this be a v0.23+ thing or something else?

**Comment by reidpr** [comment]
Real soon now? 😂 Let's discuss offline.
