### ISSUE TITLE
ch-image: new subcommand import

### ISSUE THREAD

**Issue by qwofford** [hpc/charliecloud#997]
It would be useful to have the ability to put a tar-ball or deployed container back into the Charliecloud build back-end at `/var/tmp/$(whoami)`. Something like a `ch-tar2builder`.

Scenario:

1. Dockerfile takes 4 hours 30 minutes to build. Let's say container is called A.
2. Maximum interactive allocation is 5 hours, and it is not acceptable to push this built container into a container registry.
3. New Dockerfile is defined, where the first line is "`FROM A`".

In order to build the Dockerfile in step 3, we need to first build the Dockerfile in step 1. However, at the completion of step 1, I only have 30 minutes of interactive development time.

If I were able to take a tarball and get it into the build system, that would allow me to quickly deploy the container in step 1 and begin dev work on the container in step 3 almost immediately after getting on an interactive compute node allocation.

**Comment by reidpr** [comment]
This feature request is not hard to do, but if you put your storage directory somewhere non-volatile, it won't get cleared when your allocation ends. I think for your use case this would be easier than messing with tarballs.

**Comment by qwofford** [comment]
Great! Thanks for the tip. Do you mean I should `cp -R` the storage directory and copy it back to `/var/tmp/$(whoami)` on subsequent allocations, or something else?

**Comment by reidpr** [comment]
Let's move that discussion internally.
